/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as WorkspacesNewRouteImport } from './routes/workspaces.new'
import { Route as WorkspaceSlugSettingsRouteImport } from './routes/$workspaceSlug.settings'
import { Route as WorkspaceSlugRuntimesRouteImport } from './routes/$workspaceSlug.runtimes'
import { Route as WorkspaceSlugMembersRouteImport } from './routes/$workspaceSlug.members'
import { Route as WorkspaceSlugIssuesRouteImport } from './routes/$workspaceSlug.issues'
import { Route as WorkspaceSlugChatRouteImport } from './routes/$workspaceSlug.chat'
import { Route as WorkspaceSlugAgentsRouteImport } from './routes/$workspaceSlug.agents'
import { Route as WorkspaceSlugRuntimesMachineIdRouteImport } from './routes/$workspaceSlug.runtimes_.$machineId'
import { Route as WorkspaceSlugIssuesIssueIdRouteImport } from './routes/$workspaceSlug.issues_.$issueId'
import { Route as WorkspaceSlugChatFilesRouteImport } from './routes/$workspaceSlug.chat_.files'
import { Route as WorkspaceSlugAgentsTeamsRouteImport } from './routes/$workspaceSlug.agents_.teams'
import { Route as WorkspaceSlugAgentsAgentIdRouteImport } from './routes/$workspaceSlug.agents_.$agentId'
import { Route as WorkspaceSlugIssuesProjectsProjectIdRouteImport } from './routes/$workspaceSlug.issues_.projects_.$projectId'
import { Route as WorkspaceSlugIssuesAutomationsAutopilotIdRouteImport } from './routes/$workspaceSlug.issues_.automations_.$autopilotId'
import { Route as WorkspaceSlugAgentsTeamsSquadIdRouteImport } from './routes/$workspaceSlug.agents_.teams_.$squadId'
import { Route as WorkspaceSlugAgentsNewManualRouteImport } from './routes/$workspaceSlug.agents_.new.manual'
import { Route as WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRouteImport } from './routes/$workspaceSlug.runtimes_.$machineId_.runtime.$runtimeId'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRoute = WorkspacesNewRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugSettingsRoute = WorkspaceSlugSettingsRouteImport.update({
  id: '/$workspaceSlug/settings',
  path: '/$workspaceSlug/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRuntimesRoute = WorkspaceSlugRuntimesRouteImport.update({
  id: '/$workspaceSlug/runtimes',
  path: '/$workspaceSlug/runtimes',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugMembersRoute = WorkspaceSlugMembersRouteImport.update({
  id: '/$workspaceSlug/members',
  path: '/$workspaceSlug/members',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIssuesRoute = WorkspaceSlugIssuesRouteImport.update({
  id: '/$workspaceSlug/issues',
  path: '/$workspaceSlug/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugChatRoute = WorkspaceSlugChatRouteImport.update({
  id: '/$workspaceSlug/chat',
  path: '/$workspaceSlug/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugAgentsRoute = WorkspaceSlugAgentsRouteImport.update({
  id: '/$workspaceSlug/agents',
  path: '/$workspaceSlug/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRuntimesMachineIdRoute =
  WorkspaceSlugRuntimesMachineIdRouteImport.update({
    id: '/$workspaceSlug/runtimes_/$machineId',
    path: '/$workspaceSlug/runtimes/$machineId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugIssuesIssueIdRoute =
  WorkspaceSlugIssuesIssueIdRouteImport.update({
    id: '/$workspaceSlug/issues_/$issueId',
    path: '/$workspaceSlug/issues/$issueId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugChatFilesRoute = WorkspaceSlugChatFilesRouteImport.update({
  id: '/$workspaceSlug/chat_/files',
  path: '/$workspaceSlug/chat/files',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugAgentsTeamsRoute =
  WorkspaceSlugAgentsTeamsRouteImport.update({
    id: '/$workspaceSlug/agents_/teams',
    path: '/$workspaceSlug/agents/teams',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugAgentsAgentIdRoute =
  WorkspaceSlugAgentsAgentIdRouteImport.update({
    id: '/$workspaceSlug/agents_/$agentId',
    path: '/$workspaceSlug/agents/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugIssuesProjectsProjectIdRoute =
  WorkspaceSlugIssuesProjectsProjectIdRouteImport.update({
    id: '/$workspaceSlug/issues_/projects_/$projectId',
    path: '/$workspaceSlug/issues/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugIssuesAutomationsAutopilotIdRoute =
  WorkspaceSlugIssuesAutomationsAutopilotIdRouteImport.update({
    id: '/$workspaceSlug/issues_/automations_/$autopilotId',
    path: '/$workspaceSlug/issues/automations/$autopilotId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugAgentsTeamsSquadIdRoute =
  WorkspaceSlugAgentsTeamsSquadIdRouteImport.update({
    id: '/$workspaceSlug/agents_/teams_/$squadId',
    path: '/$workspaceSlug/agents/teams/$squadId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugAgentsNewManualRoute =
  WorkspaceSlugAgentsNewManualRouteImport.update({
    id: '/$workspaceSlug/agents_/new/manual',
    path: '/$workspaceSlug/agents/new/manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRoute =
  WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRouteImport.update({
    id: '/$workspaceSlug/runtimes_/$machineId_/runtime/$runtimeId',
    path: '/$workspaceSlug/runtimes/$machineId/runtime/$runtimeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/$workspaceSlug/agents': typeof WorkspaceSlugAgentsRoute
  '/$workspaceSlug/chat': typeof WorkspaceSlugChatRoute
  '/$workspaceSlug/issues': typeof WorkspaceSlugIssuesRoute
  '/$workspaceSlug/members': typeof WorkspaceSlugMembersRoute
  '/$workspaceSlug/runtimes': typeof WorkspaceSlugRuntimesRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/$workspaceSlug/agents/$agentId': typeof WorkspaceSlugAgentsAgentIdRoute
  '/$workspaceSlug/agents/teams': typeof WorkspaceSlugAgentsTeamsRoute
  '/$workspaceSlug/chat/files': typeof WorkspaceSlugChatFilesRoute
  '/$workspaceSlug/issues/$issueId': typeof WorkspaceSlugIssuesIssueIdRoute
  '/$workspaceSlug/runtimes/$machineId': typeof WorkspaceSlugRuntimesMachineIdRoute
  '/$workspaceSlug/agents/new/manual': typeof WorkspaceSlugAgentsNewManualRoute
  '/$workspaceSlug/agents/teams/$squadId': typeof WorkspaceSlugAgentsTeamsSquadIdRoute
  '/$workspaceSlug/issues/automations/$autopilotId': typeof WorkspaceSlugIssuesAutomationsAutopilotIdRoute
  '/$workspaceSlug/issues/projects/$projectId': typeof WorkspaceSlugIssuesProjectsProjectIdRoute
  '/$workspaceSlug/runtimes/$machineId/runtime/$runtimeId': typeof WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRoute
}
export interface FileRoutesByTo {
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/$workspaceSlug/agents': typeof WorkspaceSlugAgentsRoute
  '/$workspaceSlug/chat': typeof WorkspaceSlugChatRoute
  '/$workspaceSlug/issues': typeof WorkspaceSlugIssuesRoute
  '/$workspaceSlug/members': typeof WorkspaceSlugMembersRoute
  '/$workspaceSlug/runtimes': typeof WorkspaceSlugRuntimesRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/$workspaceSlug/agents/$agentId': typeof WorkspaceSlugAgentsAgentIdRoute
  '/$workspaceSlug/agents/teams': typeof WorkspaceSlugAgentsTeamsRoute
  '/$workspaceSlug/chat/files': typeof WorkspaceSlugChatFilesRoute
  '/$workspaceSlug/issues/$issueId': typeof WorkspaceSlugIssuesIssueIdRoute
  '/$workspaceSlug/runtimes/$machineId': typeof WorkspaceSlugRuntimesMachineIdRoute
  '/$workspaceSlug/agents/new/manual': typeof WorkspaceSlugAgentsNewManualRoute
  '/$workspaceSlug/agents/teams/$squadId': typeof WorkspaceSlugAgentsTeamsSquadIdRoute
  '/$workspaceSlug/issues/automations/$autopilotId': typeof WorkspaceSlugIssuesAutomationsAutopilotIdRoute
  '/$workspaceSlug/issues/projects/$projectId': typeof WorkspaceSlugIssuesProjectsProjectIdRoute
  '/$workspaceSlug/runtimes/$machineId/runtime/$runtimeId': typeof WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/$workspaceSlug/agents': typeof WorkspaceSlugAgentsRoute
  '/$workspaceSlug/chat': typeof WorkspaceSlugChatRoute
  '/$workspaceSlug/issues': typeof WorkspaceSlugIssuesRoute
  '/$workspaceSlug/members': typeof WorkspaceSlugMembersRoute
  '/$workspaceSlug/runtimes': typeof WorkspaceSlugRuntimesRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/workspaces/new': typeof WorkspacesNewRoute
  '/$workspaceSlug/agents_/$agentId': typeof WorkspaceSlugAgentsAgentIdRoute
  '/$workspaceSlug/agents_/teams': typeof WorkspaceSlugAgentsTeamsRoute
  '/$workspaceSlug/chat_/files': typeof WorkspaceSlugChatFilesRoute
  '/$workspaceSlug/issues_/$issueId': typeof WorkspaceSlugIssuesIssueIdRoute
  '/$workspaceSlug/runtimes_/$machineId': typeof WorkspaceSlugRuntimesMachineIdRoute
  '/$workspaceSlug/agents_/new/manual': typeof WorkspaceSlugAgentsNewManualRoute
  '/$workspaceSlug/agents_/teams_/$squadId': typeof WorkspaceSlugAgentsTeamsSquadIdRoute
  '/$workspaceSlug/issues_/automations_/$autopilotId': typeof WorkspaceSlugIssuesAutomationsAutopilotIdRoute
  '/$workspaceSlug/issues_/projects_/$projectId': typeof WorkspaceSlugIssuesProjectsProjectIdRoute
  '/$workspaceSlug/runtimes_/$machineId_/runtime/$runtimeId': typeof WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/invite'
    | '/join'
    | '/$workspaceSlug/agents'
    | '/$workspaceSlug/chat'
    | '/$workspaceSlug/issues'
    | '/$workspaceSlug/members'
    | '/$workspaceSlug/runtimes'
    | '/$workspaceSlug/settings'
    | '/workspaces/new'
    | '/$workspaceSlug/agents/$agentId'
    | '/$workspaceSlug/agents/teams'
    | '/$workspaceSlug/chat/files'
    | '/$workspaceSlug/issues/$issueId'
    | '/$workspaceSlug/runtimes/$machineId'
    | '/$workspaceSlug/agents/new/manual'
    | '/$workspaceSlug/agents/teams/$squadId'
    | '/$workspaceSlug/issues/automations/$autopilotId'
    | '/$workspaceSlug/issues/projects/$projectId'
    | '/$workspaceSlug/runtimes/$machineId/runtime/$runtimeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/invite'
    | '/join'
    | '/$workspaceSlug/agents'
    | '/$workspaceSlug/chat'
    | '/$workspaceSlug/issues'
    | '/$workspaceSlug/members'
    | '/$workspaceSlug/runtimes'
    | '/$workspaceSlug/settings'
    | '/workspaces/new'
    | '/$workspaceSlug/agents/$agentId'
    | '/$workspaceSlug/agents/teams'
    | '/$workspaceSlug/chat/files'
    | '/$workspaceSlug/issues/$issueId'
    | '/$workspaceSlug/runtimes/$machineId'
    | '/$workspaceSlug/agents/new/manual'
    | '/$workspaceSlug/agents/teams/$squadId'
    | '/$workspaceSlug/issues/automations/$autopilotId'
    | '/$workspaceSlug/issues/projects/$projectId'
    | '/$workspaceSlug/runtimes/$machineId/runtime/$runtimeId'
  id:
    | '__root__'
    | '/invite'
    | '/join'
    | '/$workspaceSlug/agents'
    | '/$workspaceSlug/chat'
    | '/$workspaceSlug/issues'
    | '/$workspaceSlug/members'
    | '/$workspaceSlug/runtimes'
    | '/$workspaceSlug/settings'
    | '/workspaces/new'
    | '/$workspaceSlug/agents_/$agentId'
    | '/$workspaceSlug/agents_/teams'
    | '/$workspaceSlug/chat_/files'
    | '/$workspaceSlug/issues_/$issueId'
    | '/$workspaceSlug/runtimes_/$machineId'
    | '/$workspaceSlug/agents_/new/manual'
    | '/$workspaceSlug/agents_/teams_/$squadId'
    | '/$workspaceSlug/issues_/automations_/$autopilotId'
    | '/$workspaceSlug/issues_/projects_/$projectId'
    | '/$workspaceSlug/runtimes_/$machineId_/runtime/$runtimeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  InviteRoute: typeof InviteRoute
  JoinRoute: typeof JoinRoute
  WorkspaceSlugAgentsRoute: typeof WorkspaceSlugAgentsRoute
  WorkspaceSlugChatRoute: typeof WorkspaceSlugChatRoute
  WorkspaceSlugIssuesRoute: typeof WorkspaceSlugIssuesRoute
  WorkspaceSlugMembersRoute: typeof WorkspaceSlugMembersRoute
  WorkspaceSlugRuntimesRoute: typeof WorkspaceSlugRuntimesRoute
  WorkspaceSlugSettingsRoute: typeof WorkspaceSlugSettingsRoute
  WorkspacesNewRoute: typeof WorkspacesNewRoute
  WorkspaceSlugAgentsAgentIdRoute: typeof WorkspaceSlugAgentsAgentIdRoute
  WorkspaceSlugAgentsTeamsRoute: typeof WorkspaceSlugAgentsTeamsRoute
  WorkspaceSlugChatFilesRoute: typeof WorkspaceSlugChatFilesRoute
  WorkspaceSlugIssuesIssueIdRoute: typeof WorkspaceSlugIssuesIssueIdRoute
  WorkspaceSlugRuntimesMachineIdRoute: typeof WorkspaceSlugRuntimesMachineIdRoute
  WorkspaceSlugAgentsNewManualRoute: typeof WorkspaceSlugAgentsNewManualRoute
  WorkspaceSlugAgentsTeamsSquadIdRoute: typeof WorkspaceSlugAgentsTeamsSquadIdRoute
  WorkspaceSlugIssuesAutomationsAutopilotIdRoute: typeof WorkspaceSlugIssuesAutomationsAutopilotIdRoute
  WorkspaceSlugIssuesProjectsProjectIdRoute: typeof WorkspaceSlugIssuesProjectsProjectIdRoute
  WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRoute: typeof WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/settings': {
      id: '/$workspaceSlug/settings'
      path: '/$workspaceSlug/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/runtimes': {
      id: '/$workspaceSlug/runtimes'
      path: '/$workspaceSlug/runtimes'
      fullPath: '/$workspaceSlug/runtimes'
      preLoaderRoute: typeof WorkspaceSlugRuntimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/members': {
      id: '/$workspaceSlug/members'
      path: '/$workspaceSlug/members'
      fullPath: '/$workspaceSlug/members'
      preLoaderRoute: typeof WorkspaceSlugMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/issues': {
      id: '/$workspaceSlug/issues'
      path: '/$workspaceSlug/issues'
      fullPath: '/$workspaceSlug/issues'
      preLoaderRoute: typeof WorkspaceSlugIssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/chat': {
      id: '/$workspaceSlug/chat'
      path: '/$workspaceSlug/chat'
      fullPath: '/$workspaceSlug/chat'
      preLoaderRoute: typeof WorkspaceSlugChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/agents': {
      id: '/$workspaceSlug/agents'
      path: '/$workspaceSlug/agents'
      fullPath: '/$workspaceSlug/agents'
      preLoaderRoute: typeof WorkspaceSlugAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/runtimes_/$machineId': {
      id: '/$workspaceSlug/runtimes_/$machineId'
      path: '/$workspaceSlug/runtimes/$machineId'
      fullPath: '/$workspaceSlug/runtimes/$machineId'
      preLoaderRoute: typeof WorkspaceSlugRuntimesMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/issues_/$issueId': {
      id: '/$workspaceSlug/issues_/$issueId'
      path: '/$workspaceSlug/issues/$issueId'
      fullPath: '/$workspaceSlug/issues/$issueId'
      preLoaderRoute: typeof WorkspaceSlugIssuesIssueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/chat_/files': {
      id: '/$workspaceSlug/chat_/files'
      path: '/$workspaceSlug/chat/files'
      fullPath: '/$workspaceSlug/chat/files'
      preLoaderRoute: typeof WorkspaceSlugChatFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/agents_/teams': {
      id: '/$workspaceSlug/agents_/teams'
      path: '/$workspaceSlug/agents/teams'
      fullPath: '/$workspaceSlug/agents/teams'
      preLoaderRoute: typeof WorkspaceSlugAgentsTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/agents_/$agentId': {
      id: '/$workspaceSlug/agents_/$agentId'
      path: '/$workspaceSlug/agents/$agentId'
      fullPath: '/$workspaceSlug/agents/$agentId'
      preLoaderRoute: typeof WorkspaceSlugAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/issues_/projects_/$projectId': {
      id: '/$workspaceSlug/issues_/projects_/$projectId'
      path: '/$workspaceSlug/issues/projects/$projectId'
      fullPath: '/$workspaceSlug/issues/projects/$projectId'
      preLoaderRoute: typeof WorkspaceSlugIssuesProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/issues_/automations_/$autopilotId': {
      id: '/$workspaceSlug/issues_/automations_/$autopilotId'
      path: '/$workspaceSlug/issues/automations/$autopilotId'
      fullPath: '/$workspaceSlug/issues/automations/$autopilotId'
      preLoaderRoute: typeof WorkspaceSlugIssuesAutomationsAutopilotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/agents_/teams_/$squadId': {
      id: '/$workspaceSlug/agents_/teams_/$squadId'
      path: '/$workspaceSlug/agents/teams/$squadId'
      fullPath: '/$workspaceSlug/agents/teams/$squadId'
      preLoaderRoute: typeof WorkspaceSlugAgentsTeamsSquadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/agents_/new/manual': {
      id: '/$workspaceSlug/agents_/new/manual'
      path: '/$workspaceSlug/agents/new/manual'
      fullPath: '/$workspaceSlug/agents/new/manual'
      preLoaderRoute: typeof WorkspaceSlugAgentsNewManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/runtimes_/$machineId_/runtime/$runtimeId': {
      id: '/$workspaceSlug/runtimes_/$machineId_/runtime/$runtimeId'
      path: '/$workspaceSlug/runtimes/$machineId/runtime/$runtimeId'
      fullPath: '/$workspaceSlug/runtimes/$machineId/runtime/$runtimeId'
      preLoaderRoute: typeof WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  InviteRoute: InviteRoute,
  JoinRoute: JoinRoute,
  WorkspaceSlugAgentsRoute: WorkspaceSlugAgentsRoute,
  WorkspaceSlugChatRoute: WorkspaceSlugChatRoute,
  WorkspaceSlugIssuesRoute: WorkspaceSlugIssuesRoute,
  WorkspaceSlugMembersRoute: WorkspaceSlugMembersRoute,
  WorkspaceSlugRuntimesRoute: WorkspaceSlugRuntimesRoute,
  WorkspaceSlugSettingsRoute: WorkspaceSlugSettingsRoute,
  WorkspacesNewRoute: WorkspacesNewRoute,
  WorkspaceSlugAgentsAgentIdRoute: WorkspaceSlugAgentsAgentIdRoute,
  WorkspaceSlugAgentsTeamsRoute: WorkspaceSlugAgentsTeamsRoute,
  WorkspaceSlugChatFilesRoute: WorkspaceSlugChatFilesRoute,
  WorkspaceSlugIssuesIssueIdRoute: WorkspaceSlugIssuesIssueIdRoute,
  WorkspaceSlugRuntimesMachineIdRoute: WorkspaceSlugRuntimesMachineIdRoute,
  WorkspaceSlugAgentsNewManualRoute: WorkspaceSlugAgentsNewManualRoute,
  WorkspaceSlugAgentsTeamsSquadIdRoute: WorkspaceSlugAgentsTeamsSquadIdRoute,
  WorkspaceSlugIssuesAutomationsAutopilotIdRoute:
    WorkspaceSlugIssuesAutomationsAutopilotIdRoute,
  WorkspaceSlugIssuesProjectsProjectIdRoute:
    WorkspaceSlugIssuesProjectsProjectIdRoute,
  WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRoute:
    WorkspaceSlugRuntimesMachineIdRuntimeRuntimeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
