// AUTO-GENERATED by scripts/generate-text-preview-types.mjs.
// Do not edit by hand — edit server/internal/handler/text_preview_types.json
// and run `pnpm generate:text-preview-types`.

export const TEXT_CONTENT_TYPES: ReadonlySet<string> = new Set([
  "application/json",
  "application/javascript",
  "application/xml",
  "application/x-yaml",
  "application/yaml",
  "application/toml",
  "application/x-sh",
  "application/x-httpd-php",
]);

export const TEXT_EXTENSIONS: ReadonlySet<string> = new Set([
  // Markdown
  "md",
  "markdown",
  // Plain text
  "txt",
  "log",
  "csv",
  "tsv",
  "gitignore",
  // Web
  "html",
  "htm",
  "xml",
  // Stylesheets
  "css",
  // Sass
  "scss",
  "sass",
  // Less
  "less",
  // JSON
  "json",
  // YAML
  "yml",
  "yaml",
  // INI-style config
  "toml",
  "ini",
  "conf",
  // Build files
  "dockerfile",
  // Makefiles
  "makefile",
  // Shell
  "sh",
  "bash",
  "zsh",
  // Python
  "py",
  // Ruby
  "rb",
  // Go
  "go",
  // Rust
  "rs",
  // TypeScript
  "ts",
  "tsx",
  // JavaScript
  "js",
  "jsx",
  "mjs",
  "cjs",
  // Java
  "java",
  // Kotlin
  "kt",
  // Swift
  "swift",
  // C
  "c",
  "h",
  // C++
  "cc",
  "cpp",
  "hpp",
  // C#
  "cs",
  // PHP
  "php",
  // Lua
  "lua",
  // Vim script
  "vim",
  // SQL
  "sql",
]);

export const TEXT_BASENAMES: ReadonlySet<string> = new Set([
  // Dockerfile
  "dockerfile",
  // Makefile
  "makefile",
  // Environment and ignore files
  ".env",
  ".gitignore",
]);

export const TEXT_EXTENSION_LANGUAGE_MAP: Readonly<Record<string, string>> = {
  // Markdown
  "md": "markdown",
  "markdown": "markdown",
  // Plain text
  "txt": "plaintext",
  "log": "plaintext",
  "csv": "plaintext",
  "tsv": "plaintext",
  "gitignore": "plaintext",
  // Web
  "html": "xml",
  "htm": "xml",
  "xml": "xml",
  // Stylesheets
  "css": "css",
  // Sass
  "scss": "scss",
  "sass": "scss",
  // Less
  "less": "less",
  // JSON
  "json": "json",
  // YAML
  "yml": "yaml",
  "yaml": "yaml",
  // INI-style config
  "toml": "ini",
  "ini": "ini",
  "conf": "ini",
  // Build files
  "dockerfile": "dockerfile",
  // Makefiles
  "makefile": "makefile",
  // Shell
  "sh": "bash",
  "bash": "bash",
  "zsh": "bash",
  // Python
  "py": "python",
  // Ruby
  "rb": "ruby",
  // Go
  "go": "go",
  // Rust
  "rs": "rust",
  // TypeScript
  "ts": "typescript",
  "tsx": "typescript",
  // JavaScript
  "js": "javascript",
  "jsx": "javascript",
  "mjs": "javascript",
  "cjs": "javascript",
  // Java
  "java": "java",
  // Kotlin
  "kt": "kotlin",
  // Swift
  "swift": "swift",
  // C
  "c": "c",
  "h": "c",
  // C++
  "cc": "cpp",
  "cpp": "cpp",
  "hpp": "cpp",
  // C#
  "cs": "csharp",
  // PHP
  "php": "php",
  // Lua
  "lua": "lua",
  // Vim script
  "vim": "vim",
  // SQL
  "sql": "sql",
};

export const TEXT_BASENAME_LANGUAGE_MAP: Readonly<Record<string, string>> = {
  // Dockerfile
  "dockerfile": "dockerfile",
  // Makefile
  "makefile": "makefile",
  // Environment and ignore files
  ".env": "plaintext",
  ".gitignore": "plaintext",
};
