package main

import (
	"fmt"
	"log/slog"
	"net/http"

	"github.com/google/go-github/v60/github"
)

func (s *Server) handleGitHubWebhook(w http.ResponseWriter, r *http.Request) {
	payload, err := github.ValidatePayload(r, []byte(s.cfg.GitHubWebhookSecret))
	if err != nil {
		slog.Warn("webhook signature invalid", "error", err)
		http.Error(w, "invalid signature", http.StatusUnauthorized)
		return
	}

	deliveryID := r.Header.Get("X-GitHub-Delivery")
	eventType := github.WebHookType(r)

	if deliveryID != "" {
		if hit, ok := s.dedup.Lookup(deliveryID); ok {
			slog.Info("webhook dedup hit",
				"delivery", deliveryID,
				"multica_issue", hit.MulticaIssueIdentifier,
			)
			writeJSON(w, http.StatusOK, map[string]any{
				"ok":                       true,
				"deduplicated":             true,
				"multica_issue_id":         hit.MulticaIssueID,
				"multica_issue_identifier": hit.MulticaIssueIdentifier,
			})
			return
		}
	}

	evt, err := github.ParseWebHook(eventType, payload)
	if err != nil {
		slog.Warn("webhook parse failed", "error", err, "type", eventType)
		http.Error(w, "parse failed", http.StatusBadRequest)
		return
	}

	pre, ok := evt.(*github.PullRequestEvent)
	if !ok {
		writeJSON(w, http.StatusOK, map[string]any{"ok": true, "ignored": "non-pr-event"})
		return
	}

	action := pre.GetAction()
	if action != "opened" && action != "synchronize" {
		writeJSON(w, http.StatusOK, map[string]any{"ok": true, "ignored": "action=" + action})
		return
	}

	repo := pre.GetRepo()
	repoFull := repo.GetFullName()
	if !s.cfg.RepoAllowed(repoFull) {
		slog.Info("webhook repo not in allowlist", "repo", repoFull)
		writeJSON(w, http.StatusOK, map[string]any{"ok": true, "ignored": "repo-not-allowed"})
		return
	}

	installationID := pre.GetInstallation().GetID()
	if installationID == 0 {
		slog.Warn("webhook missing installation id", "delivery", deliveryID, "repo", repoFull)
		http.Error(w, "no installation id", http.StatusBadRequest)
		return
	}

	pr := pre.GetPullRequest()
	prNumber := pre.GetNumber()
	headSHA := pr.GetHead().GetSHA()
	author := pr.GetUser().GetLogin()

	nonce, err := s.nonces.Put(PRContext{
		InstallationID: installationID,
		Owner:          repo.GetOwner().GetLogin(),
		Repo:           repo.GetName(),
		PRNumber:       prNumber,
		HeadSHA:        headSHA,
	})
	if err != nil {
		slog.Error("nonce put failed", "error", err)
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	body := buildIssueBody(issueBodyData{
		Repo:        repoFull,
		PRNumber:    prNumber,
		PRTitle:     pr.GetTitle(),
		PRURL:       pr.GetHTMLURL(),
		HeadSHA:     headSHA,
		Author:      author,
		CallbackURL: s.cfg.SidecarPublicURL + "/installation-token?nonce=" + nonce,
	})

	issue, err := s.multica.CreateIssue(r.Context(), CreateIssueRequest{
		Title:        fmt.Sprintf("Review PR #%d: %s", prNumber, pr.GetTitle()),
		Description:  body,
		AssigneeType: "agent",
		AssigneeID:   s.cfg.PRReviewerAgentID,
	})
	if err != nil {
		slog.Error("multica create-issue failed",
			"delivery", deliveryID,
			"repo", repoFull,
			"pr", prNumber,
			"error", err,
		)
		http.Error(w, "multica unavailable", http.StatusInternalServerError)
		return
	}

	if deliveryID != "" {
		s.dedup.Store(deliveryID, DeliveryResult{
			MulticaIssueID:         issue.ID,
			MulticaIssueIdentifier: issue.Identifier,
		})
	}

	slog.Info("webhook handled",
		"delivery", deliveryID,
		"repo", repoFull,
		"pr", prNumber,
		"action", action,
		"multica_issue", issue.Identifier,
	)

	writeJSON(w, http.StatusAccepted, map[string]any{
		"ok":                       true,
		"multica_issue_id":         issue.ID,
		"multica_issue_identifier": issue.Identifier,
	})
}

type issueBodyData struct {
	Repo        string
	PRNumber    int
	PRTitle     string
	PRURL       string
	HeadSHA     string
	Author      string
	CallbackURL string
}

const issueBodyTpl = "## PR Context (auto-generated by pr-agent-sidecar)\n\n" +
	"- **Repo:** `%s`\n" +
	"- **PR:** #%d — %s\n" +
	"- **URL:** %s\n" +
	"- **Head SHA:** `%s`\n" +
	"- **Author:** @%s\n" +
	"- **Token callback:** %s\n\n" +
	"---\n\n" +
	"Review this PR and post a single summary comment. Use the `pr-reviewer` skill.\n"

func buildIssueBody(d issueBodyData) string {
	return fmt.Sprintf(issueBodyTpl,
		d.Repo,
		d.PRNumber, d.PRTitle,
		d.PRURL,
		d.HeadSHA,
		d.Author,
		d.CallbackURL,
	)
}
