package workflows

import (
	"crypto/sha256"
	"encoding/hex"
)

// IdempotencyKey hashes the inputs into the stable string we use as the
// (workflow_id, key) primary key in cerebro_workflow_idempotency_key.
//
// `eventID` is the unique identifier for the domain event being processed
// (typically a UUID generated by the publisher). `actionID` is the workflow's
// own action_id (we use the workflow ID — every workflow has exactly one
// action in phase 1). The hash combines them so the same (event, workflow)
// pair always produces the same key, and different ones never collide.
func IdempotencyKey(eventID, actionID string) string {
	h := sha256.New()
	h.Write([]byte(eventID))
	h.Write([]byte{0}) // separator so "ab"+"c" hashes differently than "a"+"bc"
	h.Write([]byte(actionID))
	return hex.EncodeToString(h.Sum(nil))
}
