apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agentfarm
  annotations:
    $patch: replace
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($http_x_forwarded_proto = 'http') {
        return 301 https://$host$request_uri;
      }
    external-dns.alpha.kubernetes.io/hostname: agentfarm.development.g2.com
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: nginx-internal
  rules:
    - host: agentfarm.development.g2.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agentfarm-web
                port:
                  name: http
