apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentfarm-secret-store
spec:
  dataFrom:
    - find:
        name:
          regexp: "(?i)^/agentfarm/development/.*"
      rewrite:
        - regexp:
            source: "(?i)^/agentfarm/development/(.*)"
            target: "$1"
