import { api, parseWithFallback } from "@multica/core/api";
import { DEFAULT_SETTINGS, EMPTY_CONNECTIONS, EMPTY_ELEMENTS, EMPTY_GOAL_TYPES, EMPTY_MEETING, EMPTY_ORG_CHART, EMPTY_PERIODS, EMPTY_ROCKS, EMPTY_STRATEGY, EMPTY_STRATEGY_HISTORY, EMPTY_VISION_PLAN, goalTypeListSchema, goalTypeSchema, meetingSchema, objectConnectionListSchema, objectConnectionSchema, operatingPeriodListSchema, operatingPeriodSchema, operatingSystemSettingsSchema, orgChartSeatListSchema, orgChartSeatSchema, osElementListSchema, osElementSchema, rockCheckInSchema, rockSchema, rocksListSchema, strategyHistoryListSchema, strategyItemSchema, strategyListSchema, visionPlanItemSchema, visionPlanPageSchema, visionPlanSchema, visionPlanSectionSchema } from "./api-schemas";
import type { GoalType, GoalTypeInput, GoalTypeList, MeetingConfig, MeetingConfigInput, ObjectConnection, ObjectConnectionInput, ObjectConnectionList, OperatingPeriod, OperatingPeriodInput, OperatingPeriodList, OperatingSystemSettings, OrgChartSeat, OrgChartSeatInput, OrgChartSeatList, OsElement, OsElementList, Rock, RockCheckIn, RockCheckInInput, RockInput, RocksList, StrategyHistoryList, StrategyItem, StrategyItemInput, StrategyList, Terminology, VisionPlan, VisionPlanItem, VisionPlanItemInput, VisionPlanPage, VisionPlanPageInput, VisionPlanSection, VisionPlanSectionInput } from "./types";

export async function fetchSettings(): Promise<OperatingSystemSettings> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-system/settings"); return parseWithFallback(raw, operatingSystemSettingsSchema, DEFAULT_SETTINGS, { endpoint: "fetchOperatingSystemSettings" }); }
export async function updateSettings(terminology: Terminology): Promise<OperatingSystemSettings> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-system/settings", { method: "PUT", body: JSON.stringify({ terminology }) }); return parseWithFallback(raw, operatingSystemSettingsSchema, DEFAULT_SETTINGS, { endpoint: "updateOperatingSystemSettings" }); }
export async function fetchMeeting(): Promise<MeetingConfig> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/meetings"); return parseWithFallback(raw, meetingSchema, EMPTY_MEETING, { endpoint: "fetchOperatingMeeting" }); }
export async function updateMeeting(input: MeetingConfigInput): Promise<MeetingConfig | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/meetings", { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, meetingSchema, null, { endpoint: "updateOperatingMeeting" }); }
export async function fetchOrgChart(): Promise<OrgChartSeatList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/org-chart"); return parseWithFallback(raw, orgChartSeatListSchema, EMPTY_ORG_CHART, { endpoint: "fetchOrgChart" }); }
export async function createOrgChartSeat(input: OrgChartSeatInput): Promise<OrgChartSeat | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/org-chart/seats", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, orgChartSeatSchema, null, { endpoint: "createOrgChartSeat" }); }
export async function updateOrgChartSeat(id: string, input: OrgChartSeatInput): Promise<OrgChartSeat | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/org-chart/seats/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, orgChartSeatSchema, null, { endpoint: "updateOrgChartSeat" }); }
export async function deleteOrgChartSeat(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/org-chart/seats/${id}`, { method: "DELETE" }); }
export async function fetchPeriods(): Promise<OperatingPeriodList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-periods"); return parseWithFallback(raw, operatingPeriodListSchema, EMPTY_PERIODS, { endpoint: "fetchOperatingPeriods" }); }
export async function createPeriod(input: OperatingPeriodInput): Promise<OperatingPeriod | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-periods", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, operatingPeriodSchema, null, { endpoint: "createOperatingPeriod" }); }
export async function updatePeriod(id: string, input: OperatingPeriodInput): Promise<OperatingPeriod | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/operating-periods/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, operatingPeriodSchema, null, { endpoint: "updateOperatingPeriod" }); }
export async function deletePeriod(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/operating-periods/${id}`, { method: "DELETE" }); }
export async function fetchElements(): Promise<OsElementList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-system/elements"); return parseWithFallback(raw, osElementListSchema, EMPTY_ELEMENTS, { endpoint: "fetchOperatingSystemElements" }); }
export async function updateElement(key: string, enabled: boolean): Promise<OsElement | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/operating-system/elements/${encodeURIComponent(key)}`, { method: "PUT", body: JSON.stringify({ enabled }) }); return parseWithFallback(raw, osElementSchema, null, { endpoint: "updateOperatingSystemElement" }); }
export async function fetchGoalTypes(): Promise<GoalTypeList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/goal-types"); return parseWithFallback(raw, goalTypeListSchema, EMPTY_GOAL_TYPES, { endpoint: "fetchGoalTypes" }); }
export async function createGoalType(input: GoalTypeInput): Promise<GoalType | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/goal-types", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, goalTypeSchema, null, { endpoint: "createGoalType" }); }
export async function updateGoalType(id: string, input: GoalTypeInput): Promise<GoalType | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/goal-types/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, goalTypeSchema, null, { endpoint: "updateGoalType" }); }
export async function deleteGoalType(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/goal-types/${id}`, { method: "DELETE" }); }
export async function fetchStrategy(): Promise<StrategyList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/strategy-items"); return parseWithFallback(raw, strategyListSchema, EMPTY_STRATEGY, { endpoint: "fetchStrategy" }); }
export async function fetchStrategyHistory(): Promise<StrategyHistoryList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/strategy-history"); return parseWithFallback(raw, strategyHistoryListSchema, EMPTY_STRATEGY_HISTORY, { endpoint: "fetchStrategyHistory" }); }
export async function createStrategyItem(input: StrategyItemInput): Promise<StrategyItem | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/strategy-items", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, strategyItemSchema, null, { endpoint: "createStrategyItem" }); }
export async function updateStrategyItem(id: string, input: StrategyItemInput): Promise<StrategyItem | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/strategy-items/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, strategyItemSchema, null, { endpoint: "updateStrategyItem" }); }
export async function fetchRocks(): Promise<RocksList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/rocks"); return parseWithFallback(raw, rocksListSchema, EMPTY_ROCKS, { endpoint: "fetchRocks" }); }
export async function createRock(input: RockInput): Promise<Rock | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/rocks", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, rockSchema, null, { endpoint: "createRock" }); }
export async function updateRock(id: string, input: RockInput): Promise<Rock | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/rocks/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, rockSchema, null, { endpoint: "updateRock" }); }
export async function addRockCheckIn(id: string, input: RockCheckInInput): Promise<RockCheckIn | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/rocks/${id}/check-ins`, { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, rockCheckInSchema, null, { endpoint: "addRockCheckIn" }); }
export async function fetchConnections(objectType: string, objectId: string): Promise<ObjectConnectionList> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/object-connections?object_type=${encodeURIComponent(objectType)}&object_id=${encodeURIComponent(objectId)}`); return parseWithFallback(raw, objectConnectionListSchema, EMPTY_CONNECTIONS, { endpoint: "fetchOperatingSystemConnections" }); }
export async function createConnection(input: ObjectConnectionInput): Promise<ObjectConnection | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/object-connections", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, objectConnectionSchema, null, { endpoint: "createOperatingSystemConnection" }); }
export async function deleteConnection(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/object-connections/${id}`, { method: "DELETE" }); }
export async function fetchVisionPlan(): Promise<VisionPlan> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/vision-plan"); return parseWithFallback(raw, visionPlanSchema, EMPTY_VISION_PLAN, { endpoint: "fetchVisionPlan" }); }
export async function createVisionPlanPage(input: VisionPlanPageInput): Promise<VisionPlanPage | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/vision-plan/pages", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, visionPlanPageSchema, null, { endpoint: "createVisionPlanPage" }); }
export async function updateVisionPlanPage(id: string, input: VisionPlanPageInput): Promise<VisionPlanPage | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/vision-plan/pages/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, visionPlanPageSchema, null, { endpoint: "updateVisionPlanPage" }); }
export async function deleteVisionPlanPage(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/vision-plan/pages/${id}`, { method: "DELETE" }); }
export async function createVisionPlanSection(input: VisionPlanSectionInput): Promise<VisionPlanSection | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/vision-plan/sections", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, visionPlanSectionSchema, null, { endpoint: "createVisionPlanSection" }); }
export async function updateVisionPlanSection(id: string, input: VisionPlanSectionInput): Promise<VisionPlanSection | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/vision-plan/sections/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, visionPlanSectionSchema, null, { endpoint: "updateVisionPlanSection" }); }
export async function deleteVisionPlanSection(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/vision-plan/sections/${id}`, { method: "DELETE" }); }
export async function createVisionPlanItem(input: VisionPlanItemInput): Promise<VisionPlanItem | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/vision-plan/items", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, visionPlanItemSchema, null, { endpoint: "createVisionPlanItem" }); }
export async function updateVisionPlanItem(id: string, input: VisionPlanItemInput): Promise<VisionPlanItem | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/vision-plan/items/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, visionPlanItemSchema, null, { endpoint: "updateVisionPlanItem" }); }
export async function deleteVisionPlanItem(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/vision-plan/items/${id}`, { method: "DELETE" }); }
