import { api, parseWithFallback } from "@multica/core/api";
import { DEFAULT_SETTINGS, EMPTY_CONNECTIONS, EMPTY_ELEMENTS, EMPTY_GOAL_TYPES, EMPTY_PERIODS, EMPTY_ROCKS, EMPTY_STRATEGY, EMPTY_STRATEGY_HISTORY, goalTypeListSchema, goalTypeSchema, objectConnectionListSchema, objectConnectionSchema, operatingPeriodListSchema, operatingPeriodSchema, operatingSystemSettingsSchema, osElementListSchema, osElementSchema, rockCheckInSchema, rockSchema, rocksListSchema, strategyHistoryListSchema, strategyItemSchema, strategyListSchema } from "./api-schemas";
import type { GoalType, GoalTypeInput, GoalTypeList, ObjectConnection, ObjectConnectionInput, ObjectConnectionList, OperatingPeriod, OperatingPeriodInput, OperatingPeriodList, OperatingSystemSettings, OsElement, OsElementList, Rock, RockCheckIn, RockCheckInInput, RockInput, RocksList, StrategyHistoryList, StrategyItem, StrategyItemInput, StrategyList, Terminology } from "./types";

export async function fetchSettings(): Promise<OperatingSystemSettings> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-system/settings"); return parseWithFallback(raw, operatingSystemSettingsSchema, DEFAULT_SETTINGS, { endpoint: "fetchOperatingSystemSettings" }); }
export async function updateSettings(terminology: Terminology): Promise<OperatingSystemSettings> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-system/settings", { method: "PUT", body: JSON.stringify({ terminology }) }); return parseWithFallback(raw, operatingSystemSettingsSchema, DEFAULT_SETTINGS, { endpoint: "updateOperatingSystemSettings" }); }
export async function fetchPeriods(): Promise<OperatingPeriodList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-periods"); return parseWithFallback(raw, operatingPeriodListSchema, EMPTY_PERIODS, { endpoint: "fetchOperatingPeriods" }); }
export async function createPeriod(input: OperatingPeriodInput): Promise<OperatingPeriod | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-periods", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, operatingPeriodSchema, null, { endpoint: "createOperatingPeriod" }); }
export async function updatePeriod(id: string, input: OperatingPeriodInput): Promise<OperatingPeriod | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/operating-periods/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, operatingPeriodSchema, null, { endpoint: "updateOperatingPeriod" }); }
export async function deletePeriod(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/operating-periods/${id}`, { method: "DELETE" }); }
export async function fetchElements(): Promise<OsElementList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/operating-system/elements"); return parseWithFallback(raw, osElementListSchema, EMPTY_ELEMENTS, { endpoint: "fetchOperatingSystemElements" }); }
export async function updateElement(key: string, enabled: boolean): Promise<OsElement | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/operating-system/elements/${encodeURIComponent(key)}`, { method: "PUT", body: JSON.stringify({ enabled }) }); return parseWithFallback(raw, osElementSchema, null, { endpoint: "updateOperatingSystemElement" }); }
export async function fetchGoalTypes(): Promise<GoalTypeList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/goal-types"); return parseWithFallback(raw, goalTypeListSchema, EMPTY_GOAL_TYPES, { endpoint: "fetchGoalTypes" }); }
export async function createGoalType(input: GoalTypeInput): Promise<GoalType | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/goal-types", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, goalTypeSchema, null, { endpoint: "createGoalType" }); }
export async function updateGoalType(id: string, input: GoalTypeInput): Promise<GoalType | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/goal-types/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, goalTypeSchema, null, { endpoint: "updateGoalType" }); }
export async function deleteGoalType(id: string): Promise<void> { await api.cerebroRequest<void>(`/api/cerebro/goal-types/${id}`, { method: "DELETE" }); }
export async function fetchStrategy(): Promise<StrategyList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/strategy-items"); return parseWithFallback(raw, strategyListSchema, EMPTY_STRATEGY, { endpoint: "fetchStrategy" }); }
export async function fetchStrategyHistory(): Promise<StrategyHistoryList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/strategy-history"); return parseWithFallback(raw, strategyHistoryListSchema, EMPTY_STRATEGY_HISTORY, { endpoint: "fetchStrategyHistory" }); }
export async function createStrategyItem(input: StrategyItemInput): Promise<StrategyItem | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/strategy-items", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, strategyItemSchema, null, { endpoint: "createStrategyItem" }); }
export async function updateStrategyItem(id: string, input: StrategyItemInput): Promise<StrategyItem | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/strategy-items/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, strategyItemSchema, null, { endpoint: "updateStrategyItem" }); }
export async function fetchRocks(): Promise<RocksList> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/rocks"); return parseWithFallback(raw, rocksListSchema, EMPTY_ROCKS, { endpoint: "fetchRocks" }); }
export async function createRock(input: RockInput): Promise<Rock | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/rocks", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, rockSchema, null, { endpoint: "createRock" }); }
export async function updateRock(id: string, input: RockInput): Promise<Rock | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/rocks/${id}`, { method: "PUT", body: JSON.stringify(input) }); return parseWithFallback(raw, rockSchema, null, { endpoint: "updateRock" }); }
export async function addRockCheckIn(id: string, input: RockCheckInInput): Promise<RockCheckIn | null> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/rocks/${id}/check-ins`, { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, rockCheckInSchema, null, { endpoint: "addRockCheckIn" }); }
export async function fetchConnections(objectType: string, objectId: string): Promise<ObjectConnectionList> { const raw = await api.cerebroRequest<unknown>(`/api/cerebro/object-connections?object_type=${encodeURIComponent(objectType)}&object_id=${encodeURIComponent(objectId)}`); return parseWithFallback(raw, objectConnectionListSchema, EMPTY_CONNECTIONS, { endpoint: "fetchOperatingSystemConnections" }); }
export async function createConnection(input: ObjectConnectionInput): Promise<ObjectConnection | null> { const raw = await api.cerebroRequest<unknown>("/api/cerebro/object-connections", { method: "POST", body: JSON.stringify(input) }); return parseWithFallback(raw, objectConnectionSchema, null, { endpoint: "createOperatingSystemConnection" }); }
