import { queryOptions, useMutation, useQueryClient, type QueryClient } from "@tanstack/react-query";
import { addRockCheckIn, createConnection, createGoalType, createOrgChartSeat, createPeriod, createRock, createStrategyItem, createVisionPlanItem, createVisionPlanPage, createVisionPlanSection, deleteConnection, deleteGoalType, deleteOrgChartSeat, deletePeriod, deleteVisionPlanItem, deleteVisionPlanPage, deleteVisionPlanSection, fetchConnections, fetchElements, fetchGoalTypes, fetchMeeting, fetchOrgChart, fetchPeriods, fetchRocks, fetchSettings, fetchStrategy, fetchStrategyHistory, fetchVisionPlan, updateElement, updateGoalType, updateMeeting, updateOrgChartSeat, updatePeriod, updateRock, updateSettings, updateStrategyItem, updateVisionPlanItem, updateVisionPlanPage, updateVisionPlanSection } from "./api";
import type { GoalTypeInput, MeetingConfigInput, ObjectConnectionInput, OperatingPeriodInput, OrgChartSeatInput, RockCheckInInput, RockInput, StrategyItemInput, Terminology, VisionPlanItemInput, VisionPlanPageInput, VisionPlanSectionInput } from "./types";

export const operatingSystemKeys = {
  all: (wsId: string) => ["cerebro", "operating-system", wsId] as const,
  settings: (wsId: string) => [...operatingSystemKeys.all(wsId), "settings"] as const,
  periods: (wsId: string) => [...operatingSystemKeys.all(wsId), "periods"] as const,
  strategy: (wsId: string) => [...operatingSystemKeys.all(wsId), "strategy"] as const,
  strategyHistory: (wsId: string) => [...operatingSystemKeys.all(wsId), "strategy-history"] as const,
  rocks: (wsId: string) => [...operatingSystemKeys.all(wsId), "rocks"] as const,
  elements: (wsId: string) => [...operatingSystemKeys.all(wsId), "elements"] as const,
  goalTypes: (wsId: string) => [...operatingSystemKeys.all(wsId), "goal-types"] as const,
  connections: (wsId: string, objectType: string, objectId: string) => [...operatingSystemKeys.all(wsId), "connections", objectType, objectId] as const,
  visionPlan: (wsId: string) => [...operatingSystemKeys.all(wsId), "vision-plan"] as const,
  meeting: (wsId: string) => [...operatingSystemKeys.all(wsId), "meeting"] as const,
  orgChart: (wsId: string) => [...operatingSystemKeys.all(wsId), "org-chart"] as const,
};
export const settingsOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.settings(wsId), queryFn: fetchSettings, enabled: !!wsId });
export const periodsOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.periods(wsId), queryFn: fetchPeriods, enabled: !!wsId });
export const strategyOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.strategy(wsId), queryFn: fetchStrategy, enabled: !!wsId });
export const strategyHistoryOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.strategyHistory(wsId), queryFn: fetchStrategyHistory, enabled: !!wsId });
export const rocksOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.rocks(wsId), queryFn: fetchRocks, enabled: !!wsId });
export const elementsOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.elements(wsId), queryFn: fetchElements, enabled: !!wsId });
export const goalTypesOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.goalTypes(wsId), queryFn: fetchGoalTypes, enabled: !!wsId });
export const connectionsOptions = (wsId: string, objectType: string, objectId: string) => queryOptions({ queryKey: operatingSystemKeys.connections(wsId, objectType, objectId), queryFn: () => fetchConnections(objectType, objectId), enabled: !!wsId && !!objectType && !!objectId });
export const visionPlanOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.visionPlan(wsId), queryFn: fetchVisionPlan, enabled: !!wsId });
export const meetingOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.meeting(wsId), queryFn: fetchMeeting, enabled: !!wsId });
export const orgChartOptions = (wsId: string) => queryOptions({ queryKey: operatingSystemKeys.orgChart(wsId), queryFn: fetchOrgChart, enabled: !!wsId });
export function useUpdateMeeting(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: MeetingConfigInput) => updateMeeting(input), onSettled: () => qc.invalidateQueries({ queryKey: operatingSystemKeys.meeting(wsId) }) }); }
export function useCreateOrgChartSeat(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: OrgChartSeatInput) => createOrgChartSeat(input), onSettled: () => qc.invalidateQueries({ queryKey: operatingSystemKeys.orgChart(wsId) }) }); }
export function useUpdateOrgChartSeat(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: OrgChartSeatInput }) => updateOrgChartSeat(id, input), onSettled: () => qc.invalidateQueries({ queryKey: operatingSystemKeys.orgChart(wsId) }) }); }
export function useDeleteOrgChartSeat(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: deleteOrgChartSeat, onSettled: () => qc.invalidateQueries({ queryKey: operatingSystemKeys.orgChart(wsId) }) }); }
export function useCreateStrategyItem(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: StrategyItemInput) => createStrategyItem(input), onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.strategy(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.strategyHistory(wsId) }); } }) }
export function useUpdateStrategyItem(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: StrategyItemInput }) => updateStrategyItem(id, input), onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.strategy(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.strategyHistory(wsId) }); } }) }
export function useSaveRock(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id?: string; input: RockInput }) => id ? updateRock(id, input) : createRock(input), onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.rocks(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.strategy(wsId) }); } }); }
export function useRockCheckIn(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: RockCheckInInput }) => addRockCheckIn(id, input), onSettled: () => qc.invalidateQueries({ queryKey: operatingSystemKeys.rocks(wsId) }) }); }
export function useUpdateSettings(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: Terminology) => updateSettings(input), onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.settings(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.strategy(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.rocks(wsId) }); } }); }
export function useUpdateElement(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ key, enabled }: { key: string; enabled: boolean }) => updateElement(key, enabled), onSettled: () => qc.invalidateQueries({ queryKey: operatingSystemKeys.elements(wsId) }) }); }
export function useSaveGoalType(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id?: string; input: GoalTypeInput }) => id ? updateGoalType(id, input) : createGoalType(input), onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.goalTypes(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.rocks(wsId) }); } }); }
export function useDeleteGoalType(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (id: string) => deleteGoalType(id), onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.goalTypes(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.rocks(wsId) }); } }); }
export function useSavePeriod(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id?: string; input: OperatingPeriodInput }) => id ? updatePeriod(id, input) : createPeriod(input), onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.periods(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.rocks(wsId) }); } }); }
export function useDeletePeriod(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (id: string) => deletePeriod(id), onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.periods(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.rocks(wsId) }); } }); }
export function useCreateConnection(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: ObjectConnectionInput) => createConnection(input), onSettled: (_data, _error, input) => { qc.invalidateQueries({ queryKey: operatingSystemKeys.connections(wsId, input.source_type, input.source_id) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.strategy(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.visionPlan(wsId) }); } }); }
const invalidateVisionPlan = (qc: QueryClient, wsId: string) => { qc.invalidateQueries({ queryKey: operatingSystemKeys.visionPlan(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.strategy(wsId) }); };
export function useCreateVisionPlanPage(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: VisionPlanPageInput) => createVisionPlanPage(input), onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useUpdateVisionPlanPage(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: VisionPlanPageInput }) => updateVisionPlanPage(id, input), onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useDeleteVisionPlanPage(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: deleteVisionPlanPage, onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useCreateVisionPlanSection(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: VisionPlanSectionInput) => createVisionPlanSection(input), onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useUpdateVisionPlanSection(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: VisionPlanSectionInput }) => updateVisionPlanSection(id, input), onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useDeleteVisionPlanSection(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: deleteVisionPlanSection, onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useCreateVisionPlanItem(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: VisionPlanItemInput) => createVisionPlanItem(input), onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useUpdateVisionPlanItem(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ id, input }: { id: string; input: VisionPlanItemInput }) => updateVisionPlanItem(id, input), onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useDeleteVisionPlanItem(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: deleteVisionPlanItem, onSettled: () => invalidateVisionPlan(qc, wsId) }); }
export function useDeleteConnection(wsId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: deleteConnection, onSettled: () => { qc.invalidateQueries({ queryKey: operatingSystemKeys.visionPlan(wsId) }); qc.invalidateQueries({ queryKey: operatingSystemKeys.rocks(wsId) }); } }); }
