apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentfarm-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secretstore-aws-ssm
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /agentfarm/tools
        name:
          regexp: "(?i)^/agentfarm/tools/[^/]+$"
      rewrite:
        - regexp:
            source: "(?i)^/agentfarm/tools/(.*)"
            target: "$1"
