apiVersion: v1
kind: Secret
metadata:
  name: multica-bot-secrets
  namespace: multica-bot
type: Opaque
stringData:
  JWT_SECRET: "dd6514cdcbcd6a427a6e96c7ed5ea971336fa74697224c0f008f8257fc1a6358"
  POSTGRES_PASSWORD: "multica_bot_2026"
  RESEND_API_KEY: ""
  GOOGLE_CLIENT_ID: "28093689205-633mpk0mooj2nvu4ougg6l3978rh8iil.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  DINGTALK_CLIENT_ID: "dingfibftxe2ayknnslf"
  DINGTALK_CLIENT_SECRET: "Tm9DzOZa3naJMkIabKR8CrGGjihyqedD4b_yxUqHb8G9r1LqAQO8QSVMWTd-W_9-"
  DINGTALK_ROBOT_CODE: "dingfibftxe2ayknnslf"
  DATABASE_URL: "postgres://multica:multica_bot_2026@postgres:5432/multica_bot?sslmode=disable"
