/**
 * One-shot generator for components/ui/ionicon-glyphs.ts.
 *
 * Emits the glyph name -> unicode code point map for the Ionicons set this
 * app renders, sourced from react-native-vector-icons' glyphmap (the same
 * mapping @expo/vector-icons uses on iOS). The Ionicons.ttf itself is
 * vendored at harmony/entry/src/main/resources/rawfile/ and registered
 * under the "Ionicons" font family in Index.ets. Run from the repo root:
 *
 *   node apps/mobile-harmony/scripts/generate-icons.mjs
 *
 * Requires network access (npm-packs react-native-vector-icons). The
 * generated file is committed; rerun only when adding names to ICONS.
 */
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import os from "node:os";

const ICONS = [
  // Tab bar + More menu (SF-symbol equivalents: tray, checklist,
  // bubble.left, ellipsis, pin, list.bullet, square.stack, chevron.right)
  "file-tray",
  "file-tray-outline",
  "checkbox",
  "checkbox-outline",
  "chatbubble",
  "chatbubble-outline",
  "chatbubble-ellipses",
  "chatbubble-ellipses-outline",
  "ellipsis-horizontal",
  "pin",
  "pin-outline",
  "list",
  "list-outline",
  "albums",
  "albums-outline",
  "chevron-forward",
  "chevron-back",
  "chevron-down",
  // In-app icons (mirrors the Ionicons names used across apps/mobile)
  "search",
  "add",
  "add-circle-outline",
  "close",
  "checkmark",
  "checkmark-circle",
  "checkmark-circle-outline",
  "calendar-clear-outline",
  "calendar-outline",
  "attach-outline",
  "at",
  "at-outline",
  "image-outline",
  "document-outline",
  "document-attach-outline",
  "folder-open-outline",
  "folder-outline",
  "git-branch-outline",
  "server-outline",
  "code-slash-outline",
  "cloud-offline-outline",
  "mail-open-outline",
  "mail-outline",
  "archive-outline",
  "alert-circle",
  "alert-circle-outline",
  "close-circle",
  "close-circle-outline",
  "cog-outline",
  "people",
  "people-outline",
  "person",
  "person-outline",
  "person-circle-outline",
  "return-up-back",
  "time-outline",
  "options-outline",
  "download-outline",
  "arrow-up",
  "arrow-down",
  "arrow-redo",
  "arrow-undo",
  "bulb-outline",
  "chatbox-outline",
  "happy-outline",
  "square-outline",
  "square",
  "pulse-outline",
  "play-outline",
  "sparkles-outline",
  "warning-outline",
  "information-circle-outline",
  "refresh",
  "lock-closed-outline",
  "log-out-outline",
  "camera-outline",
  "trash-outline",
  "create-outline",
  "text-outline",
  "flag-outline",
  "book-outline",
  "link-outline",
  "logo-github",
  "open-outline",
  "copy-outline",
  "share-outline",
];

const outRel = "components/ui/ionicon-glyphs.ts";
const tmp = path.join(os.tmpdir(), `ionicons-gen-${process.pid}`);
mkdirSync(tmp, { recursive: true });

execSync(`npm pack --silent react-native-vector-icons@10`, { cwd: tmp, stdio: "pipe" });
execSync(`tar -xzf react-native-vector-icons-*.tgz`, { cwd: tmp, stdio: "ignore" });

const glyphmap = JSON.parse(
  readFileSync(path.join(tmp, "package", "glyphmaps", "Ionicons.json"), "utf8"),
);

const entries = [];
const missing = [];
for (const name of ICONS) {
  const codePoint = glyphmap[name];
  if (typeof codePoint === "number") {
    entries.push(`  "${name}": ${codePoint},`);
  } else {
    missing.push(name);
  }
}
if (missing.length > 0) {
  console.error(`MISSING GLYPHS (not in Ionicons.json): ${missing.join(", ")}`);
}

const banner = `/**
 * Generated by scripts/generate-icons.mjs — DO NOT EDIT BY HAND.
 * Source: react-native-vector-icons@10 glyphmaps/Ionicons.json (Ionicons 7
 * glyph name -> unicode code point), rendered as font text by
 * components/ui/icon.tsx against the bundled Ionicons.ttf. Regenerate:
 * node scripts/generate-icons.mjs
 */
export const IONICON_GLYPHS: Record<string, number> = {
`;

mkdirSync(path.dirname(path.join(process.cwd(), "apps/mobile-harmony", outRel)), {
  recursive: true,
});
writeFileSync(
  path.join(process.cwd(), "apps/mobile-harmony", outRel),
  banner + entries.join("\n") + "\n};\n",
);
console.log(
  `wrote ${outRel}: ${ICONS.length - missing.length}/${ICONS.length} glyphs`,
);
rmSync(tmp, { recursive: true, force: true });
