package execenv

import (
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strings"
)

const agentSecurityBundleEnv = "MULTICA_AGENT_SECURITY_BUNDLE"

type agentSecurityBundle struct {
	SchemaVersion int            `json:"schema_version"`
	Claude        map[string]any `json:"claude"`
	CodexTOML     string         `json:"codex_toml"`
}

func loadAgentSecurityBundle() (*agentSecurityBundle, error) {
	path := strings.TrimSpace(os.Getenv(agentSecurityBundleEnv))
	if path == "" {
		return nil, nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", agentSecurityBundleEnv, err)
	}
	var bundle agentSecurityBundle
	if err := json.Unmarshal(data, &bundle); err != nil {
		return nil, fmt.Errorf("parse %s: %w", agentSecurityBundleEnv, err)
	}
	if bundle.SchemaVersion != 1 || bundle.CodexTOML == "" || bundle.Claude == nil {
		return nil, fmt.Errorf("%s has unsupported or incomplete schema", agentSecurityBundleEnv)
	}
	return &bundle, nil
}

var multicaSandboxBlockRE = regexp.MustCompile(`(?ms)^# BEGIN multica-managed \(do not edit; regenerated by daemon\)\n.*?^# END multica-managed\n?`)

func applyCodexAgentSecurityBundle(configPath string, bundle *agentSecurityBundle) error {
	data, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	text := multicaSandboxBlockRE.ReplaceAllString(string(data), "")
	begin := "# BEGIN myai-managed tcc-policy (do not edit)"
	end := "# END myai-managed tcc-policy"
	if start := strings.Index(text, begin); start >= 0 {
		if stop := strings.Index(text[start:], end); stop >= 0 {
			stop = start + stop + len(end)
			if stop < len(text) && text[stop] == '\n' {
				stop++
			}
			text = text[:start] + text[stop:]
		}
	}
	return os.WriteFile(configPath, []byte(bundle.CodexTOML+"\n"+strings.TrimLeft(text, "\n")), 0o600)
}
