package execenv

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAgentSecurityBundleAppliesToCodexAndClaude(t *testing.T) {
	dir := t.TempDir()
	bundle := filepath.Join(dir, "bundle.json")
	body := `{"schema_version":1,"claude":{"sandbox":{"enabled":true},"permissions":{"deny":["Read(/private/**)"]}},"codex_toml":"# BEGIN myai-managed tcc-policy (do not edit)\ndefault_permissions = \"safe\"\n[permissions.safe.filesystem]\n\":root\" = \"write\"\n\"/private\" = \"deny\"\n# END myai-managed tcc-policy\n"}`
	if err := os.WriteFile(bundle, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	t.Setenv(agentSecurityBundleEnv, bundle)
	config := filepath.Join(dir, "config.toml")
	if err := os.WriteFile(config, []byte("# BEGIN multica-managed (do not edit; regenerated by daemon)\nsandbox_mode = \"danger-full-access\"\n# END multica-managed\nmodel = \"x\"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	b, err := loadAgentSecurityBundle()
	if err != nil {
		t.Fatal(err)
	}
	if err := applyCodexAgentSecurityBundle(config, b); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(config)
	if strings.Contains(string(got), "danger-full-access") || !strings.Contains(string(got), `"/private" = "deny"`) || !strings.Contains(string(got), `model = "x"`) {
		t.Fatalf("unexpected config: %s", got)
	}
	settings, err := prepareClaudeSkillSettings(dir, nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	got, _ = os.ReadFile(settings)
	if !strings.Contains(string(got), `Read(/private/**)`) || !strings.Contains(string(got), `"enabled":true`) {
		t.Fatalf("unexpected settings: %s", got)
	}
}
