package execenv

import (
	"fmt"
	"log/slog"
	"os"
	"regexp"
	"strings"
)

// Codex filters environment variables before running shell tool subprocesses.
// Its default secret guard drops names containing TOKEN, so a daemon-spawned
// Codex process can have MULTICA_TOKEN while `multica issue ...` inside a shell
// tool does not. Pin a narrow task environment for Multica-managed Codex homes:
// enough shell basics for commands to run, plus the daemon-provided MULTICA_*
// task context.
const (
	multicaShellEnvBeginMarker = "# BEGIN multica-managed shell-environment (do not edit; regenerated by daemon)"
	multicaShellEnvEndMarker   = "# END multica-managed shell-environment"
)

var shellEnvBlockRe = regexp.MustCompile(
	`(?ms)^` + regexp.QuoteMeta(multicaShellEnvBeginMarker) +
		`.*?^` + regexp.QuoteMeta(multicaShellEnvEndMarker) + `\n*`)

var (
	rootShellEnvPolicyTableHeaderRe = regexp.MustCompile(`^\s*\[\s*shell_environment_policy\s*\]\s*(?:#.*)?$`)
	rootDottedShellEnvPolicyRe      = regexp.MustCompile(`^\s*shell_environment_policy\s*\.\s*(inherit|ignore_default_excludes|include_only|exclude|set)\s*=`)
	shellEnvPolicyTableDirectiveRe  = regexp.MustCompile(`^\s*(inherit|ignore_default_excludes|include_only|exclude|set)\s*=`)
)

func renderMulticaShellEnvBlock(inShellEnvPolicyTable bool) string {
	var b strings.Builder
	b.WriteString(multicaShellEnvBeginMarker)
	b.WriteString("\n")
	if inShellEnvPolicyTable {
		b.WriteString("inherit = \"all\"\n")
		b.WriteString("ignore_default_excludes = true\n")
		b.WriteString("include_only = [\"PATH\", \"HOME\", \"USER\", \"SHELL\", \"TERM\", \"TMPDIR\", \"TMP\", \"TEMP\", \"MULTICA_*\"]\n")
	} else {
		b.WriteString("shell_environment_policy.inherit = \"all\"\n")
		b.WriteString("shell_environment_policy.ignore_default_excludes = true\n")
		b.WriteString("shell_environment_policy.include_only = [\"PATH\", \"HOME\", \"USER\", \"SHELL\", \"TERM\", \"TMPDIR\", \"TMP\", \"TEMP\", \"MULTICA_*\"]\n")
	}
	b.WriteString(multicaShellEnvEndMarker)
	b.WriteString("\n")
	return b.String()
}

func stripUserShellEnvPolicyDirectives(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := "" // empty = TOML root
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if rootShellEnvPolicyTableHeaderRe.MatchString(line) {
			currentTable = "[shell_environment_policy]"
			out = append(out, line)
			continue
		}
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		switch currentTable {
		case "":
			if rootDottedShellEnvPolicyRe.MatchString(trimmed) {
				continue
			}
		case "[shell_environment_policy]":
			if shellEnvPolicyTableDirectiveRe.MatchString(trimmed) {
				continue
			}
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func hasRootShellEnvPolicyTable(content string) bool {
	for _, line := range strings.Split(content, "\n") {
		if rootShellEnvPolicyTableHeaderRe.MatchString(line) {
			return true
		}
	}
	return false
}

func injectManagedBlockIntoShellEnvPolicyTable(content string) string {
	block := renderMulticaShellEnvBlock(true)
	blockLines := strings.Split(strings.TrimRight(block, "\n"), "\n")
	lines := strings.Split(content, "\n")
	for i, line := range lines {
		if !rootShellEnvPolicyTableHeaderRe.MatchString(line) {
			continue
		}
		out := make([]string, 0, len(lines)+len(blockLines))
		out = append(out, lines[:i+1]...)
		out = append(out, blockLines...)
		out = append(out, lines[i+1:]...)
		return strings.Join(out, "\n")
	}
	return content
}

func ensureCodexShellEnvPolicyConfig(configPath string, logger *slog.Logger) error {
	data, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read config.toml: %w", err)
	}
	existing := shellEnvBlockRe.ReplaceAllString(string(data), "")
	existing = stripUserShellEnvPolicyDirectives(existing)

	var updated string
	if hasRootShellEnvPolicyTable(existing) {
		updated = injectManagedBlockIntoShellEnvPolicyTable(existing)
	} else {
		existing = strings.TrimLeft(existing, "\n")
		block := renderMulticaShellEnvBlock(false)
		if existing == "" {
			updated = block
		} else {
			updated = block + "\n" + existing
		}
	}

	if updated == string(data) {
		return nil
	}
	if err := os.WriteFile(configPath, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write config.toml: %w", err)
	}
	if logger != nil {
		logger.Debug("codex shell environment: wrote managed shell_environment_policy",
			"config_path", configPath,
		)
	}
	return nil
}
