package execenv

import (
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const (
	multicaCodexRuntimeConfigBeginMarker = "# BEGIN multica-managed codex-runtime-config (do not edit; regenerated by daemon)"
	multicaCodexRuntimeConfigEndMarker   = "# END multica-managed codex-runtime-config"
)

var (
	codexRuntimeConfigBlockRe = regexp.MustCompile(
		`(?ms)^` + regexp.QuoteMeta(multicaCodexRuntimeConfigBeginMarker) +
			`.*?^` + regexp.QuoteMeta(multicaCodexRuntimeConfigEndMarker) + `\n*`)
	rootModelReasoningEffortRe = regexp.MustCompile(`^\s*model_reasoning_effort\s*=`)
)

func codexReasoningEffortFromRuntimeConfig(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}
	var cfg map[string]any
	if err := json.Unmarshal(raw, &cfg); err != nil {
		return ""
	}
	value, ok := cfg["model_reasoning_effort"].(string)
	if !ok {
		return ""
	}
	return strings.TrimSpace(value)
}

func renderCodexRuntimeConfigBlock(modelReasoningEffort string) string {
	var b strings.Builder
	b.WriteString(multicaCodexRuntimeConfigBeginMarker)
	b.WriteString("\n")
	fmt.Fprintf(&b, "model_reasoning_effort = %s\n", strconv.Quote(modelReasoningEffort))
	b.WriteString(multicaCodexRuntimeConfigEndMarker)
	b.WriteString("\n")
	return b.String()
}

func stripRootModelReasoningEffort(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	currentTable := ""
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "[") {
			currentTable = trimmed
			out = append(out, line)
			continue
		}
		if currentTable == "" && rootModelReasoningEffortRe.MatchString(line) {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

func upsertCodexRuntimeConfigBlock(content, modelReasoningEffort string) string {
	content = codexRuntimeConfigBlockRe.ReplaceAllString(content, "")
	if modelReasoningEffort == "" {
		return strings.TrimLeft(content, "\n")
	}
	content = stripRootModelReasoningEffort(content)
	content = strings.TrimLeft(content, "\n")
	block := renderCodexRuntimeConfigBlock(modelReasoningEffort)
	if content == "" {
		return block
	}
	return block + "\n" + content
}

func ensureCodexRuntimeConfig(configPath string, runtimeConfig json.RawMessage) error {
	data, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read config.toml: %w", err)
	}

	updated := upsertCodexRuntimeConfigBlock(string(data), codexReasoningEffortFromRuntimeConfig(runtimeConfig))
	if updated == string(data) {
		return nil
	}
	if err := os.WriteFile(configPath, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("write config.toml: %w", err)
	}
	return nil
}
