import type { GraphEdge, GraphNode, GraphNodeType } from "./types";

export const HIDDEN_GRAPH_NODE_TYPES = new Set<GraphNodeType>(["code_file"]);

const DOMAIN_META = [
  { id: "domestic-influencer", label: "国内达人", color: "bg-blue-500" },
  { id: "overseas-influencer", label: "海外达人", color: "bg-sky-500" },
  { id: "domestic-incentive", label: "国内激励", color: "bg-amber-500" },
  { id: "overseas-incentive", label: "海外激励", color: "bg-orange-500" },
  { id: "domestic-anchor", label: "国内锚点", color: "bg-emerald-500" },
  { id: "overseas-anchor", label: "海外锚点", color: "bg-violet-500" },
  { id: "horizontal-assets", label: "横向知识", color: "bg-slate-500" },
] as const;

export const NODE_TYPE_LABELS = {
  domain: "业务域",
  repo: "代码仓库",
  frontend_app: "前端应用 / 目录",
  code_file: "代码文件",
  service: "服务 / PSM",
  markdown: "知识卡片",
  prd: "需求背景",
  business_insight: "业务结论",
  alert_sop: "告警 / SOP",
  api_contract: "API / 契约",
  term: "专业名词",
  flow: "链路流程",
  owner: "对接人",
  tracking: "埋点数据",
  data_asset: "横向资产",
  alert_policy: "告警规范",
  config: "配置 / 灰度",
} as const;

export const CONFIDENCE_LABELS = {
  verified: "已验证",
  high: "高可信",
  medium: "中可信",
  inferred: "推断",
  conflicted: "冲突",
} as const;

export const NODE_TYPE_OPTIONS = [
  "代码仓库",
  "服务 / PSM",
  "知识卡片",
  "需求背景",
  "业务结论",
  "告警 / SOP",
  "告警规范",
  "API / 契约",
  "专业名词",
  "链路流程",
  "对接人",
  "埋点数据",
  "横向资产",
  "配置 / 灰度",
] as const;

export const GRAPH_NODES: GraphNode[] = [
  {
    id: "wiki/product/domestic-influencer/README.md",
    label: "wiki/product/domestic-influencer/README.md",
    displayName: "国内 Pick 领域总览",
    type: "markdown",
    scene: ["总览", "AI 编码", "业务问答"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "wiki/product/domestic-influencer/README.md",
    summary: "国内 Pick 领域总览，定义达人入驻与审核、投稿与链接校验、归因、结算、代理账单审核与打款。",
    details: [
      {
        title: "领域定义",
        items: ["达人入驻与审核", "任务投稿与链接校验", "口令 / 链接承接与归因", "投稿收益结算", "代理账单审核与打款"],
      },
      {
        title: "服务版图",
        items: ["jianying_campaign：C 端 portal、auth、task、token、submit_post、profit、分享回流", "jianying_campaign_faas：token 归因、投稿结算、定时刷新、MQ/EventBus 消费", "jianying_ug_backend：达人审核、投稿审核、代理投稿列表、账单审核", "jianying_ug_rpc：Pick 信息查询、推广链接生成、账单钱包打款"],
      },
      {
        title: "推荐阅读",
        items: ["先理解核心对象和关键状态", "再看投稿、归因、结算、账单的主链路", "最后对照前后端服务分工和已沉淀业务结论"],
      },
    ],
    related: ["wiki/product/domestic-influencer/repositories.md", "wiki/product/domestic-influencer/flows.md", "wiki/product/domestic-influencer/rules.md"],
    x: 600,
    y: 380,
    size: "lg",
  },
  {
    id: "domestic-influencer",
    label: "domestic-influencer",
    displayName: "国内达人",
    type: "domain",
    scene: ["AI 编码", "业务问答", "总览"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "wiki/product/domestic-influencer/",
    summary: "国内达人 Pick 业务域，覆盖报名、审核、投稿、归因、结算和运营后台。",
    related: ["growth/seeyou", "wiki/product/domestic-influencer/repositories.md", "AuditPlatformView"],
    x: 390,
    y: 240,
    size: "lg",
  },
  {
    id: "overseas-anchor",
    label: "overseas-anchor",
    displayName: "海外锚点",
    type: "domain",
    scene: ["服务架构", "业务问答", "总览"],
    domain: "overseas-anchor",
    confidence: "high",
    path: "wiki/product/overseas-anchor/",
    summary: "海外锚点业务域，覆盖 TikTok / CapCut anchor landing、配置和排障 SOP。",
    related: ["growth/ug-video-fe-os", "capcut_anchor_landing_page"],
    x: 760,
    y: 150,
    size: "lg",
  },
  {
    id: "domestic-incentive",
    label: "domestic-incentive",
    displayName: "国内激励",
    type: "domain",
    scene: ["业务问答", "总览"],
    domain: "domestic-incentive",
    confidence: "medium",
    path: "wiki/product/domestic-incentive/",
    summary: "国内激励与裂变业务域，覆盖任务奖励、邀请、红包和防薅规则。",
    related: ["jianying_campaign", "jianying_ug_rpc"],
    x: 155,
    y: 480,
    size: "md",
  },
  {
    id: "growth/seeyou",
    label: "growth/seeyou",
    type: "repo",
    scene: ["AI 编码", "服务架构", "总览"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "code.byted.org/growth/seeyou",
    summary: "国内 Seeyou 前端/Node monorepo，覆盖 seeyou-social-cn、Pick inhouse/agent、国内 AnchorPlatform 和审核后台。",
    related: ["apps/seeyou-social-cn", "domestic-influencer"],
    x: 260,
    y: 265,
    size: "md",
  },
  {
    id: "ies/capcut_web_ug",
    label: "ies/capcut_web_ug",
    type: "repo",
    scene: ["AI 编码", "业务问答"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "code.byted.org/ies/capcut_web_ug",
    summary: "国内 Web UG 大仓，承载 Domestic PICK2.0、活动页、分享中间页和端能力跳转。",
    x: 90,
    y: 310,
    size: "md",
  },
  {
    id: "ies/capcut_web_ug_os",
    label: "ies/capcut_web_ug_os",
    type: "repo",
    scene: ["AI 编码", "业务问答"],
    domain: "overseas-influencer",
    confidence: "verified",
    path: "code.byted.org/ies/capcut_web_ug_os",
    summary: "海外 Web UG 大仓，承载 Overseas Pick、Dreamina 分享回流、share middle/common SSR 等。",
    x: 970,
    y: 290,
    size: "md",
  },
  {
    id: "growth/ug-video-fe-os",
    label: "growth/ug-video-fe-os",
    type: "repo",
    scene: ["AI 编码", "服务架构"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/ug-video-fe-os",
    summary: "海外 UG Lynx 前端 monorepo，承载 CapCut/TikTok/Hypic landing 与 anchor landing。",
    x: 780,
    y: 300,
    size: "md",
  },
  {
    id: "growth/capcut_ug_http",
    label: "growth/capcut_ug_http",
    type: "repo",
    scene: ["服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/capcut_ug_http",
    summary: "海外 CapCut 前台 HTTP 聚合服务，负责 landing page、thirdparty share、metadata 和 anchor info。",
    x: 860,
    y: 430,
    size: "md",
  },
  {
    id: "apps/seeyou-social-cn",
    label: "apps/seeyou-social-cn",
    type: "frontend_app",
    scene: ["AI 编码"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "growth/seeyou/apps/seeyou-social-cn",
    repo: "growth/seeyou",
    summary: "国内社媒增长后台应用，承载 bgent、Pick inhouse/agent 和国内锚点后台入口。",
    related: ["bgent", "growth/seeyou"],
    x: 300,
    y: 365,
    size: "md",
  },
  {
    id: "bgent",
    label: "bgent",
    type: "frontend_app",
    scene: ["AI 编码"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "apps/seeyou-social-cn/src/routes/bgent/",
    repo: "growth/seeyou",
    app: "apps/seeyou-social-cn",
    summary: "bgent 审核与增长运营相关路由目录。",
    related: ["AuditPlatformView", "routes.tsx"],
    x: 445,
    y: 390,
    size: "md",
  },
  {
    id: "AuditPlatformView",
    label: "AuditPlatformView",
    type: "frontend_app",
    scene: ["AI 编码"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "growth/seeyou/apps/seeyou-social-cn/src/routes/bgent/views/AuditPlatformView/",
    repo: "growth/seeyou",
    app: "apps/seeyou-social-cn",
    updated: "2026-06-09",
    summary: "bgent 审核平台页面，包含视频与达人两个审核 tab。达人审核对应 kol 类型，并映射到 bgent 的 influencer_audit 场景。",
    evidence: [
      { title: "routes.tsx", description: "RouteKey.AUDIT_PLATFORM -> AuditPlatformView" },
      { title: "AuditPlatformView.tsx", description: "tabs: video / kol" },
      { title: "api.ts", description: "kol -> influencer_audit" },
      { title: "bgentClient.ts", description: "/bgent/audit_influencer_review/result" },
    ],
    related: ["bgent", "api.ts", "bgentClient.ts", "influencer_audit", "domestic-influencer"],
    x: 565,
    y: 330,
    size: "lg",
  },
  {
    id: "routes.tsx",
    label: "routes.tsx",
    type: "code_file",
    scene: ["AI 编码"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "apps/seeyou-social-cn/src/routes/bgent/routes.tsx",
    repo: "growth/seeyou",
    app: "apps/seeyou-social-cn",
    summary: "bgent 路由注册文件，将 AUDIT_PLATFORM 路由映射到 AuditPlatformView。",
    related: ["AuditPlatformView"],
    x: 590,
    y: 205,
    size: "sm",
  },
  {
    id: "api.ts",
    label: "api.ts",
    type: "code_file",
    scene: ["AI 编码"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "apps/seeyou-social-cn/src/routes/bgent/views/AuditPlatformView/api.ts",
    repo: "growth/seeyou",
    app: "apps/seeyou-social-cn",
    summary: "AuditPlatformView 的接口适配层，包含 kol 到 influencer_audit 的映射。",
    related: ["influencer_audit", "bgentClient.ts"],
    x: 625,
    y: 455,
    size: "sm",
  },
  {
    id: "bgentClient.ts",
    label: "bgentClient.ts",
    type: "code_file",
    scene: ["AI 编码"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "apps/seeyou-social-cn/src/routes/bgent/api/bgentClient.ts",
    repo: "growth/seeyou",
    app: "apps/seeyou-social-cn",
    summary: "bgent API client，封装 audit_influencer_review 的 result、submit、retry、update 等调用。",
    related: ["audit_influencer_review/result", "audit_influencer_review/submit"],
    x: 715,
    y: 520,
    size: "sm",
  },
  {
    id: "capcut_anchor_landing_page",
    label: "capcut_anchor_landing_page",
    type: "frontend_app",
    scene: ["AI 编码", "服务架构"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "growth/ug-video-fe-os/apps/tiktok/capcut_anchor_landing_page",
    repo: "growth/ug-video-fe-os",
    summary: "TikTok CapCut 锚点 Lynx 页面，包含 landing、Dreamina landing 和 Pippit landing。",
    x: 720,
    y: 405,
    size: "md",
  },
  {
    id: "dreamina-activities/share",
    label: "dreamina-activities/share",
    type: "frontend_app",
    scene: ["业务问答", "AI 编码"],
    domain: "overseas-influencer",
    confidence: "verified",
    path: "ies/capcut_web_ug_os/apps/dreamina-activities/src/pages/share/",
    repo: "ies/capcut_web_ug_os",
    summary: "即梦海外分享回流页面目录。",
    x: 1030,
    y: 410,
    size: "md",
  },
  {
    id: "jianying_campaign",
    label: "jianying_campaign",
    type: "service",
    scene: ["SRE 排障", "服务架构"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "code.byted.org/growth/jianying_campaign",
    summary: "国内 C 端 Pick 入口、任务中心、投稿、收益查询和分享回流服务。",
    x: 165,
    y: 590,
    size: "md",
  },
  {
    id: "jianying_ug_rpc",
    label: "jianying_ug_rpc",
    type: "service",
    scene: ["服务架构"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "code.byted.org/luckycat/jianying_ug_rpc",
    summary: "公共 RPC、推广链接生成、资源位运行时构建和钱包打款服务。",
    x: 345,
    y: 600,
    size: "md",
  },
  {
    id: "capcut_ug_http",
    label: "capcut_ug_http",
    type: "service",
    scene: ["SRE 排障", "服务架构"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/capcut_ug_http",
    summary: "海外 CapCut 前台 HTTP 聚合服务。",
    x: 990,
    y: 560,
    size: "md",
  },
  {
    id: "cc_ug_proxy_api",
    label: "cc_ug_proxy_api",
    type: "service",
    scene: ["SRE 排障", "服务架构"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/cc_ug_proxy_api",
    summary: "海外 UG 前台数据代理服务，负责模板信息、搜索、资源位和 tool anchor 配置。",
    x: 1100,
    y: 500,
    size: "md",
  },
  {
    id: "manifest.yaml",
    label: "manifest.yaml",
    displayName: "业务学习入口",
    type: "markdown",
    scene: ["业务问答", "AI 编码", "总览"],
    confidence: "verified",
    path: "manifest.yaml",
    summary: "进入 UG 业务知识时的总入口，帮助用户先选业务域，再沿图谱理解术语、流程、服务、SOP 和数据资产。",
    details: [
      {
        title: "学习顺序",
        items: ["先选择知识域：国内达人、海外达人、国内激励、海外激励、国内锚点、海外锚点或横向知识", "再沿图谱展开术语、流程、核心服务、数据口径和 SOP", "需要定位代码时使用节点详情里的技术定位和相邻节点"],
      },
      {
        title: "当前默认模块",
        items: ["国内达人模块覆盖报名、审核、投稿、归因、收益结算和运营后台", "适合从业务模块入口直接学习核心概念和主链路"],
      },
    ],
    x: 245,
    y: 120,
    size: "sm",
  },
  {
    id: "wiki/registry/domains.yaml",
    label: "wiki/registry/domains.yaml",
    displayName: "业务模块清单",
    type: "markdown",
    scene: ["总览", "业务问答"],
    confidence: "verified",
    path: "wiki/registry/domains.yaml",
    summary: "UG 业务模块清单，把达人、激励、锚点按国内/海外拆成可学习、可排障、可定位代码的模块。",
    details: [
      {
        title: "模块划分",
        items: ["达人模块：Pick 投稿、审核、归因、结算", "激励模块：任务奖励、邀请裂变、Post Incentive", "锚点模块：锚点挂载、配置、展示和分享"],
      },
      {
        title: "每个模块应学习的内容",
        items: ["专业名词和核心对象", "用户旅程与链路流程", "核心仓库、服务和前端入口", "告警排查、数据口径、配置灰度和对接人"],
      },
    ],
    related: ["wiki/product/domestic-influencer/README.md"],
    x: 300,
    y: 360,
    size: "sm",
  },
  {
    id: "wiki/index.md",
    label: "wiki/index.md",
    displayName: "知识导航总览",
    type: "markdown",
    scene: ["业务问答", "总览"],
    confidence: "verified",
    path: "wiki/index.md",
    summary: "UG 业务知识导航，按学习、问答、代码定位、服务架构和线上排障组织知识入口。",
    details: [
      {
        title: "导航入口",
        items: ["AI 编码：从业务问题定位到前端入口、服务和接口契约", "SRE 排障：从告警现象定位服务、日志、指标、Trace、配置和近期变更", "业务问答：从术语、规则、数据口径和业务结论开始理解"],
      },
      {
        title: "结构化资产",
        items: ["业务模块资产", "核心仓库与 PSM 服务资产", "链路流程资产", "SOP 与告警规范资产", "API 契约和数据口径资产"],
      },
    ],
    x: 420,
    y: 105,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/glossary.md",
    label: "wiki/product/domestic-influencer/glossary.md",
    displayName: "术语表",
    type: "markdown",
    scene: ["业务问答"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "wiki/product/domestic-influencer/glossary.md",
    summary: "国内 Pick 的核心术语和业务口径。",
    x: 760,
    y: 150,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/journeys.md",
    label: "wiki/product/domestic-influencer/journeys.md",
    displayName: "用户旅程",
    type: "markdown",
    scene: ["业务问答"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "wiki/product/domestic-influencer/journeys.md",
    summary: "达人、代理和运营视角的国内 Pick 旅程。",
    x: 760,
    y: 220,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/entities.md",
    label: "wiki/product/domestic-influencer/entities.md",
    displayName: "核心对象",
    type: "markdown",
    scene: ["业务问答", "AI 编码"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "wiki/product/domestic-influencer/entities.md",
    summary: "Pick 用户、投稿、任务、账单、归因等核心实体。",
    details: [
      {
        title: "核心对象",
        items: ["PickUserAuditRecord：自营达人审核主表", "PickPostAuditRecord：自营投稿审核主表", "PostAttributionRecord：投稿维度归因聚合结果", "PickPostSettlementRecord：自营投稿收益结算记录", "PickPaymentBill：代理或自营账单主表"],
      },
      {
        title: "资源投放",
        items: ["TResourcePlanDraft / TResourcePlan：资源位投放计划草稿表与线上表", "TResourceItemRel：投放计划物料表", "PickTaskResource：资源投放体系中的 Pick 任务物料，不是独立任务表"],
      },
    ],
    x: 760,
    y: 290,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/rules.md",
    label: "wiki/product/domestic-influencer/rules.md",
    displayName: "业务规则",
    type: "markdown",
    scene: ["业务问答", "AI 编码"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "wiki/product/domestic-influencer/rules.md",
    summary: "国内 Pick 准入、任务、结算、审核与配置规则。",
    details: [
      {
        title: "当前状态",
        items: ["规则仍在持续沉淀，当前优先关注准入、任务配置、投稿审核、归因结算和账单状态", "遇到口径不一致时，需要同时核对业务规则、链路流程、配置和真实服务行为"],
      },
    ],
    x: 760,
    y: 360,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/flows.md",
    label: "wiki/product/domestic-influencer/flows.md",
    displayName: "核心流程",
    type: "markdown",
    scene: ["AI 编码", "服务架构"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "wiki/product/domestic-influencer/flows.md",
    summary: "国内 Pick 入驻、投稿、审核、归因、结算的主流程。",
    details: [
      {
        title: "自营投稿主链路",
        items: ["jianying_campaign /pick/portal -> auth + task + token", "SubmitPostExecutor -> pick_post_audit_record", "jianying_campaign_faas 审核 / 归因 / 结算 Timer 或 Consumer", "post_attribution_record / pick_post_settlement_record -> C 端 profit 或后台查询"],
      },
      {
        title: "口令 / 分享回流链路",
        items: ["用户复制 token 或三方链接", "jianying_campaign GetSchemaExecutor 区分 Pick 投稿回流 / Promo 回流", "调用 jianying_ug_rpc GetPromoLink", "返回 schema 或 deeplink", "FaaS 侧 token_attribution / process_token_timer 补齐"],
      },
      {
        title: "资源位 / Pick 任务结论",
        items: ["新增 Pick 任务本质是新增 resource_key = pick_task 的资源投放计划", "任务内容存在 t_resource_item_rel.material，不是单独 Pick 任务表", "后台投稿审核列表里的任务名称来自资源计划草稿表"],
      },
    ],
    x: 760,
    y: 430,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/errors.md",
    label: "wiki/product/domestic-influencer/errors.md",
    displayName: "错误与异常",
    type: "markdown",
    scene: ["SRE 排障", "业务问答"],
    domain: "domestic-influencer",
    confidence: "medium",
    path: "wiki/product/domestic-influencer/errors.md",
    summary: "国内 Pick 常见错误、异常状态和排查入口。",
    x: 760,
    y: 570,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/sop.md",
    label: "wiki/product/domestic-influencer/sop.md",
    displayName: "排障 SOP",
    type: "markdown",
    scene: ["SRE 排障"],
    domain: "domestic-influencer",
    confidence: "medium",
    path: "wiki/product/domestic-influencer/sop.md",
    summary: "国内 Pick 排障和操作 SOP。",
    details: [
      {
        title: "投稿后长时间无收益",
        items: ["查 pick_post_audit_record，确认投稿是否审核通过", "查 post_attribution_record，确认是否已有归因结果", "查 pick_post_settlement_record，确认是否已创建结算记录", "回看 jianying_campaign_faas/biz/pick/settlement/ timer 或 consumer"],
      },
      {
        title: "后台投稿列表 task_name 丢失",
        items: ["用 pick_post_audit_record.task_id 回查后台列表数据", "看 QueryPostAuditList 的任务回填逻辑", "查 t_resource_plan_draft 中对应任务是否存在", "确认任务计划是否被误删或环境切换不一致"],
      },
      {
        title: "账单状态未推进或打款失败",
        items: ["查 pick_payment_bill.bill_status 当前值", "查后台是否触发 SubmitBillAudit 或 ModifyBillStatus", "查 PickBillPayout 的调用路径与返回结果", "确认钱包打款回写和账单状态推进是否同时成功"],
      },
    ],
    x: 760,
    y: 640,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/insights.md",
    label: "wiki/product/domestic-influencer/insights.md",
    displayName: "业务结论",
    type: "markdown",
    scene: ["业务问答"],
    domain: "domestic-influencer",
    confidence: "medium",
    path: "wiki/product/domestic-influencer/insights.md",
    summary: "国内 Pick 已沉淀的业务结论、待确认项和判断依据。",
    x: 760,
    y: 710,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/references.md",
    label: "wiki/product/domestic-influencer/references.md",
    displayName: "参考资料",
    type: "markdown",
    scene: ["业务问答"],
    domain: "domestic-influencer",
    confidence: "medium",
    path: "wiki/product/domestic-influencer/references.md",
    summary: "国内 Pick 的外部引用、原始记录和待补资料。",
    x: 760,
    y: 780,
    size: "sm",
  },
  {
    id: "wiki/codebase/frontend-hosts/business-navigation.md",
    label: "wiki/codebase/frontend-hosts/business-navigation.md",
    displayName: "前端业务代码导航",
    type: "markdown",
    scene: ["AI 编码", "业务问答"],
    confidence: "verified",
    path: "wiki/codebase/frontend-hosts/business-navigation.md",
    summary: "达人营销、激励、锚点和分享回流类问题到前端 monorepo 的导航地图。",
    x: 125,
    y: 180,
    size: "md",
  },
  {
    id: "wiki/registry/repos.yaml",
    label: "wiki/registry/repos.yaml",
    displayName: "核心仓库与服务清单",
    type: "markdown",
    scene: ["服务架构", "业务问答"],
    confidence: "verified",
    path: "wiki/registry/repos.yaml",
    summary: "UG 前端仓库、后端服务、RPC、FaaS 和 Consumer 的职责清单，是理解模块技术资产的入口。",
    x: 530,
    y: 95,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-influencer/repositories.md",
    label: "wiki/product/domestic-influencer/repositories.md",
    displayName: "国内达人仓库说明",
    type: "markdown",
    scene: ["AI 编码", "业务问答"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "wiki/product/domestic-influencer/repositories.md",
    summary: "国内达人业务域下的仓库、服务和职责说明。",
    details: [
      {
        title: "前端入口",
        items: ["ies/capcut_web_ug/apps/web-cn-ssg/src/pages/pick/：Pick2.0 报名、授权、任务、收益、教程和端能力跳转", "growth/seeyou/apps/seeyou-social-cn/src/routes/pick/：Pick inhouse / agent、达人 / 视频审核等后台页面", "growth/seeyou/apps/seeyou-social-cn/src/routes/bgent/views/PickPlanView/：Pick 计划创建、预览、续期和资源配置"],
      },
      {
        title: "服务分工",
        items: ["jianying_campaign：C 端门户、投稿、收益查询、分享回流", "jianying_campaign_faas：归因消费、定时结算、账单生成、数据同步、补偿", "jianying_ug_backend：运营审核、账单审核、导出、状态推进", "jianying_ug_rpc：共享 Pick 查询、推广链接生成、钱包打款"],
      },
    ],
    x: 120,
    y: 410,
    size: "md",
  },
  {
    id: "wiki/product/overseas-anchor/flows.md",
    label: "wiki/product/overseas-anchor/flows.md",
    displayName: "海外锚点链路",
    type: "markdown",
    scene: ["服务架构", "业务问答"],
    domain: "overseas-anchor",
    confidence: "medium",
    path: "wiki/product/overseas-anchor/flows.md",
    summary: "海外锚点关键链路和代码入口。",
    x: 910,
    y: 95,
    size: "sm",
  },
  {
    id: "wiki/product/overseas-anchor/sop.md",
    label: "wiki/product/overseas-anchor/sop.md",
    displayName: "海外锚点 SOP",
    type: "markdown",
    scene: ["SRE 排障"],
    domain: "overseas-anchor",
    confidence: "medium",
    path: "wiki/product/overseas-anchor/sop.md",
    summary: "海外锚点常见排障 SOP。",
    x: 1110,
    y: 180,
    size: "sm",
  },
  {
    id: "CCUG TT 图模板锚点能力建设",
    label: "CCUG TT 图模板锚点能力建设",
    type: "prd",
    scene: ["业务问答", "服务架构"],
    domain: "overseas-anchor",
    confidence: "high",
    path: "raw/prd/2026-05-25/ccug-tt-photo-template-anchor.md",
    summary: "TT 图模板锚点能力建设 PRD。",
    x: 1015,
    y: 90,
    size: "md",
  },
  {
    id: "Pick2.0 国内达人任务配置",
    label: "Pick2.0 国内达人任务配置",
    type: "prd",
    scene: ["业务问答"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "raw/prd/2026-05-31/domestic-pick-dorado-offline-tasks.md",
    summary: "Pick2.0 国内达人任务配置相关 PRD。",
    x: 60,
    y: 520,
    size: "md",
  },
  {
    id: "bgent 达人审核入口在 AuditPlatformView",
    label: "bgent 达人审核入口在 AuditPlatformView",
    type: "business_insight",
    scene: ["AI 编码", "业务问答"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "growth/seeyou/apps/seeyou-social-cn/src/routes/bgent/views/AuditPlatformView/",
    summary: "bgent 达人审核入口落在 AuditPlatformView，并通过 kol 映射到 influencer_audit。",
    x: 565,
    y: 620,
    size: "md",
  },
  {
    id: "TT 锚点中间页在 capcut_anchor_landing_page",
    label: "TT 锚点中间页在 capcut_anchor_landing_page",
    type: "business_insight",
    scene: ["AI 编码", "业务问答"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "growth/ug-video-fe-os/apps/tiktok/capcut_anchor_landing_page",
    summary: "TikTok / CapCut 锚点中间页在 capcut_anchor_landing_page。",
    x: 780,
    y: 620,
    size: "md",
  },
  {
    id: "即梦海外分享回流在 dreamina-activities/share",
    label: "即梦海外分享回流在 dreamina-activities/share",
    type: "business_insight",
    scene: ["业务问答", "AI 编码"],
    domain: "overseas-influencer",
    confidence: "verified",
    path: "ies/capcut_web_ug_os/apps/dreamina-activities/src/pages/share/",
    summary: "即梦海外分享回流主要入口在 dreamina-activities/share。",
    x: 1035,
    y: 650,
    size: "md",
  },
  {
    id: "分享链路异常排查",
    label: "分享链路异常排查",
    type: "alert_sop",
    scene: ["SRE 排障"],
    confidence: "medium",
    path: "wiki/runbooks/call-error-rate-alert.md",
    summary: "分享链路异常时从日志、Trace、短链、回流归因和下游依赖逐步排查。",
    x: 1030,
    y: 735,
    size: "md",
  },
  {
    id: "锚点不展示排查",
    label: "锚点不展示排查",
    type: "alert_sop",
    scene: ["SRE 排障"],
    domain: "overseas-anchor",
    confidence: "high",
    path: "wiki/product/overseas-anchor/sop.md",
    summary: "锚点不展示时检查挂载白名单、anchor conf、素材信息和端侧展示条件。",
    x: 835,
    y: 735,
    size: "md",
  },
  {
    id: "回流归因异常排查",
    label: "回流归因异常排查",
    type: "alert_sop",
    scene: ["SRE 排障"],
    confidence: "medium",
    path: "raw/messages/2026-06-02/attribution-platform-channel-id-sop.md",
    summary: "回流归因异常时检查 channel id、数据集、埋点和归因链路。",
    x: 150,
    y: 735,
    size: "md",
  },
  {
    id: "influencer_audit",
    label: "influencer_audit",
    type: "api_contract",
    scene: ["AI 编码", "服务架构"],
    domain: "domestic-influencer",
    confidence: "verified",
    summary: "bgent 达人审核场景标识，由 kol 类型映射而来。",
    x: 745,
    y: 350,
    size: "sm",
  },
  {
    id: "audit_influencer_review/submit",
    label: "audit_influencer_review/submit",
    type: "api_contract",
    scene: ["AI 编码", "服务架构"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "/bgent/audit_influencer_review/submit",
    summary: "提交达人审核结果接口。",
    x: 890,
    y: 640,
    size: "sm",
  },
  {
    id: "audit_influencer_review/result",
    label: "audit_influencer_review/result",
    type: "api_contract",
    scene: ["AI 编码", "服务架构"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "/bgent/audit_influencer_review/result",
    summary: "查询达人审核结果接口。",
    x: 880,
    y: 535,
    size: "sm",
  },
  {
    id: "audit_influencer_review/retry",
    label: "audit_influencer_review/retry",
    type: "api_contract",
    scene: ["AI 编码"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "/bgent/audit_influencer_review/retry",
    summary: "达人审核重试接口。",
    x: 975,
    y: 610,
    size: "sm",
  },
  {
    id: "audit_influencer_review/update",
    label: "audit_influencer_review/update",
    type: "api_contract",
    scene: ["AI 编码"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "/bgent/audit_influencer_review/update",
    summary: "达人审核更新接口。",
    x: 770,
    y: 685,
    size: "sm",
  },
  {
    id: "ug-wiki",
    label: "ug-wiki",
    displayName: "UG Wiki 知识底座",
    type: "data_asset",
    scene: ["总览", "AI 编码", "业务问答", "服务架构", "SRE 排障"],
    confidence: "verified",
    path: "/Users/bytedance/go/src/code.byted.org/growth/jianying_ug_spec",
    summary: "按业务域、代码仓库、链路流程、SOP、实体和横向资产组织的 UG 知识底座。",
    details: [
      {
        title: "用户视角切片",
        items: ["分业务模块：专业名词、链路流程、核心仓库、对接人", "横向资产：埋点数据、PSM 前后端服务、线上告警定位规范、配置灰度、异步任务"],
      },
    ],
    related: ["manifest.yaml", "wiki/index.md", "wiki/registry/domains.yaml", "wiki/registry/repos.yaml"],
    x: 520,
    y: 80,
    size: "lg",
  },
  {
    id: "asset/user-view-slices",
    label: "asset/user-view-slices",
    displayName: "用户视角知识切片",
    type: "data_asset",
    scene: ["总览", "业务问答"],
    confidence: "high",
    path: "knowledge/AI-INDEX.md",
    summary: "把 wiki 原始材料蒸馏成用户能直接检索的几类资产：术语、流程、仓库服务、对接人、SOP 和横向数据。",
    details: [
      {
        title: "模块内资产",
        items: ["专业名词：业务对象、ID 口径、关键配置", "链路流程：用户动作到服务、异步任务和数据落表", "核心仓库：前端、后端、FaaS、RPC", "对接人：PM/RD/产运或对应群组"],
      },
      {
        title: "横向资产",
        items: ["埋点与数据集", "PSM / 服务拓扑", "线上告警定位规范", "配置灰度与发布入口", "MQ/EventBus/定时任务"],
      },
    ],
    x: 410,
    y: 175,
    size: "md",
  },
  {
    id: "asset/tracking-datasets",
    label: "asset/tracking-datasets",
    displayName: "埋点与业务数据集",
    type: "tracking",
    scene: ["总览", "业务问答", "SRE 排障"],
    confidence: "high",
    path: "knowledge/AI-INDEX.md#业务结论索引",
    summary: "围绕投稿、归因、结算和锚点展示沉淀的数据集与 ID 口径。",
    details: [
      {
        title: "高频数据口径",
        items: ["Global Pick：投稿数据集、投稿明细数据集、结算数据集", "cc_video_id 用于归因，item_id 用于结算，二者错位会造成部分投稿无法归因", "anchor_infos 是锚点展示和挂载排查的关键字段"],
      },
    ],
    related: ["term/cc_video_id", "term/item_id", "term/anchor_infos", "dataset/global-pick-three-datasets"],
    x: 1020,
    y: 210,
    size: "md",
  },
  {
    id: "asset/psm-service-map",
    label: "asset/psm-service-map",
    displayName: "PSM 前后端服务图谱",
    type: "data_asset",
    scene: ["总览", "服务架构", "SRE 排障"],
    confidence: "verified",
    path: "knowledge/registry/repos.yaml",
    summary: "从仓库注册表抽出的前端应用、后端服务、RPC、FaaS 和 Consumer 映射。",
    details: [
      {
        title: "服务分层",
        items: ["前端：seeyou、capcut_web_ug、capcut_web_ug_os、ug-video-fe-os", "国内后端：jianying_campaign、jianying_campaign_faas、jianying_ug_backend、jianying_ug_rpc、jianying_ug_anchor", "海外后端：capcut_campaign、capcut_ug_backend、capcut_ug_rpc、capcut_ug_http、post_incentive_faas、TikTok consumers"],
      },
    ],
    related: ["wiki/registry/repos.yaml", "jianying_campaign", "capcut_campaign", "capcut_ug_backend", "capcut_ug_http"],
    x: 1040,
    y: 305,
    size: "md",
  },
  {
    id: "asset/online-alert-policy",
    label: "asset/online-alert-policy",
    displayName: "线上告警定位规范",
    type: "alert_policy",
    scene: ["总览", "SRE 排障"],
    confidence: "verified",
    path: "AGENTS.md#线上告警定位处理思路",
    summary: "告警排查必须先读报警卡片，再确认服务架构和机房，使用 Argos 取日志/指标/Trace，并结合代码、配置和变更闭环。",
    details: [
      {
        title: "排查顺序",
        items: ["读取报警卡片：时间、服务、指标、地区、实例、错误信息", "用 growth-architecture 确认业务域、仓库、PSM、部署机房", "用 Argos 拉日志、指标、Trace 和报警上下文", "检查时间窗内发布/配置变更，再映射到代码入口或外部依赖"],
      },
    ],
    related: ["分享链路异常排查", "锚点不展示排查", "回流归因异常排查"],
    x: 980,
    y: 720,
    size: "md",
  },
  {
    id: "asset/config-gray-release",
    label: "asset/config-gray-release",
    displayName: "配置与灰度资产",
    type: "config",
    scene: ["总览", "AI 编码", "业务问答", "SRE 排障"],
    confidence: "high",
    path: "knowledge/registry/domains.yaml",
    summary: "沉淀 Pick 配置、奖励配置、锚点配置、白名单、资源位计划与灰度发布入口。",
    details: [
      {
        title: "典型配置",
        items: ["pick_conf / pick_settlement_conf：Pick 任务与结算", "anchor conf / 白名单：锚点挂载与展示", "reward config：激励任务、裂变、榜单和发奖"],
      },
    ],
    related: ["term/pick_conf_settlement_conf", "config/domestic-anchor/anchor_conf", "config/overseas-anchor/anchor_conf"],
    x: 1010,
    y: 395,
    size: "md",
  },
  {
    id: "asset/async-eventbus",
    label: "asset/async-eventbus",
    displayName: "异步任务与 MQ/EventBus",
    type: "data_asset",
    scene: ["总览", "服务架构", "SRE 排障"],
    confidence: "high",
    path: "knowledge/registry/repos.yaml",
    summary: "承接归因、审核同步、结算、账单、榜单刷新、item 事件回补等异步链路。",
    details: [
      {
        title: "典型消费者",
        items: ["jianying_campaign_faas：国内 Pick 归因、结算、账单、定时任务", "post_incentive_faas：海外促投稿与 Global Pick 发奖、统计、通知", "tiktok_capcut_ug_consumer / mq_consumer：TikTok item 变更、安装和冷启动事件"],
      },
    ],
    related: ["jianying_campaign_faas", "post_incentive_faas", "tiktok_capcut_ug_consumer", "tiktok_capcut_ug_mq_consumer"],
    x: 1035,
    y: 500,
    size: "md",
  },
  {
    id: "asset/contact-map",
    label: "asset/contact-map",
    displayName: "对接人与协作入口",
    type: "owner",
    scene: ["总览", "业务问答"],
    confidence: "medium",
    path: "knowledge/AI-INDEX.md#业务结论索引",
    summary: "把已知 PM、RD、产运或服务 Owner 以资产节点形式沉淀，方便从业务问题直接找到协作入口。",
    details: [
      {
        title: "当前明确沉淀",
        items: ["国内 Pick 夜莺展归：PM 张晨岳，RD 陆健", "其他域先沉淀为模块 Owner 群组，后续从 wiki references 和值班信息继续补齐人名"],
      },
    ],
    related: ["owner/domestic-pick/zhangchenyue", "owner/domestic-pick/lujian"],
    x: 280,
    y: 720,
    size: "md",
  },
  {
    id: "overseas-influencer",
    label: "overseas-influencer",
    displayName: "海外达人",
    type: "domain",
    scene: ["总览", "业务问答", "AI 编码", "服务架构"],
    domain: "overseas-influencer",
    confidence: "high",
    path: "knowledge/product/pick/global/",
    summary: "海外达人 / Global Pick 业务域，覆盖 CapCut Pioneer、投稿、审核、归因、结算、CPA/CPM 和运营快照。",
    related: ["capcut_campaign", "post_incentive_faas", "capcut_ug_backend", "term/cc_video_id", "flow/pick/global/submission"],
    x: 930,
    y: 250,
    size: "lg",
  },
  {
    id: "overseas-incentive",
    label: "overseas-incentive",
    displayName: "海外激励",
    type: "domain",
    scene: ["总览", "业务问答", "AI 编码", "服务架构"],
    domain: "overseas-incentive",
    confidence: "medium",
    path: "knowledge/product/incentive/global/",
    summary: "海外 Post Incentive 激励域，覆盖投稿激励、发奖、排行榜、配置生效和后台排障。",
    related: ["post_incentive_faas", "capcut_ug_backend", "capcut_ug_rpc", "flow/incentive/global/post_incentive"],
    x: 1045,
    y: 455,
    size: "lg",
  },
  {
    id: "domestic-anchor",
    label: "domestic-anchor",
    displayName: "国内锚点",
    type: "domain",
    scene: ["总览", "业务问答", "AI 编码", "服务架构", "SRE 排障"],
    domain: "domestic-anchor",
    confidence: "medium",
    path: "knowledge/product/anchor/domestic/",
    summary: "国内锚点业务域，覆盖锚点挂载、分享链路、素材数据、白名单和后台配置。",
    related: ["jianying_ug_anchor", "term/anchor_infos", "flow/anchor/domestic/query_share", "config/domestic-anchor/anchor_conf"],
    x: 300,
    y: 545,
    size: "lg",
  },
  {
    id: "domestic-pick/terms-index",
    label: "domestic-pick/terms-index",
    displayName: "国内 Pick 专业名词",
    type: "term",
    scene: ["总览", "业务问答"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "wiki/product/domestic-influencer/entities.md",
    summary: "国内 Pick 高频术语入口：资源位任务、物料、Pick 配置、结算配置、账单和归因。",
    related: ["term/pick_task", "term/t_resource_item_rel_material", "term/pick_conf_settlement_conf"],
    x: 500,
    y: 535,
    size: "md",
  },
  {
    id: "term/pick_task",
    label: "pick_task",
    displayName: "Pick 资源位任务",
    type: "term",
    scene: ["总览", "业务问答", "AI 编码"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "wiki/product/domestic-influencer/flows.md",
    summary: "新增 Pick 任务本质是新增 resource_key = pick_task 的资源投放计划，不是独立任务表。",
    details: [
      {
        title: "排查口径",
        items: ["任务内容在资源位计划体系中维护", "后台任务名缺失时优先查资源计划草稿和物料关系", "C 端任务展示来自资源位运行时构建"],
      },
    ],
    related: ["term/t_resource_item_rel_material", "flow/pick/domestic/resource_task", "jianying_ug_rpc"],
    x: 445,
    y: 610,
    size: "sm",
  },
  {
    id: "term/t_resource_item_rel_material",
    label: "t_resource_item_rel.material",
    displayName: "资源位物料 material",
    type: "term",
    scene: ["总览", "业务问答", "AI 编码"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "wiki/product/domestic-influencer/entities.md",
    summary: "Pick 任务内容存在 t_resource_item_rel.material，是资源投放计划里的物料字段。",
    related: ["term/pick_task", "Pick2.0 国内达人任务配置"],
    x: 515,
    y: 650,
    size: "sm",
  },
  {
    id: "term/pick_conf_settlement_conf",
    label: "pick_conf / pick_settlement_conf",
    displayName: "Pick 配置与结算配置",
    type: "config",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "knowledge/AI-INDEX.md#Entity 反查映射",
    summary: "国内 Pick 配置和结算配置，是排查任务展示、结算金额和配置生效的核心入口。",
    related: ["asset/config-gray-release", "flow/pick/domestic/self_operated_submission"],
    x: 595,
    y: 615,
    size: "sm",
  },
  {
    id: "flow/pick/domestic/self_operated_submission",
    label: "pick/domestic/self_operated_submission",
    displayName: "自营投稿主链路",
    type: "flow",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "国内 Pick 自营投稿主链路：C 端入口、投稿提交、审核记录、异步归因与结算。",
    details: [
      {
        title: "链路节点",
        items: ["jianying_campaign /pick/portal", "SubmitPostExecutor -> pick_post_audit_record", "jianying_campaign_faas 审核 / 归因 / 结算 Timer 或 Consumer", "post_attribution_record / pick_post_settlement_record -> C 端 profit 或后台查询"],
      },
    ],
    related: ["jianying_campaign", "jianying_campaign_faas", "wiki/product/domestic-influencer/flows.md"],
    x: 370,
    y: 680,
    size: "md",
  },
  {
    id: "flow/pick/domestic/token_reflow",
    label: "pick/domestic/token_reflow",
    displayName: "口令与分享回流链路",
    type: "flow",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "domestic-influencer",
    confidence: "high",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "用户复制 token 或三方链接后，经 jianying_campaign 识别承接，再调用 jianying_ug_rpc 生成推广链接并由 FaaS 补齐归因。",
    related: ["jianying_campaign", "jianying_ug_rpc", "回流归因异常排查"],
    x: 285,
    y: 650,
    size: "md",
  },
  {
    id: "flow/pick/domestic/agent_bill",
    label: "pick/domestic/agent_bill",
    displayName: "代理账单链路",
    type: "flow",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "domestic-influencer",
    confidence: "high",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "代理账单生成、提交审核、账单状态推进和钱包打款链路。",
    related: ["jianying_ug_backend", "jianying_ug_rpc", "wiki/product/domestic-influencer/sop.md"],
    x: 235,
    y: 610,
    size: "sm",
  },
  {
    id: "flow/pick/domestic/resource_task",
    label: "pick/domestic/resource_task",
    displayName: "资源位任务链路",
    type: "flow",
    scene: ["总览", "AI 编码", "业务问答"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "Pick 任务创建、资源计划草稿、物料关系和运行时打包链路。",
    related: ["term/pick_task", "term/t_resource_item_rel_material", "Pick2.0 国内达人任务配置"],
    x: 310,
    y: 565,
    size: "sm",
  },
  {
    id: "jianying_campaign_faas",
    label: "jianying_campaign_faas",
    type: "service",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "code.byted.org/growth/jianying_campaign_faas",
    summary: "国内 Pick 异步归因、审核同步、结算、账单、定时任务与内部调试入口。",
    related: ["asset/async-eventbus", "flow/pick/domestic/self_operated_submission"],
    x: 110,
    y: 650,
    size: "md",
  },
  {
    id: "jianying_ug_backend",
    label: "jianying_ug_backend",
    type: "service",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "domestic-influencer",
    confidence: "verified",
    path: "code.byted.org/growth/jianying_ug_backend",
    summary: "国内运营后台服务，负责达人审核、投稿审核、资源位计划、代理账单与状态推进。",
    related: ["flow/pick/domestic/agent_bill", "AuditPlatformView"],
    x: 205,
    y: 690,
    size: "md",
  },
  {
    id: "owner/domestic-pick/zhangchenyue",
    label: "PM 张晨岳",
    displayName: "夜莺展归 PM 张晨岳",
    type: "owner",
    scene: ["总览", "业务问答"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "knowledge/AI-INDEX.md#国内-Pick-补充",
    summary: "国内 Pick 夜莺展归对接 PM。",
    related: ["owner/domestic-pick/lujian", "asset/contact-map"],
    x: 185,
    y: 780,
    size: "sm",
  },
  {
    id: "owner/domestic-pick/lujian",
    label: "RD 陆健",
    displayName: "夜莺展归 RD 陆健",
    type: "owner",
    scene: ["总览", "业务问答"],
    domain: "domestic-influencer",
    confidence: "high",
    path: "knowledge/AI-INDEX.md#国内-Pick-补充",
    summary: "国内 Pick 夜莺展归对接 RD。",
    related: ["owner/domestic-pick/zhangchenyue", "asset/contact-map"],
    x: 255,
    y: 800,
    size: "sm",
  },
  {
    id: "wiki/product/overseas-influencer/README.md",
    label: "wiki/product/overseas-influencer/README.md",
    displayName: "海外 Pick 领域总览",
    type: "markdown",
    scene: ["总览", "业务问答", "AI 编码"],
    domain: "overseas-influencer",
    confidence: "medium",
    path: "knowledge/product/pick/global/README.md",
    summary: "海外达人 Global Pick 总览，覆盖 CapCut Pioneer、投稿、审核、归因、结算和运营快照。",
    related: ["overseas-influencer", "term/cc_video_id", "flow/pick/global/submission"],
    x: 845,
    y: 205,
    size: "md",
  },
  {
    id: "term/cc_video_id",
    label: "cc_video_id",
    displayName: "cc_video_id",
    type: "term",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "overseas-influencer",
    confidence: "verified",
    path: "knowledge/AI-INDEX.md#Entity-反查映射",
    summary: "Global Pick 归因使用 cc_video_id，与结算侧 item_id 不是同一口径。",
    related: ["term/item_id", "asset/tracking-datasets"],
    x: 910,
    y: 350,
    size: "sm",
  },
  {
    id: "term/item_id",
    label: "item_id",
    displayName: "item_id",
    type: "term",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "overseas-influencer",
    confidence: "verified",
    path: "knowledge/AI-INDEX.md#业务结论索引",
    summary: "Global Pick 结算使用 item_id；多发场景里 cc_video_id 与 item_id 错位可能造成部分 item 无归因。",
    related: ["term/cc_video_id", "dataset/global-pick-three-datasets"],
    x: 970,
    y: 360,
    size: "sm",
  },
  {
    id: "term/cpa_cpm",
    label: "CPA / CPM",
    displayName: "CPA 与 CPM 任务区别",
    type: "term",
    scene: ["总览", "业务问答"],
    domain: "overseas-influencer",
    confidence: "high",
    path: "knowledge/AI-INDEX.md#海外-Pick-业务结论",
    summary: "CPA 按 acquisition 口径不走审核；CPM 需要审核与 7 日播放梯度，通常月末审核、次月付款。",
    related: ["flow/pick/global/submission", "capcut_ug_backend"],
    x: 1025,
    y: 315,
    size: "sm",
  },
  {
    id: "term/growth_program",
    label: "Growth Program / 校园",
    displayName: "Growth Program 与校园专项",
    type: "term",
    scene: ["总览", "业务问答"],
    domain: "overseas-influencer",
    confidence: "medium",
    path: "knowledge/AI-INDEX.md#海外-Pick-业务结论",
    summary: "校园专项与自营身份互斥；校园 CPM 有 ROW、$40/video、单视频上限 $2500 等特殊结算规则。",
    related: ["term/cpa_cpm"],
    x: 1065,
    y: 250,
    size: "sm",
  },
  {
    id: "dataset/global-pick-three-datasets",
    label: "Global Pick 三类数据集",
    displayName: "投稿 / 明细 / 结算数据集",
    type: "tracking",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "overseas-influencer",
    confidence: "high",
    path: "knowledge/AI-INDEX.md#海外-Pick-业务结论",
    summary: "Global Pick 排查围绕投稿记录、投稿明细和结算数据三类数据集展开。",
    related: ["asset/tracking-datasets", "term/cc_video_id", "term/item_id"],
    x: 1120,
    y: 355,
    size: "md",
  },
  {
    id: "flow/pick/global/submission",
    label: "pick/global/submission",
    displayName: "Global Pick 投稿链路",
    type: "flow",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "overseas-influencer",
    confidence: "high",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "海外 Pick 投稿链路：capcut_campaign submit_video_link、capcut_ug_backend 审核配置、post_incentive_faas 发奖。",
    related: ["capcut_campaign", "capcut_ug_backend", "post_incentive_faas"],
    x: 890,
    y: 470,
    size: "md",
  },
  {
    id: "flow/pick/global/review_reward",
    label: "pick/global/review_reward",
    displayName: "审核与发奖链路",
    type: "flow",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "overseas-influencer",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "投稿已有审核结果但无收益时，沿审核记录、归因结果、发奖任务和结算数据回查。",
    related: ["dataset/global-pick-three-datasets", "post_incentive_faas"],
    x: 1010,
    y: 480,
    size: "sm",
  },
  {
    id: "capcut_campaign",
    label: "capcut_campaign",
    type: "service",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "overseas-influencer",
    confidence: "verified",
    path: "code.byted.org/growth/capcut_campaign",
    summary: "海外 Pick / Post Incentive C 端入口，承载活动、投稿、状态和收益查询。",
    related: ["flow/pick/global/submission", "flow/incentive/global/post_incentive"],
    x: 845,
    y: 560,
    size: "md",
  },
  {
    id: "post_incentive_faas",
    label: "post_incentive_faas",
    type: "service",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "overseas-incentive",
    confidence: "verified",
    path: "code.byted.org/growth/post_incentive_faas",
    summary: "海外促投稿与 Global Pick 异步发奖、统计、机器人通知和补偿任务。",
    related: ["asset/async-eventbus", "flow/incentive/global/post_incentive", "flow/pick/global/submission"],
    x: 1100,
    y: 580,
    size: "md",
  },
  {
    id: "capcut_ug_backend",
    label: "capcut_ug_backend",
    type: "service",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/capcut_ug_backend",
    summary: "海外运营后台，管理活动计划、奖励配置、Pick 审核和锚点配置。",
    related: ["overseas-influencer", "overseas-incentive", "overseas-anchor"],
    x: 1170,
    y: 430,
    size: "md",
  },
  {
    id: "capcut_ug_rpc",
    label: "capcut_ug_rpc",
    type: "service",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "overseas-incentive",
    confidence: "verified",
    path: "code.byted.org/growth/capcut_ug_rpc",
    summary: "海外 UG 共享 RPC，承接奖励、库存、Pick 查询和跨服务共享能力。",
    related: ["capcut_ug_backend", "post_incentive_faas"],
    x: 1150,
    y: 505,
    size: "md",
  },
  {
    id: "wiki/product/domestic-incentive/README.md",
    label: "wiki/product/domestic-incentive/README.md",
    displayName: "国内激励领域总览",
    type: "markdown",
    scene: ["总览", "业务问答", "AI 编码"],
    domain: "domestic-incentive",
    confidence: "medium",
    path: "knowledge/product/incentive/domestic/README.md",
    summary: "国内激励与裂变业务总览，覆盖任务奖励、邀请裂变、会员/订阅奖励和防薅策略。",
    related: ["domestic-incentive", "flow/incentive/domestic/fission_and_task"],
    x: 155,
    y: 430,
    size: "md",
  },
  {
    id: "term/domestic-incentive/task_reward",
    label: "任务奖励",
    displayName: "国内任务奖励",
    type: "term",
    scene: ["总览", "业务问答"],
    domain: "domestic-incentive",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "国内激励中用户完成任务后的奖励发放口径，排查时关注完成态、发奖记录和风控结果。",
    related: ["flow/incentive/domestic/fission_and_task", "sop/domestic-incentive/reward_missing"],
    x: 70,
    y: 485,
    size: "sm",
  },
  {
    id: "term/domestic-incentive/fission_invite",
    label: "邀请裂变",
    displayName: "邀请裂变奖励",
    type: "term",
    scene: ["总览", "业务问答"],
    domain: "domestic-incentive",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "邀请关系、任务完成、奖励到账和防薅规则共同决定裂变奖励是否发放。",
    related: ["flow/incentive/domestic/invite_reward"],
    x: 80,
    y: 545,
    size: "sm",
  },
  {
    id: "flow/incentive/domestic/fission_and_task",
    label: "incentive/domestic/fission_and_task",
    displayName: "国内裂变与任务奖励链路",
    type: "flow",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "domestic-incentive",
    confidence: "medium",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "国内激励主链路，串联任务完成、邀请关系、奖励发放、风控和状态查询。",
    related: ["jianying_campaign", "jianying_ug_rpc", "sop/domestic-incentive/reward_missing"],
    x: 160,
    y: 555,
    size: "md",
  },
  {
    id: "flow/incentive/domestic/invite_reward",
    label: "incentive/domestic/invite_reward",
    displayName: "邀请奖励链路",
    type: "flow",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "domestic-incentive",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "邀请裂变奖励未到账时，沿邀请关系、被邀请人完成状态、奖励记录和风控拦截回查。",
    related: ["term/domestic-incentive/fission_invite", "jianying_campaign_faas"],
    x: 240,
    y: 520,
    size: "sm",
  },
  {
    id: "config/domestic-incentive/reward_config",
    label: "domestic reward config",
    displayName: "国内激励配置",
    type: "config",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "domestic-incentive",
    confidence: "medium",
    path: "knowledge/product/incentive/domestic/configuration.md",
    summary: "国内激励任务、奖励金额、发奖节奏、灰度和防薅策略配置。",
    related: ["asset/config-gray-release", "flow/incentive/domestic/fission_and_task"],
    x: 230,
    y: 465,
    size: "sm",
  },
  {
    id: "sop/domestic-incentive/reward_missing",
    label: "完成任务但未发奖",
    displayName: "国内激励未发奖 SOP",
    type: "alert_sop",
    scene: ["总览", "SRE 排障"],
    domain: "domestic-incentive",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "完成任务但未发奖时，确认任务完成、发奖记录、风控拦截、异步任务和配置生效状态。",
    related: ["flow/incentive/domestic/fission_and_task", "asset/online-alert-policy"],
    x: 120,
    y: 630,
    size: "sm",
  },
  {
    id: "wiki/product/overseas-incentive/README.md",
    label: "wiki/product/overseas-incentive/README.md",
    displayName: "海外激励领域总览",
    type: "markdown",
    scene: ["总览", "业务问答", "AI 编码"],
    domain: "overseas-incentive",
    confidence: "medium",
    path: "knowledge/product/incentive/global/README.md",
    summary: "海外 Post Incentive 总览，覆盖投稿后发奖、配置生效、排行榜和运营后台。",
    related: ["overseas-incentive", "flow/incentive/global/post_incentive"],
    x: 1130,
    y: 360,
    size: "md",
  },
  {
    id: "term/overseas-incentive/post_incentive",
    label: "Post Incentive",
    displayName: "Post Incentive",
    type: "term",
    scene: ["总览", "业务问答"],
    domain: "overseas-incentive",
    confidence: "medium",
    path: "knowledge/product/incentive/global/entities.md",
    summary: "海外投稿激励，关注投稿完成、统计归因、奖励发放和榜单展示。",
    related: ["flow/incentive/global/post_incentive", "post_incentive_faas"],
    x: 1205,
    y: 555,
    size: "sm",
  },
  {
    id: "term/overseas-incentive/leaderboard",
    label: "Leaderboard",
    displayName: "排行榜",
    type: "term",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "overseas-incentive",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "排行榜异常时关注数据刷新、统计窗口、配置生效和缓存。",
    related: ["flow/incentive/global/leaderboard_refresh", "sop/overseas-incentive/reward_config"],
    x: 1220,
    y: 470,
    size: "sm",
  },
  {
    id: "flow/incentive/global/post_incentive",
    label: "incentive/global/post_incentive",
    displayName: "Global Post Incentive 发奖链路",
    type: "flow",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "overseas-incentive",
    confidence: "medium",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "海外促投稿发奖链路：C 端投稿、统计归因、post_incentive_faas 发奖和通知。",
    related: ["capcut_campaign", "post_incentive_faas", "capcut_ug_rpc"],
    x: 1080,
    y: 650,
    size: "md",
  },
  {
    id: "flow/incentive/global/leaderboard_refresh",
    label: "incentive/global/leaderboard_refresh",
    displayName: "海外榜单刷新链路",
    type: "flow",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "overseas-incentive",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "排行榜异常排查链路，重点看统计窗口、异步刷新、缓存和前端展示条件。",
    related: ["term/overseas-incentive/leaderboard", "post_incentive_faas"],
    x: 1190,
    y: 640,
    size: "sm",
  },
  {
    id: "sop/overseas-incentive/reward_config",
    label: "海外激励配置/发奖 SOP",
    displayName: "海外激励排障 SOP",
    type: "alert_sop",
    scene: ["总览", "SRE 排障"],
    domain: "overseas-incentive",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "投稿后未发奖、后台配置改动未生效、排行榜异常的排查入口。",
    related: ["asset/online-alert-policy", "config/overseas-incentive/reward_config"],
    x: 1180,
    y: 715,
    size: "sm",
  },
  {
    id: "config/overseas-incentive/reward_config",
    label: "global reward config",
    displayName: "海外激励配置",
    type: "config",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "overseas-incentive",
    confidence: "medium",
    path: "knowledge/product/incentive/global/configuration.md",
    summary: "海外激励奖励配置、榜单配置、灰度和后台发布状态。",
    related: ["asset/config-gray-release", "capcut_ug_backend"],
    x: 1260,
    y: 610,
    size: "sm",
  },
  {
    id: "wiki/product/domestic-anchor/README.md",
    label: "wiki/product/domestic-anchor/README.md",
    displayName: "国内锚点领域总览",
    type: "markdown",
    scene: ["总览", "业务问答", "AI 编码"],
    domain: "domestic-anchor",
    confidence: "medium",
    path: "knowledge/product/anchor/domestic/README.md",
    summary: "国内锚点总览，覆盖锚点查询、挂载、分享、素材数据和白名单。",
    related: ["domestic-anchor", "flow/anchor/domestic/query_share"],
    x: 380,
    y: 465,
    size: "md",
  },
  {
    id: "term/anchor_infos",
    label: "anchor_infos",
    displayName: "anchor_infos",
    type: "term",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "domestic-anchor",
    confidence: "high",
    path: "knowledge/AI-INDEX.md#Entity-反查映射",
    summary: "锚点挂载和展示排查的关键字段，决定素材、模板和端侧展示信息是否齐全。",
    related: ["asset/tracking-datasets", "flow/anchor/domestic/query_share", "flow/anchor/global/item_pack_web_display"],
    x: 375,
    y: 610,
    size: "sm",
  },
  {
    id: "term/domestic-anchor/whitelist",
    label: "锚点挂载白名单",
    displayName: "锚点挂载白名单",
    type: "term",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "domestic-anchor",
    confidence: "high",
    path: "knowledge/AI-INDEX.md#海外-Pick-业务结论",
    summary: "只有白名单 Pick 创作者才能自动或手动挂载锚点，展示异常时优先确认名单和身份。",
    related: ["config/domestic-anchor/anchor_conf", "sop/domestic-anchor/not_display"],
    x: 440,
    y: 565,
    size: "sm",
  },
  {
    id: "flow/anchor/domestic/query_share",
    label: "anchor/domestic/query_and_share",
    displayName: "国内锚点查询与分享链路",
    type: "flow",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "domestic-anchor",
    confidence: "medium",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "国内锚点挂载、查询和分享链路，连接锚点服务、前端后台配置、素材数据和分享中间页。",
    related: ["jianying_ug_anchor", "growth/seeyou", "term/anchor_infos"],
    x: 390,
    y: 700,
    size: "md",
  },
  {
    id: "jianying_ug_anchor",
    label: "jianying_ug_anchor",
    type: "service",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "domestic-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/jianying_ug_anchor",
    summary: "国内锚点核心服务，承接锚点配置、查询、挂载和素材关联能力。",
    related: ["flow/anchor/domestic/query_share", "config/domestic-anchor/anchor_conf"],
    x: 470,
    y: 735,
    size: "md",
  },
  {
    id: "config/domestic-anchor/anchor_conf",
    label: "domestic anchor conf",
    displayName: "国内锚点配置",
    type: "config",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "domestic-anchor",
    confidence: "medium",
    path: "knowledge/product/anchor/domestic/configuration.md",
    summary: "国内锚点配置、白名单、素材策略和端侧展示条件。",
    related: ["asset/config-gray-release", "term/domestic-anchor/whitelist"],
    x: 515,
    y: 650,
    size: "sm",
  },
  {
    id: "sop/domestic-anchor/not_display",
    label: "国内锚点不展示 SOP",
    displayName: "国内锚点不展示排查",
    type: "alert_sop",
    scene: ["总览", "SRE 排障"],
    domain: "domestic-anchor",
    confidence: "medium",
    path: "knowledge/registry/sop.yaml",
    summary: "锚点不展示时检查白名单、配置、素材数据、分享链路和端侧展示条件。",
    related: ["asset/online-alert-policy", "term/anchor_infos", "config/domestic-anchor/anchor_conf"],
    x: 510,
    y: 795,
    size: "sm",
  },
  {
    id: "term/overseas-anchor/photo_template_anchor",
    label: "TT 图模板锚点",
    displayName: "TT 图模板锚点",
    type: "term",
    scene: ["总览", "业务问答"],
    domain: "overseas-anchor",
    confidence: "high",
    path: "raw/prd/2026-05-25/ccug-tt-photo-template-anchor.md",
    summary: "TikTok 图模板锚点能力，关联 CapCut / Dreamina / Pippit landing 与锚点展示。",
    related: ["CCUG TT 图模板锚点能力建设", "capcut_anchor_landing_page"],
    x: 845,
    y: 250,
    size: "sm",
  },
  {
    id: "flow/anchor/global/config_landing",
    label: "anchor/global/config_and_landing",
    displayName: "Global 锚点配置与落地页链路",
    type: "flow",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "high",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "海外锚点从后台配置到 CapCut/TikTok landing 展示的主链路。",
    related: ["capcut_ug_backend", "capcut_ug_http", "capcut_anchor_landing_page"],
    x: 910,
    y: 680,
    size: "md",
  },
  {
    id: "flow/anchor/global/item_pack_web_display",
    label: "anchor/global/item_pack_and_web_display",
    displayName: "Global 锚点 item pack 与 Web 展示链路",
    type: "flow",
    scene: ["总览", "AI 编码", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "medium",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "TikTok item pack、Web 展示和锚点信息透传链路。",
    related: ["term/anchor_infos", "item_anchor", "tiktok_web_core", "web_pack", "web_webapi"],
    x: 1015,
    y: 650,
    size: "md",
  },
  {
    id: "flow/anchor/global/item_event_backfill",
    label: "anchor/global/item_event_backfill",
    displayName: "Global 锚点 item 事件补数链路",
    type: "flow",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "medium",
    path: ".ai/indexes/flow_registry.yaml",
    summary: "TikTok item 变更、安装、冷启动事件消费与锚点数据补偿链路。",
    related: ["tiktok_capcut_ug_consumer", "tiktok_capcut_ug_mq_consumer", "asset/async-eventbus"],
    x: 1125,
    y: 650,
    size: "sm",
  },
  {
    id: "config/overseas-anchor/anchor_conf",
    label: "global anchor conf",
    displayName: "海外锚点配置",
    type: "config",
    scene: ["总览", "业务问答", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "high",
    path: "knowledge/product/anchor/global/configuration.md",
    summary: "海外锚点后台配置、落地页配置、白名单、素材兜底和发布生效状态。",
    related: ["asset/config-gray-release", "capcut_ug_backend", "锚点不展示排查"],
    x: 1165,
    y: 340,
    size: "sm",
  },
  {
    id: "tiktok_capcut_ug_rpc",
    label: "tiktok_capcut_ug_rpc",
    type: "service",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/tiktok_capcut_ug_rpc",
    summary: "TikTok 侧落地页、模板和锚点配置 RPC。",
    related: ["flow/anchor/global/config_landing", "capcut_ug_http"],
    x: 1215,
    y: 315,
    size: "sm",
  },
  {
    id: "tiktok_capcut_ug_consumer",
    label: "tiktok_capcut_ug_consumer",
    type: "service",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/tiktok_capcut_ug_consumer",
    summary: "消费 TikTok item 变更事件，驱动锚点数据同步和补偿。",
    related: ["flow/anchor/global/item_event_backfill", "asset/async-eventbus"],
    x: 1210,
    y: 690,
    size: "sm",
  },
  {
    id: "tiktok_capcut_ug_mq_consumer",
    label: "tiktok_capcut_ug_mq_consumer",
    type: "service",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "verified",
    path: "code.byted.org/growth/tiktok_capcut_ug_mq_consumer",
    summary: "消费 TikTok 安装、冷启动等 MQ 事件，辅助锚点展示和数据补齐。",
    related: ["flow/anchor/global/item_event_backfill", "asset/async-eventbus"],
    x: 1260,
    y: 735,
    size: "sm",
  },
  {
    id: "item_anchor",
    label: "item_anchor",
    type: "service",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "medium",
    path: "knowledge/registry/repos.yaml",
    summary: "TikTok item anchor 相关服务或模块，支撑 item 维度锚点查询和展示。",
    related: ["flow/anchor/global/item_pack_web_display"],
    x: 960,
    y: 755,
    size: "sm",
  },
  {
    id: "web_pack",
    label: "web-pack",
    type: "frontend_app",
    scene: ["总览", "AI 编码", "服务架构"],
    domain: "overseas-anchor",
    confidence: "medium",
    path: "knowledge/registry/repos.yaml",
    summary: "TikTok Web pack 相关前端资产，用于锚点 Web 展示链路。",
    related: ["flow/anchor/global/item_pack_web_display"],
    x: 1035,
    y: 770,
    size: "sm",
  },
  {
    id: "web_webapi",
    label: "web-webapi",
    type: "service",
    scene: ["总览", "服务架构", "SRE 排障"],
    domain: "overseas-anchor",
    confidence: "medium",
    path: "knowledge/registry/repos.yaml",
    summary: "TikTok Web API 相关服务，参与锚点 Web 展示和数据查询。",
    related: ["flow/anchor/global/item_pack_web_display"],
    x: 1085,
    y: 790,
    size: "sm",
  },
  {
    id: "tiktok_web_core",
    label: "tiktok-web-core",
    type: "frontend_app",
    scene: ["总览", "AI 编码", "服务架构"],
    domain: "overseas-anchor",
    confidence: "medium",
    path: "knowledge/registry/repos.yaml",
    summary: "TikTok Web core 前端资产，承载 Web 端锚点展示条件与页面集成。",
    related: ["flow/anchor/global/item_pack_web_display"],
    x: 1135,
    y: 800,
    size: "sm",
  },
];

export const COMMON_ROUTE_NODE_IDS = [
  "ug-wiki",
  "wiki/index.md",
  "manifest.yaml",
  "wiki/registry/domains.yaml",
  "wiki/registry/repos.yaml",
  "wiki/codebase/frontend-hosts/business-navigation.md",
  "asset/user-view-slices",
  "asset/tracking-datasets",
  "asset/psm-service-map",
  "asset/online-alert-policy",
  "asset/config-gray-release",
  "asset/async-eventbus",
  "asset/contact-map",
] as const;

export const DOMAIN_OPTIONS = DOMAIN_META.map((domain) => ({
  ...domain,
  count:
    domain.id === "horizontal-assets"
      ? COMMON_ROUTE_NODE_IDS.filter((id) => {
        const node = GRAPH_NODES.find((item) => item.id === id);
        return node && !HIDDEN_GRAPH_NODE_TYPES.has(node.type);
      }).length
      : GRAPH_NODES.filter((node) => node.domain === domain.id && !HIDDEN_GRAPH_NODE_TYPES.has(node.type)).length,
}));

export const DOMESTIC_PICK_ROUTE_NODE_IDS = [
  "domestic-influencer",
  "wiki/product/domestic-influencer/README.md",
  "wiki/product/domestic-influencer/glossary.md",
  "wiki/product/domestic-influencer/journeys.md",
  "wiki/product/domestic-influencer/entities.md",
  "wiki/product/domestic-influencer/rules.md",
  "wiki/product/domestic-influencer/flows.md",
  "wiki/product/domestic-influencer/repositories.md",
  "wiki/product/domestic-influencer/errors.md",
  "wiki/product/domestic-influencer/sop.md",
  "wiki/product/domestic-influencer/insights.md",
  "wiki/product/domestic-influencer/references.md",
  "ies/capcut_web_ug",
  "growth/seeyou",
  "jianying_campaign",
  "jianying_ug_rpc",
  "apps/seeyou-social-cn",
  "bgent",
  "AuditPlatformView",
  "routes.tsx",
  "api.ts",
  "bgentClient.ts",
  "influencer_audit",
  "audit_influencer_review/result",
  "Pick2.0 国内达人任务配置",
  "bgent 达人审核入口在 AuditPlatformView",
  "domestic-pick/terms-index",
  "term/pick_task",
  "term/t_resource_item_rel_material",
  "term/pick_conf_settlement_conf",
  "flow/pick/domestic/self_operated_submission",
  "flow/pick/domestic/token_reflow",
  "flow/pick/domestic/agent_bill",
  "flow/pick/domestic/resource_task",
  "jianying_campaign_faas",
  "jianying_ug_backend",
  "owner/domestic-pick/zhangchenyue",
  "owner/domestic-pick/lujian",
] as const;

export const DOMAIN_ROUTE_NODE_IDS: Record<string, readonly string[]> = {
  "horizontal-assets": COMMON_ROUTE_NODE_IDS,
  "domestic-influencer": DOMESTIC_PICK_ROUTE_NODE_IDS,
  "overseas-influencer": [
    "overseas-influencer",
    "wiki/product/overseas-influencer/README.md",
    "ies/capcut_web_ug_os",
    "dreamina-activities/share",
    "即梦海外分享回流在 dreamina-activities/share",
    "term/cc_video_id",
    "term/item_id",
    "term/cpa_cpm",
    "term/growth_program",
    "dataset/global-pick-three-datasets",
    "flow/pick/global/submission",
    "flow/pick/global/review_reward",
    "capcut_campaign",
    "post_incentive_faas",
    "capcut_ug_backend",
  ],
  "domestic-incentive": [
    "domestic-incentive",
    "wiki/product/domestic-incentive/README.md",
    "term/domestic-incentive/task_reward",
    "term/domestic-incentive/fission_invite",
    "flow/incentive/domestic/fission_and_task",
    "flow/incentive/domestic/invite_reward",
    "config/domestic-incentive/reward_config",
    "sop/domestic-incentive/reward_missing",
    "jianying_campaign",
    "jianying_campaign_faas",
    "jianying_ug_rpc",
  ],
  "overseas-incentive": [
    "overseas-incentive",
    "wiki/product/overseas-incentive/README.md",
    "term/overseas-incentive/post_incentive",
    "term/overseas-incentive/leaderboard",
    "flow/incentive/global/post_incentive",
    "flow/incentive/global/leaderboard_refresh",
    "sop/overseas-incentive/reward_config",
    "config/overseas-incentive/reward_config",
    "capcut_campaign",
    "post_incentive_faas",
    "capcut_ug_backend",
    "capcut_ug_rpc",
  ],
  "domestic-anchor": [
    "domestic-anchor",
    "wiki/product/domestic-anchor/README.md",
    "term/anchor_infos",
    "term/domestic-anchor/whitelist",
    "flow/anchor/domestic/query_share",
    "jianying_ug_anchor",
    "config/domestic-anchor/anchor_conf",
    "sop/domestic-anchor/not_display",
    "growth/seeyou",
    "apps/seeyou-social-cn",
  ],
  "overseas-anchor": [
    "overseas-anchor",
    "wiki/product/overseas-anchor/flows.md",
    "wiki/product/overseas-anchor/sop.md",
    "CCUG TT 图模板锚点能力建设",
    "growth/ug-video-fe-os",
    "growth/capcut_ug_http",
    "capcut_anchor_landing_page",
    "capcut_ug_http",
    "cc_ug_proxy_api",
    "capcut_ug_backend",
    "term/overseas-anchor/photo_template_anchor",
    "flow/anchor/global/config_landing",
    "flow/anchor/global/item_pack_web_display",
    "flow/anchor/global/item_event_backfill",
    "config/overseas-anchor/anchor_conf",
    "tiktok_capcut_ug_rpc",
    "tiktok_capcut_ug_consumer",
    "tiktok_capcut_ug_mq_consumer",
    "item_anchor",
    "web_pack",
    "web_webapi",
    "tiktok_web_core",
    "TT 锚点中间页在 capcut_anchor_landing_page",
    "锚点不展示排查",
  ],
};

export const GRAPH_EDGES: GraphEdge[] = [
  { id: "e0-root-1", source: "ug-wiki", target: "domestic-influencer", label: "包含" },
  { id: "e0-root-2", source: "ug-wiki", target: "overseas-anchor", label: "包含" },
  { id: "e0-root-3", source: "ug-wiki", target: "domestic-incentive", label: "包含" },
  { id: "e0-root-4", source: "ug-wiki", target: "manifest.yaml", label: "启动入口" },
  { id: "e0-root-5", source: "ug-wiki", target: "wiki/index.md", label: "导航" },
  { id: "e0-root-6", source: "ug-wiki", target: "wiki/registry/repos.yaml", label: "注册" },
  { id: "e1", source: "domestic-influencer", target: "growth/seeyou", label: "uses_repo" },
  { id: "e2", source: "domestic-influencer", target: "wiki/product/domestic-influencer/repositories.md", label: "documented_by" },
  { id: "e3", source: "growth/seeyou", target: "apps/seeyou-social-cn", label: "contains" },
  { id: "e4", source: "apps/seeyou-social-cn", target: "bgent", label: "contains" },
  { id: "e5", source: "bgent", target: "AuditPlatformView", label: "contains" },
  { id: "e6", source: "routes.tsx", target: "AuditPlatformView", label: "routes_to" },
  { id: "e7", source: "AuditPlatformView", target: "api.ts", label: "uses" },
  { id: "e8", source: "api.ts", target: "influencer_audit", label: "maps_to" },
  { id: "e9", source: "api.ts", target: "bgentClient.ts", label: "uses" },
  { id: "e10", source: "bgentClient.ts", target: "audit_influencer_review/result", label: "calls" },
  { id: "e11", source: "wiki/codebase/frontend-hosts/business-navigation.md", target: "growth/seeyou", label: "references" },
  { id: "e12", source: "overseas-anchor", target: "growth/ug-video-fe-os", label: "implemented_by" },
  { id: "e13", source: "growth/ug-video-fe-os", target: "capcut_anchor_landing_page", label: "contains" },
  { id: "e14", source: "overseas-anchor", target: "wiki/product/overseas-anchor/flows.md", label: "documented_by" },
  { id: "e15", source: "growth/ug-video-fe-os", target: "growth/capcut_ug_http", label: "depends_on" },
  { id: "e16", source: "growth/capcut_ug_http", target: "capcut_ug_http", label: "deploys_as" },
  { id: "e17", source: "growth/capcut_ug_http", target: "cc_ug_proxy_api", label: "calls" },
  { id: "e18", source: "ies/capcut_web_ug_os", target: "dreamina-activities/share", label: "contains" },
  { id: "e19", source: "dreamina-activities/share", target: "即梦海外分享回流在 dreamina-activities/share", label: "supports" },
  { id: "e20", source: "capcut_anchor_landing_page", target: "TT 锚点中间页在 capcut_anchor_landing_page", label: "supports" },
  { id: "e21", source: "AuditPlatformView", target: "bgent 达人审核入口在 AuditPlatformView", label: "supports" },
  { id: "e22", source: "bgentClient.ts", target: "audit_influencer_review/submit", label: "calls" },
  { id: "e23", source: "bgentClient.ts", target: "audit_influencer_review/retry", label: "calls" },
  { id: "e24", source: "bgentClient.ts", target: "audit_influencer_review/update", label: "calls" },
  { id: "e25", source: "domestic-incentive", target: "jianying_campaign", label: "uses_repo" },
  { id: "e26", source: "domestic-influencer", target: "Pick2.0 国内达人任务配置", label: "has_prd" },
  { id: "e27", source: "overseas-anchor", target: "CCUG TT 图模板锚点能力建设", label: "has_prd" },
  { id: "e28", source: "wiki/product/overseas-anchor/sop.md", target: "锚点不展示排查", label: "describes" },
  { id: "e29", source: "manifest.yaml", target: "wiki/index.md", label: "bootstraps" },
  { id: "e30", source: "wiki/registry/repos.yaml", target: "growth/seeyou", label: "registers" },
  { id: "e31", source: "ug-wiki", target: "overseas-influencer", label: "包含" },
  { id: "e32", source: "ug-wiki", target: "overseas-incentive", label: "包含" },
  { id: "e33", source: "ug-wiki", target: "domestic-anchor", label: "包含" },
  { id: "e34", source: "ug-wiki", target: "asset/user-view-slices", label: "organizes" },
  { id: "e35", source: "ug-wiki", target: "asset/tracking-datasets", label: "沉淀" },
  { id: "e36", source: "ug-wiki", target: "asset/psm-service-map", label: "沉淀" },
  { id: "e37", source: "ug-wiki", target: "asset/online-alert-policy", label: "沉淀" },
  { id: "e38", source: "ug-wiki", target: "asset/config-gray-release", label: "沉淀" },
  { id: "e39", source: "ug-wiki", target: "asset/async-eventbus", label: "沉淀" },
  { id: "e40", source: "ug-wiki", target: "asset/contact-map", label: "沉淀" },
  { id: "e41", source: "asset/user-view-slices", target: "domestic-pick/terms-index", label: "抽取" },
  { id: "e42", source: "domestic-influencer", target: "domestic-pick/terms-index", label: "has_terms" },
  { id: "e43", source: "domestic-pick/terms-index", target: "term/pick_task", label: "includes" },
  { id: "e44", source: "domestic-pick/terms-index", target: "term/t_resource_item_rel_material", label: "includes" },
  { id: "e45", source: "domestic-pick/terms-index", target: "term/pick_conf_settlement_conf", label: "includes" },
  { id: "e46", source: "term/pick_task", target: "flow/pick/domestic/resource_task", label: "used_by" },
  { id: "e47", source: "term/t_resource_item_rel_material", target: "flow/pick/domestic/resource_task", label: "stored_in" },
  { id: "e48", source: "domestic-influencer", target: "flow/pick/domestic/self_operated_submission", label: "has_flow" },
  { id: "e49", source: "domestic-influencer", target: "flow/pick/domestic/token_reflow", label: "has_flow" },
  { id: "e50", source: "domestic-influencer", target: "flow/pick/domestic/agent_bill", label: "has_flow" },
  { id: "e51", source: "domestic-influencer", target: "flow/pick/domestic/resource_task", label: "has_flow" },
  { id: "e52", source: "flow/pick/domestic/self_operated_submission", target: "jianying_campaign", label: "entry" },
  { id: "e53", source: "flow/pick/domestic/self_operated_submission", target: "jianying_campaign_faas", label: "async" },
  { id: "e54", source: "flow/pick/domestic/token_reflow", target: "jianying_campaign", label: "entry" },
  { id: "e55", source: "flow/pick/domestic/token_reflow", target: "jianying_ug_rpc", label: "calls" },
  { id: "e56", source: "flow/pick/domestic/agent_bill", target: "jianying_ug_backend", label: "backend" },
  { id: "e57", source: "flow/pick/domestic/agent_bill", target: "jianying_ug_rpc", label: "payout" },
  { id: "e58", source: "flow/pick/domestic/resource_task", target: "jianying_ug_rpc", label: "pack" },
  { id: "e59", source: "jianying_campaign_faas", target: "asset/async-eventbus", label: "uses" },
  { id: "e60", source: "jianying_ug_backend", target: "AuditPlatformView", label: "supports" },
  { id: "e61", source: "asset/contact-map", target: "owner/domestic-pick/zhangchenyue", label: "includes" },
  { id: "e62", source: "asset/contact-map", target: "owner/domestic-pick/lujian", label: "includes" },
  { id: "e63", source: "domestic-influencer", target: "owner/domestic-pick/zhangchenyue", label: "owner" },
  { id: "e64", source: "domestic-influencer", target: "owner/domestic-pick/lujian", label: "owner" },
  { id: "e65", source: "overseas-influencer", target: "wiki/product/overseas-influencer/README.md", label: "documented_by" },
  { id: "e66", source: "overseas-influencer", target: "term/cc_video_id", label: "has_term" },
  { id: "e67", source: "overseas-influencer", target: "term/item_id", label: "has_term" },
  { id: "e68", source: "overseas-influencer", target: "term/cpa_cpm", label: "has_term" },
  { id: "e69", source: "overseas-influencer", target: "term/growth_program", label: "has_term" },
  { id: "e70", source: "overseas-influencer", target: "dataset/global-pick-three-datasets", label: "has_data" },
  { id: "e71", source: "overseas-influencer", target: "flow/pick/global/submission", label: "has_flow" },
  { id: "e72", source: "overseas-influencer", target: "flow/pick/global/review_reward", label: "has_flow" },
  { id: "e73", source: "term/cc_video_id", target: "term/item_id", label: "口径错位" },
  { id: "e74", source: "dataset/global-pick-three-datasets", target: "asset/tracking-datasets", label: "feeds" },
  { id: "e75", source: "flow/pick/global/submission", target: "capcut_campaign", label: "entry" },
  { id: "e76", source: "flow/pick/global/submission", target: "capcut_ug_backend", label: "review" },
  { id: "e77", source: "flow/pick/global/submission", target: "post_incentive_faas", label: "reward" },
  { id: "e78", source: "flow/pick/global/review_reward", target: "dataset/global-pick-three-datasets", label: "checks" },
  { id: "e79", source: "capcut_campaign", target: "ies/capcut_web_ug_os", label: "serves" },
  { id: "e80", source: "capcut_ug_backend", target: "asset/psm-service-map", label: "registered_in" },
  { id: "e81", source: "domestic-incentive", target: "wiki/product/domestic-incentive/README.md", label: "documented_by" },
  { id: "e82", source: "domestic-incentive", target: "term/domestic-incentive/task_reward", label: "has_term" },
  { id: "e83", source: "domestic-incentive", target: "term/domestic-incentive/fission_invite", label: "has_term" },
  { id: "e84", source: "domestic-incentive", target: "flow/incentive/domestic/fission_and_task", label: "has_flow" },
  { id: "e85", source: "domestic-incentive", target: "flow/incentive/domestic/invite_reward", label: "has_flow" },
  { id: "e86", source: "domestic-incentive", target: "config/domestic-incentive/reward_config", label: "has_config" },
  { id: "e87", source: "domestic-incentive", target: "sop/domestic-incentive/reward_missing", label: "has_sop" },
  { id: "e88", source: "flow/incentive/domestic/fission_and_task", target: "jianying_campaign", label: "entry" },
  { id: "e89", source: "flow/incentive/domestic/fission_and_task", target: "jianying_ug_rpc", label: "reward" },
  { id: "e90", source: "flow/incentive/domestic/invite_reward", target: "jianying_campaign_faas", label: "async" },
  { id: "e91", source: "config/domestic-incentive/reward_config", target: "asset/config-gray-release", label: "belongs_to" },
  { id: "e92", source: "sop/domestic-incentive/reward_missing", target: "asset/online-alert-policy", label: "follows" },
  { id: "e93", source: "overseas-incentive", target: "wiki/product/overseas-incentive/README.md", label: "documented_by" },
  { id: "e94", source: "overseas-incentive", target: "term/overseas-incentive/post_incentive", label: "has_term" },
  { id: "e95", source: "overseas-incentive", target: "term/overseas-incentive/leaderboard", label: "has_term" },
  { id: "e96", source: "overseas-incentive", target: "flow/incentive/global/post_incentive", label: "has_flow" },
  { id: "e97", source: "overseas-incentive", target: "flow/incentive/global/leaderboard_refresh", label: "has_flow" },
  { id: "e98", source: "overseas-incentive", target: "sop/overseas-incentive/reward_config", label: "has_sop" },
  { id: "e99", source: "overseas-incentive", target: "config/overseas-incentive/reward_config", label: "has_config" },
  { id: "e100", source: "flow/incentive/global/post_incentive", target: "capcut_campaign", label: "entry" },
  { id: "e101", source: "flow/incentive/global/post_incentive", target: "post_incentive_faas", label: "reward" },
  { id: "e102", source: "flow/incentive/global/post_incentive", target: "capcut_ug_rpc", label: "rpc" },
  { id: "e103", source: "flow/incentive/global/leaderboard_refresh", target: "post_incentive_faas", label: "async" },
  { id: "e104", source: "config/overseas-incentive/reward_config", target: "capcut_ug_backend", label: "managed_by" },
  { id: "e105", source: "post_incentive_faas", target: "asset/async-eventbus", label: "uses" },
  { id: "e106", source: "domestic-anchor", target: "wiki/product/domestic-anchor/README.md", label: "documented_by" },
  { id: "e107", source: "domestic-anchor", target: "term/anchor_infos", label: "has_term" },
  { id: "e108", source: "domestic-anchor", target: "term/domestic-anchor/whitelist", label: "has_term" },
  { id: "e109", source: "domestic-anchor", target: "flow/anchor/domestic/query_share", label: "has_flow" },
  { id: "e110", source: "domestic-anchor", target: "config/domestic-anchor/anchor_conf", label: "has_config" },
  { id: "e111", source: "domestic-anchor", target: "sop/domestic-anchor/not_display", label: "has_sop" },
  { id: "e112", source: "flow/anchor/domestic/query_share", target: "jianying_ug_anchor", label: "service" },
  { id: "e113", source: "flow/anchor/domestic/query_share", target: "growth/seeyou", label: "backend_ui" },
  { id: "e114", source: "term/anchor_infos", target: "asset/tracking-datasets", label: "data_field" },
  { id: "e115", source: "config/domestic-anchor/anchor_conf", target: "asset/config-gray-release", label: "belongs_to" },
  { id: "e116", source: "sop/domestic-anchor/not_display", target: "asset/online-alert-policy", label: "follows" },
  { id: "e117", source: "overseas-anchor", target: "term/overseas-anchor/photo_template_anchor", label: "has_term" },
  { id: "e118", source: "overseas-anchor", target: "flow/anchor/global/config_landing", label: "has_flow" },
  { id: "e119", source: "overseas-anchor", target: "flow/anchor/global/item_pack_web_display", label: "has_flow" },
  { id: "e120", source: "overseas-anchor", target: "flow/anchor/global/item_event_backfill", label: "has_flow" },
  { id: "e121", source: "overseas-anchor", target: "config/overseas-anchor/anchor_conf", label: "has_config" },
  { id: "e122", source: "term/overseas-anchor/photo_template_anchor", target: "CCUG TT 图模板锚点能力建设", label: "described_by" },
  { id: "e123", source: "flow/anchor/global/config_landing", target: "capcut_ug_backend", label: "config" },
  { id: "e124", source: "flow/anchor/global/config_landing", target: "capcut_ug_http", label: "http" },
  { id: "e125", source: "flow/anchor/global/config_landing", target: "capcut_anchor_landing_page", label: "landing" },
  { id: "e126", source: "flow/anchor/global/item_pack_web_display", target: "item_anchor", label: "item" },
  { id: "e127", source: "flow/anchor/global/item_pack_web_display", target: "web_pack", label: "web" },
  { id: "e128", source: "flow/anchor/global/item_pack_web_display", target: "web_webapi", label: "api" },
  { id: "e129", source: "flow/anchor/global/item_pack_web_display", target: "tiktok_web_core", label: "web" },
  { id: "e130", source: "flow/anchor/global/item_event_backfill", target: "tiktok_capcut_ug_consumer", label: "consume" },
  { id: "e131", source: "flow/anchor/global/item_event_backfill", target: "tiktok_capcut_ug_mq_consumer", label: "consume" },
  { id: "e132", source: "tiktok_capcut_ug_consumer", target: "asset/async-eventbus", label: "uses" },
  { id: "e133", source: "tiktok_capcut_ug_mq_consumer", target: "asset/async-eventbus", label: "uses" },
  { id: "e134", source: "config/overseas-anchor/anchor_conf", target: "asset/config-gray-release", label: "belongs_to" },
  { id: "e135", source: "锚点不展示排查", target: "asset/online-alert-policy", label: "follows" },
  { id: "e136", source: "asset/psm-service-map", target: "jianying_campaign", label: "registers" },
  { id: "e137", source: "asset/psm-service-map", target: "jianying_campaign_faas", label: "registers" },
  { id: "e138", source: "asset/psm-service-map", target: "jianying_ug_backend", label: "registers" },
  { id: "e139", source: "asset/psm-service-map", target: "jianying_ug_rpc", label: "registers" },
  { id: "e140", source: "asset/psm-service-map", target: "capcut_campaign", label: "registers" },
  { id: "e141", source: "asset/psm-service-map", target: "capcut_ug_backend", label: "registers" },
  { id: "e142", source: "asset/psm-service-map", target: "capcut_ug_rpc", label: "registers" },
  { id: "e143", source: "asset/psm-service-map", target: "capcut_ug_http", label: "registers" },
];
