# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agentfarm
labels:
  - pairs:
      app: agentfarm-tools
    includeSelectors: true
    includeTemplates: true
resources:
  - ../../base/
patches:
  - path: patches/service-account.yaml
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: agentfarm
  - path: patches/service-account-backend.yaml
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: agentfarm-backend
images:
  - name: ghcr.io/g2crowd/agentfarm-backend-prod
    newTag: "44bc364d"
  - name: ghcr.io/g2crowd/agentfarm-web-prod
    newTag: "44bc364d"
