apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-sa-token
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws-ssm
    kind: ClusterSecretStore
  target:
    name: onepassword-sa-token
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: ONEPASSWORD_SA_TOKEN
      remoteRef:
        key: /agentfarm/development/agentrunner-dev/shared/ONEPASSWORD_SA_TOKEN
