// Package agent — platform_command.go
//
// Base trust allowlist for Multica platform commands.
//
// Every CLI backend (Claude, Codex, future providers) MUST call
// IsTrustedPlatformCommand before routing a Bash tool request through the
// approval flow. Commands that pass this check are auto-allowed without
// user interaction.
//
// Design contract:
//   - This is the SINGLE source of truth for platform command trust.
//   - Individual CLI backends MAY add provider-specific trust rules on top,
//     but MUST NOT skip this base check.
//
// Threat model:
//   These commands are generated by the agent itself, not by untrusted
//   external input. The allowlist's purpose is reducing approval friction,
//   not hardening against adversarial shell injection. We only trust
//   single, direct multica invocations — no pipelines, no chaining,
//   no heredoc structures. Complex commands always require explicit approval.
package agent

import (
	"encoding/json"
	"path/filepath"
	"strings"
)

// IsTrustedPlatformCommand reports whether a Bash command is a trusted
// Multica platform command that can be auto-allowed without user approval.
//
// A command is trusted when:
//  1. It is a single, direct command — no pipelines, no chaining, no heredoc.
//  2. No structural shell escapes (&&, ||, ;, backticks, $(), ${}) in unquoted context.
//  3. No stdout redirection (">") in unquoted context — stderr redirects like "2>/dev/null" are safe.
//  4. The command starts with `multica`, `/path/to/multica`, or is `which multica`.
func IsTrustedPlatformCommand(command string) bool {
	command = strings.TrimSpace(command)
	if command == "" {
		return false
	}

	// Reject multiline commands (heredoc, multiline structures).
	if strings.Contains(command, "\n") {
		return false
	}

	// Quote-aware scan: reject on any unquoted shell metacharacter.
	if hasUnquotedShellStructure(command) {
		return false
	}

	// Verify the command is a direct multica invocation or `which multica`.
	words := strings.Fields(command)
	if len(words) == 0 {
		return false
	}

	executable := words[0]

	// `which multica` is trusted.
	if executable == "which" && len(words) == 2 && words[1] == "multica" {
		return true
	}

	// Direct `multica` or `/path/to/multica` invocation.
	if executable == "multica" || filepath.Base(executable) == "multica" {
		return true
	}

	return false
}

// hasUnquotedShellStructure performs a quote-aware scan of a single-line
// command. Returns true if any unquoted shell metacharacter is found:
// pipe (|), chain (&&, ||, ;), substitution ($(), ${}), backtick,
// or stdout redirect (>).
func hasUnquotedShellStructure(command string) bool {
	var (
		inSingle bool
		inDouble bool
		escaped  bool
	)

	for i := 0; i < len(command); i++ {
		ch := command[i]

		if escaped {
			escaped = false
			continue
		}
		if ch == '\\' && !inSingle {
			escaped = true
			continue
		}

		if ch == '\'' && !inDouble {
			inSingle = !inSingle
			continue
		}
		if ch == '"' && !inSingle {
			inDouble = !inDouble
			continue
		}

		if inSingle || inDouble {
			continue
		}

		// Unquoted context: reject on any structural metacharacter.
		switch ch {
		case '|':
			return true
		case '&':
			if i+1 < len(command) && command[i+1] == '&' {
				return true
			}
		case ';':
			return true
		case '`':
			return true
		case '$':
			if i+1 < len(command) && (command[i+1] == '(' || command[i+1] == '{') {
				return true
			}
		case '>':
			// Allow stderr redirect: "2>/dev/null" or "2> /dev/null".
			if i > 0 && command[i-1] == '2' {
				continue
			}
			return true
		}
	}

	return false
}

// isTrustedPlatformCommand is the package-internal alias.
// Kept for backward compatibility with existing call sites.
func isTrustedPlatformCommand(command string) bool {
	return IsTrustedPlatformCommand(command)
}

func trustedPlatformCommandFromInput(input map[string]any) string {
	if len(input) == 0 {
		return ""
	}

	if command := stringField(input, "command", "cmd", "script"); command != "" {
		return command
	}

	for _, key := range []string{"args", "arguments", "input", "payload", "tool_input", "params"} {
		nested := nestedInputRecord(input[key])
		if nested == nil {
			continue
		}
		if command := trustedPlatformCommandFromInput(nested); command != "" {
			return command
		}
	}

	return ""
}

func nestedInputRecord(value any) map[string]any {
	if value == nil {
		return nil
	}
	record, ok := value.(map[string]any)
	if ok {
		return record
	}
	raw, ok := value.(string)
	if !ok {
		return nil
	}
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return nil
	}
	var parsed map[string]any
	if err := json.Unmarshal([]byte(raw), &parsed); err != nil {
		return nil
	}
	return parsed
}

func stringField(record map[string]any, keys ...string) string {
	for _, key := range keys {
		value, _ := record[key].(string)
		if strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}
