// Package agent — platform_command.go
//
// Base trust allowlist for Multica platform commands.
//
// Every CLI backend (Claude, Codex, future providers) MUST call
// IsTrustedPlatformCommand before routing a Bash tool request through the
// approval flow. Commands that pass this check are auto-allowed without
// user interaction.
//
// Design contract:
//   - This is the SINGLE source of truth for platform command trust.
//   - Individual CLI backends MAY add provider-specific trust rules on top,
//     but MUST NOT skip this base check.
//   - If a new read-only pipe utility is commonly used with `multica` CLI
//     commands, add it to safePipeCommands below.
//
// Threat model:
//   These commands are generated by the agent itself, not by untrusted
//   external input. The allowlist's purpose is reducing approval friction,
//   not hardening against adversarial shell injection. We therefore only
//   block structural shell escapes (command chaining, substitution, stdout
//   redirection) and verify that every pipeline segment starts with a
//   known-safe executable. Argument content is NOT inspected — backslashes,
//   unicode, quotes, etc. are all legitimate in multica CLI arguments.
package agent

import (
	"path/filepath"
	"strings"
)

// safePipeCommands are read-only utilities that are safe to use in a pipeline
// with multica commands. They cannot modify the filesystem or exfiltrate data.
var safePipeCommands = map[string]bool{
	"cat":    true,
	"printf": true,
	"echo":   true,
	"head":   true,
	"tail":   true,
	"grep":   true,
	"wc":     true,
	"sort":   true,
	"tr":     true,
	"cut":    true,
	"sed":    true,
	"awk":    true,
	"jq":     true,
	"tee":    false, // writes to file — NOT safe
}

// shellEscapePatterns are structural shell constructs that allow chaining
// or injecting additional commands. These are the actual threats — NOT
// characters that happen to appear in argument values.
var shellEscapePatterns = []string{
	"&&",  // command chaining
	"||",  // conditional chaining
	";",   // command separator
	"`",   // command substitution (backtick)
	"$(",  // command substitution (modern)
	"${",  // variable expansion
}

// IsTrustedPlatformCommand reports whether a Bash command is a trusted
// Multica platform command that can be auto-allowed without user approval.
//
// A command is trusted when:
//  1. No structural shell escapes (&&, ||, ;, backticks, $(), ${}).
//  2. No stdout redirection (">") — stderr redirects like "2>/dev/null" are safe.
//  3. Every pipeline segment starts with either `multica` or a known safe utility.
//  4. At least one segment is a `multica` invocation.
func IsTrustedPlatformCommand(command string) bool {
	command = strings.TrimSpace(command)
	if command == "" {
		return false
	}

	// Split on pipe and verify each segment.
	segments := strings.Split(command, "|")
	foundMultica := false
	for _, segment := range segments {
		// Take first line only — heredoc body is safe content and must
		// not be scanned for shell metacharacters.
		header := strings.TrimSpace(strings.SplitN(segment, "\n", 2)[0])
		if header == "" {
			continue
		}

		// 1. Block structural shell escapes in this segment's header.
		for _, pat := range shellEscapePatterns {
			if strings.Contains(header, pat) {
				return false
			}
		}

		// 2. Block stdout redirection while allowing stderr-to-devnull.
		if hasStdoutRedirect(header) {
			return false
		}

		// 3. Verify the executable is known-safe.
		words := strings.Fields(header)
		if len(words) == 0 {
			continue
		}
		executable := words[0]
		if executable == "which" && len(words) == 2 && words[1] == "multica" {
			foundMultica = true
			continue
		}
		if safePipeCommands[executable] {
			continue
		}
		if executable == "multica" || filepath.Base(executable) == "multica" {
			foundMultica = true
			continue
		}
		return false
	}
	return foundMultica
}

// hasStdoutRedirect returns true if the command contains a stdout redirect
// (e.g. "> /tmp/out", "1> file"). Returns false for stderr redirects
// ("2>/dev/null", "2> /dev/null") which are harmless.
func hasStdoutRedirect(cmd string) bool {
	for i, ch := range cmd {
		if ch != '>' {
			continue
		}
		// Check character before '>': if it's '2' this is stderr redirect.
		if i > 0 && cmd[i-1] == '2' {
			continue
		}
		return true
	}
	return false
}

// isTrustedPlatformCommand is the package-internal alias.
// Kept for backward compatibility with existing call sites.
func isTrustedPlatformCommand(command string) bool {
	return IsTrustedPlatformCommand(command)
}
