#!/usr/bin/env bash
# Shared self-host URL and port derivation. Source after loading .env.

BACKEND_PORT="${BACKEND_PORT:-${API_PORT:-${SERVER_PORT:-${PORT:-8080}}}}"
SERVER_PORT="${SERVER_PORT:-${BACKEND_PORT}}"
PORT="${BACKEND_PORT}"
FRONTEND_PORT="${FRONTEND_PORT:-3000}"
BIND_HOST="${BIND_HOST:-127.0.0.1}"

case "$BIND_HOST" in
  ""|"127.0.0.1"|"::1") SELFHOST_URL_HOST="localhost" ;;
  "0.0.0.0") SELFHOST_URL_HOST="localhost" ;;
  *) SELFHOST_URL_HOST="$BIND_HOST" ;;
esac

FRONTEND_ORIGIN="${FRONTEND_ORIGIN:-http://${SELFHOST_URL_HOST}:${FRONTEND_PORT}}"
if [ -z "${CORS_ALLOWED_ORIGINS:-}" ] && [ "$SELFHOST_URL_HOST" != "localhost" ]; then
  CORS_ALLOWED_ORIGINS="$FRONTEND_ORIGIN"
fi
MULTICA_APP_URL="${MULTICA_APP_URL:-${FRONTEND_ORIGIN}}"
GOOGLE_REDIRECT_URI="${GOOGLE_REDIRECT_URI:-${FRONTEND_ORIGIN}/auth/callback}"
MULTICA_SERVER_URL="${MULTICA_SERVER_URL:-ws://${SELFHOST_URL_HOST}:${BACKEND_PORT}/ws}"
LOCAL_UPLOAD_BASE_URL="${LOCAL_UPLOAD_BASE_URL:-http://${SELFHOST_URL_HOST}:${BACKEND_PORT}}"
BACKEND_BASE_URL="${BACKEND_BASE_URL:-http://${SELFHOST_URL_HOST}:${BACKEND_PORT}}"
FRONTEND_BASE_URL="${FRONTEND_BASE_URL:-${FRONTEND_ORIGIN}}"
PLAYWRIGHT_BASE_URL="${PLAYWRIGHT_BASE_URL:-${FRONTEND_ORIGIN}}"

export BACKEND_PORT SERVER_PORT PORT FRONTEND_PORT BIND_HOST SELFHOST_URL_HOST
export FRONTEND_ORIGIN CORS_ALLOWED_ORIGINS MULTICA_APP_URL GOOGLE_REDIRECT_URI
export MULTICA_SERVER_URL LOCAL_UPLOAD_BASE_URL BACKEND_BASE_URL FRONTEND_BASE_URL
export PLAYWRIGHT_BASE_URL
