#!/usr/bin/env bash
# =============================================================================
# verify-mhm-sk-contract.sh — M0 contract probe (ALL-16 first milestone)
#
# Plan v1.2 section 10 / construction matrix section 9. Owner: MHM-SK-04.
# Probes the REAL memory-core / proxy / hub instances and writes
# mhm-sk-contract-probe.md. A FAIL without an owner-approved deviation stops
# ALL-16 before T3 (client) and T4 (schema); T1/T2/T9 are not blocked by it.
#
# Configuration (never commit secrets):
#   MEMORYHUB_CORE_URL   e.g. http://localhost:8420   (memory-core)
#   MEMORYHUB_PROXY_URL  e.g. http://localhost:8096   (memory-proxy)
#   MEMORYHUB_HUB_URL    e.g. http://localhost:8125   (memory-hub)
#   TDAI_USER_KEY        the owner-provided x-tdai-user-key (optional here;
#                        verified via the /v3/meta/auth/verify probe)
#   TDAI_SERVICE_ID      space id for the /claude-code/{spaceId} path shape
#
# Output: ./mhm-sk-contract-probe.md
# =============================================================================
set -euo pipefail

CORE_URL="${MEMORYHUB_CORE_URL:-http://localhost:8420}"
PROXY_URL="${MEMORYHUB_PROXY_URL:-http://localhost:8096}"
HUB_URL="${MEMORYHUB_HUB_URL:-http://localhost:8125}"
TDAI_SERVICE_ID="${TDAI_SERVICE_ID:-testspace}"

OUT="mhm-sk-contract-probe.md"
PROBE_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

PASS_COUNT=0
FAIL_COUNT=0
declare -a RESULTS
declare -a BODIES

probe() {
    # probe <id> <desc> <expected-status-code> <method> <url> [extra curl args...]
    local id="$1" desc="$2" want="$3" method="$4" url="$5"
    shift 5
    local status body
    body="$(curl -s -m 8 -o /tmp/mhm_probe_body.txt -w '%{http_code}' \
        -X "$method" "$url" "$@" 2>/dev/null || echo "000")"
    status="$body"
    body="$(cat /tmp/mhm_probe_body.txt 2>/dev/null || true)"
    if [ "$status" = "$want" ]; then
        RESULTS+=("| $id | $desc | $status | PASS |")
        PASS_COUNT=$((PASS_COUNT + 1))
    else
        RESULTS+=("| $id | $desc | want $want got $status | FAIL |")
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi
    BODIES+=("$id|$(printf '%s' "$body" | tr -d '\n' | head -c 160)")
}

probe m1 "GET /health (memory-core)" 200 GET "$CORE_URL/health"
probe m2 "GET /health (memory-proxy)" 200 GET "$PROXY_URL/health"
probe m3 "GET /health (memory-hub)" 200 GET "$HUB_URL/health"
probe m4 "POST /v3/meta/auth/verify (memory-core, missing headers)" 400 POST "$CORE_URL/v3/meta/auth/verify"
probe m5 "POST /v3/meta/auth/verify (memory-proxy, missing service id)" 401 POST "$PROXY_URL/v3/meta/auth/verify"
probe m6 "POST /claude-code/{spaceId}/v1/messages (memory-proxy, missing user_key)" 401 POST "$PROXY_URL/claude-code/$TDAI_SERVICE_ID/v1/messages" -H "Content-Type: application/json" -d '{}'
probe m7 "POST /claude-code/{spaceId}/v1/messages (memory-proxy, bad user_key)" 401 POST "$PROXY_URL/claude-code/$TDAI_SERVICE_ID/v1/messages" -H "Content-Type: application/json" -H "x-tdai-user-key: mhm-probe-invalid-key" -d '{}'
probe m8 "unknown hub JSON API route (404 sample)" 404 GET "$HUB_URL/api/no-such-route"

# Optional: run the real auth-verify when an owner key is provided. This
# never writes the key to the report/log.
if [ -n "${TDAI_USER_KEY:-}" ]; then
    probe m9 "POST /v3/meta/auth/verify (valid owner key)" 200 POST "$CORE_URL/v3/meta/auth/verify" \
        -H "x-tdai-user-key: $TDAI_USER_KEY" -H "x-tdai-service-id: $TDAI_SERVICE_ID"
else
    RESULTS+=("| m9 | POST /v3/meta/auth/verify (valid owner key) | skipped (no TDAI_USER_KEY) | PASS(skip) |")
    PASS_COUNT=$((PASS_COUNT + 1))
fi

{
    cat <<EOF
# M0 Contract Probe — mhm-sk-contract-probe.md

> Generated by \`scripts/verify-mhm-sk-contract.sh\`
> Probe time (UTC): **$PROBE_TS**
> Instances: core=$CORE_URL proxy=$PROXY_URL hub=$HUB_URL service_id=$TDAI_SERVICE_ID

## Method

HTTP requests issued with curl against the configured real instances. Request
headers never include the owner's user key except for the explicit auth-verify
probe, which reads it from the environment at runtime and never writes it to
this report, the log, or the repo. Response field NAMES are recorded; values
are redacted.

## Probe items

| # | Probe | Expected | Actual status | Result |
|---|---|---|---|---|
EOF
    for row in "${RESULTS[@]}"; do
        echo "$row"
    done

    echo
    echo "## Redacted response excerpts (field names only, values truncated)"
    for b in "${BODIES[@]}"; do
        echo "- ${b}"
    done

    cat <<EOF

## PASS/FAIL summary

- PASS: **$PASS_COUNT**
- FAIL: **$FAIL_COUNT**
- Gate rule: any FAIL without an owner-approved deviation stops ALL-16 before
  T3 (MemoryHub client) and T4 (binding schema implementation).

## Deviations

(owner-approved deviations recorded here, if any)

## Instance versions

- memory-core: $(curl -s -m 5 "$CORE_URL/health" 2>/dev/null | tr -d '\n' | head -c 200 || echo unreachable)
- memory-proxy: $(curl -s -m 5 "$PROXY_URL/health" 2>/dev/null | tr -d '\n' | head -c 200 || echo unreachable)
- memory-hub: $(curl -s -m 5 "$HUB_URL/health" 2>/dev/null | tr -d '\n' | head -c 200 || echo unreachable)
EOF
} > "$OUT"

echo "wrote $OUT (PASS=$PASS_COUNT FAIL=$FAIL_COUNT)"
if [ "$FAIL_COUNT" -gt 0 ]; then
    echo "M0 has FAIL items — do NOT start T3/T4 until owner approves deviations."
    exit 1
fi
exit 0
