// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelMember = `-- name: AddChannelMember :one
INSERT INTO channel_members (
    channel_id, member_id
) VALUES (
    $1, $2
)
RETURNING channel_id, member_id, joined_at
`

type AddChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	MemberID  pgtype.UUID `json:"member_id"`
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) (ChannelMember, error) {
	row := q.db.QueryRow(ctx, addChannelMember, arg.ChannelID, arg.MemberID)
	var i ChannelMember
	err := row.Scan(&i.ChannelID, &i.MemberID, &i.JoinedAt)
	return i, err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (
    workspace_id, name, description, is_private, created_by
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, workspace_id, name, description, is_private, created_by, created_at
`

type CreateChannelParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsPrivate   bool        `json:"is_private"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.IsPrivate,
		arg.CreatedBy,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createChannelMessage = `-- name: CreateChannelMessage :one
INSERT INTO channel_messages (
    channel_id, author_id, content, parent_id
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, channel_id, author_id, content, parent_id, edited_at, created_at
`

type CreateChannelMessageParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	AuthorID  pgtype.UUID `json:"author_id"`
	Content   string      `json:"content"`
	ParentID  pgtype.UUID `json:"parent_id"`
}

func (q *Queries) CreateChannelMessage(ctx context.Context, arg CreateChannelMessageParams) (ChannelMessage, error) {
	row := q.db.QueryRow(ctx, createChannelMessage,
		arg.ChannelID,
		arg.AuthorID,
		arg.Content,
		arg.ParentID,
	)
	var i ChannelMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.ParentID,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const deleteChannelMessage = `-- name: DeleteChannelMessage :exec
DELETE FROM channel_messages WHERE id = $1
`

func (q *Queries) DeleteChannelMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannelMessage, id)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, workspace_id, name, description, is_private, created_by, created_at FROM channels WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChannel(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChannelMessage = `-- name: GetChannelMessage :one
SELECT id, channel_id, author_id, content, parent_id, edited_at, created_at FROM channel_messages WHERE id = $1 LIMIT 1
`

func (q *Queries) GetChannelMessage(ctx context.Context, id pgtype.UUID) (ChannelMessage, error) {
	row := q.db.QueryRow(ctx, getChannelMessage, id)
	var i ChannelMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.ParentID,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listChannelMembers = `-- name: ListChannelMembers :many
SELECT m.id, m.workspace_id, m.user_id, m.role, m.created_at, m.updated_at, cm.joined_at
FROM channel_members cm
JOIN members m ON m.id = cm.member_id
WHERE cm.channel_id = $1
`

type ListChannelMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListChannelMembers(ctx context.Context, channelID pgtype.UUID) ([]ListChannelMembersRow, error) {
	rows, err := q.db.Query(ctx, listChannelMembers, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelMembersRow
	for rows.Next() {
		var i ListChannelMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMessageReplies = `-- name: ListChannelMessageReplies :many
SELECT id, channel_id, author_id, content, parent_id, edited_at, created_at FROM channel_messages
WHERE parent_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListChannelMessageReplies(ctx context.Context, parentID pgtype.UUID) ([]ChannelMessage, error) {
	rows, err := q.db.Query(ctx, listChannelMessageReplies, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMessage
	for rows.Next() {
		var i ChannelMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.ParentID,
			&i.EditedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelMessages = `-- name: ListChannelMessages :many
SELECT id, channel_id, author_id, content, parent_id, edited_at, created_at FROM channel_messages
WHERE channel_id = $1 AND parent_id IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChannelMessagesParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]ChannelMessage, error) {
	rows, err := q.db.Query(ctx, listChannelMessages, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMessage
	for rows.Next() {
		var i ChannelMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Content,
			&i.ParentID,
			&i.EditedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannels = `-- name: ListChannels :many
SELECT id, workspace_id, name, description, is_private, created_by, created_at FROM channels
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListChannels(ctx context.Context, workspaceID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChannelMember = `-- name: RemoveChannelMember :exec
DELETE FROM channel_members WHERE channel_id = $1 AND member_id = $2
`

type RemoveChannelMemberParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	MemberID  pgtype.UUID `json:"member_id"`
}

func (q *Queries) RemoveChannelMember(ctx context.Context, arg RemoveChannelMemberParams) error {
	_, err := q.db.Exec(ctx, removeChannelMember, arg.ChannelID, arg.MemberID)
	return err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    is_private = COALESCE($4, is_private)
WHERE id = $1
RETURNING id, workspace_id, name, description, is_private, created_by, created_at
`

type UpdateChannelParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	IsPrivate   pgtype.Bool `json:"is_private"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPrivate,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const updateChannelMessage = `-- name: UpdateChannelMessage :one
UPDATE channel_messages
SET
    content = COALESCE($2, content),
    edited_at = now()
WHERE id = $1
RETURNING id, channel_id, author_id, content, parent_id, edited_at, created_at
`

type UpdateChannelMessageParams struct {
	ID      pgtype.UUID `json:"id"`
	Content pgtype.Text `json:"content"`
}

func (q *Queries) UpdateChannelMessage(ctx context.Context, arg UpdateChannelMessageParams) (ChannelMessage, error) {
	row := q.db.QueryRow(ctx, updateChannelMessage, arg.ID, arg.Content)
	var i ChannelMessage
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Content,
		&i.ParentID,
		&i.EditedAt,
		&i.CreatedAt,
	)
	return i, err
}
