ALTER TABLE agent DROP COLUMN IF EXISTS mcp_config;
ALTER TABLE agent DROP COLUMN IF EXISTS custom_env;
ALTER TABLE agent DROP COLUMN IF EXISTS custom_args;
ALTER TABLE agent DROP COLUMN IF EXISTS thinking_level;
ALTER TABLE agent DROP COLUMN IF EXISTS model;
