ALTER TABLE agent ADD COLUMN model TEXT;
ALTER TABLE agent ADD COLUMN thinking_level TEXT;
ALTER TABLE agent ADD COLUMN custom_args JSONB NOT NULL DEFAULT '[]';
ALTER TABLE agent ADD COLUMN custom_env JSONB NOT NULL DEFAULT '{}';
ALTER TABLE agent ADD COLUMN mcp_config JSONB;
