ALTER TABLE feishu_project_sync_run
    ADD COLUMN IF NOT EXISTS total_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS processed_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_page INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS current_type TEXT NOT NULL DEFAULT '';

