DROP INDEX IF EXISTS idx_issue_sprint;
DROP INDEX IF EXISTS idx_issue_epic;
ALTER TABLE issue DROP COLUMN IF EXISTS sprint_id;
ALTER TABLE issue DROP COLUMN IF EXISTS epic_id;
DROP TABLE IF EXISTS sprint;
DROP TABLE IF EXISTS epic;
