CREATE TABLE corpus_transfer (
    id                            UUID NOT NULL,
    workspace_id                  UUID NOT NULL,
    actor_id                      UUID NOT NULL,
    idempotency_key               TEXT NOT NULL CHECK (char_length(idempotency_key) BETWEEN 1 AND 128),
    object_key                    TEXT NOT NULL CHECK (char_length(object_key) BETWEEN 1 AND 1024),
    manifest                      JSONB NOT NULL CHECK (jsonb_typeof(manifest) = 'object'),
    manifest_sha256               TEXT NOT NULL CHECK (manifest_sha256 ~ '^[0-9a-f]{64}$'),
    expected_size_bytes           BIGINT NOT NULL CHECK (expected_size_bytes BETWEEN 1 AND 2147483648),
    expected_sha256               TEXT NOT NULL CHECK (expected_sha256 ~ '^[0-9a-f]{64}$'),
    state                         TEXT NOT NULL DEFAULT 'created'
        CHECK (state IN ('created', 'uploading', 'uploaded', 'verifying', 'confirmed', 'acked', 'failed', 'expired')),
    verification_token            UUID,
    verification_lease_expires_at TIMESTAMPTZ,
    verified_size_bytes           BIGINT CHECK (verified_size_bytes >= 0),
    verified_sha256               TEXT CHECK (verified_sha256 ~ '^[0-9a-f]{64}$'),
    failure_code                  TEXT CHECK (char_length(failure_code) BETWEEN 1 AND 128),
    expires_at                    TIMESTAMPTZ NOT NULL,
    upload_started_at             TIMESTAMPTZ,
    uploaded_at                   TIMESTAMPTZ,
    verification_started_at       TIMESTAMPTZ,
    confirmed_at                  TIMESTAMPTZ,
    failed_at                     TIMESTAMPTZ,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK ((verified_size_bytes IS NULL) = (verified_sha256 IS NULL)),
    CHECK ((state IN ('confirmed', 'acked')) = (verified_size_bytes IS NOT NULL AND verified_sha256 IS NOT NULL)),
    CHECK ((verification_token IS NULL) = (verification_lease_expires_at IS NULL)),
    CHECK ((state = 'verifying') = (verification_token IS NOT NULL AND verification_lease_expires_at IS NOT NULL)),
    CHECK ((state = 'failed') = (failure_code IS NOT NULL))
);
