CREATE TABLE agent_terminal_session (
    id UUID PRIMARY KEY,
    workspace_id UUID NOT NULL,
    issue_id UUID,
    task_id UUID NOT NULL,
    agent_id UUID NOT NULL,
    runtime_id UUID NOT NULL,
    daemon_id UUID NOT NULL,
    generation INTEGER NOT NULL DEFAULT 1 CHECK (generation > 0),
    protocol_version INTEGER NOT NULL DEFAULT 1 CHECK (protocol_version > 0),
    provider TEXT NOT NULL,
    terminal_mode TEXT NOT NULL DEFAULT 'pty' CHECK (terminal_mode IN ('pty')),
    process_state TEXT NOT NULL DEFAULT 'running' CHECK (process_state IN ('starting', 'running', 'reconnecting', 'exited', 'failed')),
    structured_observation TEXT NOT NULL DEFAULT 'unavailable' CHECK (structured_observation IN ('available', 'stale', 'unavailable')),
    cols INTEGER NOT NULL DEFAULT 120 CHECK (cols BETWEEN 20 AND 400),
    rows INTEGER NOT NULL DEFAULT 32 CHECK (rows BETWEEN 5 AND 200),
    output_seq BIGINT NOT NULL DEFAULT 0 CHECK (output_seq >= 0),
    provider_session_id TEXT,
    exit_code INTEGER,
    exit_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    exited_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
