-- ExecutionLedger: frozen execution identity snapshot plus lineage and
-- review lineage fields. PK on execution_id arrives via index + constraint.
CREATE TABLE execution_ledger (
    execution_id UUID NOT NULL DEFAULT gen_random_uuid(),
    attempt INTEGER NOT NULL DEFAULT 1,
    task_id UUID NOT NULL,
    task_version INTEGER NOT NULL DEFAULT 1,
    workspace_id UUID NOT NULL,
    project_id UUID,
    scope_kind TEXT NOT NULL CHECK (scope_kind IN ('workspace', 'project')),
    issue_id UUID,
    run_id TEXT NOT NULL,
    agent_id UUID NOT NULL,
    runtime_id UUID NOT NULL,
    model TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'queued' CHECK (state IN ('queued', 'claimed', 'running', 'completed', 'failed', 'cancelled', 'dead_letter')),
    lease_owner TEXT,
    lease_expires_at TIMESTAMPTZ,
    version INTEGER NOT NULL DEFAULT 1,
    retry_of UUID,
    rerun_of UUID,
    delegated_from UUID,
    handoff_of UUID,
    origin TEXT,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    stop_reason TEXT,
    idempotency_key TEXT NOT NULL,
    merged_from UUID[] NOT NULL DEFAULT '{}',
    review_policy TEXT NOT NULL DEFAULT 'none' CHECK (review_policy IN ('none', 'independent')),
    reviewer_agent_id UUID,
    review_of_execution_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
