import { useState } from "react";
import type { UsageExplorer } from "./api";

export function UsageExplorerPanel({data,onSelect}:{data:UsageExplorer;onSelect:(dimension:string,value:string,mode:"include"|"exclude")=>void}){
 const [open,setOpen]=useState<UsageExplorer["runs"][number]|null>(null);
 return <div className="space-y-4">
  <section aria-label="Usage summary" className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border bg-border lg:grid-cols-4">
   {[['Runs',data.summary.runs],['Tokens',data.summary.tokens.toLocaleString()],['Actual gateway cost',`$${(data.summary.actual_cost_cents/100).toFixed(2)}`],['Missing cost data',data.summary.missing_cost_runs]].map(([label,value])=><div key={label} className="bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-xl tabular-nums">{value}</p></div>)}
  </section>
  <section aria-label="Universal filters" className="rounded-lg border bg-card p-4"><h2 className="text-sm font-medium">Filter every result</h2><p className="mb-3 text-xs text-muted-foreground">Include or exclude any value. All totals, savings and runs update together.</p><div className="flex flex-wrap gap-2">{Object.entries(data.facets).flatMap(([dimension,items])=>items.map(item=><span key={`${dimension}:${item.value}`} className="inline-flex items-center rounded-md border bg-background"><span className="px-2 text-xs">{dimension}: {item.value} · {item.count}</span><button aria-label={`Include ${dimension} ${item.value}`} className="border-l px-2 py-1 text-xs hover:bg-muted" onClick={()=>onSelect(dimension,item.value,"include")}>+</button><button aria-label={`Exclude ${dimension} ${item.value}`} className="border-l border-dashed px-2 py-1 text-xs hover:bg-muted" onClick={()=>onSelect(dimension,item.value,"exclude")}>−</button></span>))}</div></section>
  <section aria-label="Measured savings" className="rounded-lg border bg-card p-4"><h2 className="text-sm font-medium">Measured savings</h2>{data.savings.length===0?<p className="mt-2 text-xs text-muted-foreground">Measurement unavailable for this period.</p>:<div className="mt-2 grid gap-2 sm:grid-cols-2">{data.savings.map(s=><button key={s.type} aria-label={`Filter by saving ${s.type}`} onClick={()=>onSelect('saving',s.type,'include')} className="rounded-md border p-3 text-left hover:bg-muted"><p className="text-sm font-medium">{s.type}</p><p className="text-xs text-muted-foreground">{s.affected_runs} runs · {s.saved_units.toLocaleString()} units · ${(s.saved_cents/100).toFixed(2)} saved</p></button>)}</div>}</section>
  <section aria-label="Matching runs" className="overflow-hidden rounded-lg border bg-card"><header className="border-b px-4 py-3"><h2 className="text-sm font-medium">Matching runs</h2><p className="text-xs text-muted-foreground">{data.total} total</p></header><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-muted-foreground"><tr>{['Time','Agent','Runtime','Model','Provider','Status','Tokens','Cost'].map(h=><th key={h} className="px-3 py-2 font-medium">{h}</th>)}</tr></thead><tbody>{data.runs.map(r=><tr key={r.id} className="border-t"><td className="px-3 py-2"><button aria-label={`Open run ${r.id}`} className="underline-offset-2 hover:underline" onClick={()=>setOpen(r)}>{new Date(r.created_at).toLocaleString()}</button></td><td className="px-3">{r.agent}</td><td className="px-3">{r.runtime}</td><td className="px-3">{r.model}</td><td className="px-3">{r.provider}</td><td className="px-3">{r.status}</td><td className="px-3 font-mono">{r.input_tokens+r.output_tokens}</td><td className="px-3">{r.cost_kind==='actual'?`$${(r.cost_cents/100).toFixed(2)} actual`:'Missing'}</td></tr>)}</tbody></table></div></section>
  {open&&<aside aria-label="Run details" className="rounded-lg border bg-card p-4"><div className="flex justify-between"><h2 className="text-sm font-medium">Run details</h2><button onClick={()=>setOpen(null)} aria-label="Close run details">×</button></div><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><dt className="text-muted-foreground">Run</dt><dd className="font-mono">{open.id}</dd><dt className="text-muted-foreground">Project</dt><dd>{open.project}</dd><dt className="text-muted-foreground">Trigger</dt><dd>{open.trigger}</dd><dt className="text-muted-foreground">Duration</dt><dd>{open.duration_seconds}s</dd></dl>{open.trace_url&&<a className="mt-3 inline-block text-xs underline" href={open.trace_url}>Open Trace</a>}</aside>}
 </div>
}
