package handler

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/binary"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"regexp"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"github.com/golang-jwt/jwt/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/multica-ai/multica/server/internal/auth"
	db "github.com/multica-ai/multica/server/pkg/db/generated"
)

const (
	localUserEmail          = "chairman@lifeos.invalid"
	localUserName           = "陈星耀"
	localWorkspaceName      = "LifeOS"
	localWorkspaceSlug      = "lifeos"
	localWorkspaceBrief     = "AI 星耀的本地日常工作执行看板。"
	localLifeOSCEOAgentName = "AI 星耀"
	localPasswordIterations = 600_000
	localMaxFailedAttempts  = 5
	localLockDuration       = 15 * time.Minute
	localAuthBodyLimit      = 16 << 10
)

var localUsernamePattern = regexp.MustCompile(`^[A-Za-z0-9._-]{3,64}$`)

type LocalLoginResponse struct {
	Token     string              `json:"token"`
	User      UserResponse        `json:"user"`
	Workspace WorkspaceResponse   `json:"workspace"`
	Actor     *LocalActorResponse `json:"actor,omitempty"`
}

type LocalCredentialRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LocalAutomationRequest struct {
	AgentName string `json:"agent_name,omitempty"`
}

type LocalActorResponse struct {
	Type string `json:"type"`
	ID   string `json:"id"`
	Name string `json:"name"`
}

type localCredential struct {
	Username    string
	Salt        []byte
	Hash        []byte
	Iterations  int
	Failures    int
	LockedUntil pgtype.Timestamptz
}

// LocalSetup establishes the only human credential. It is intentionally a
// one-time operation: later password changes require an explicit local admin
// flow rather than reopening signup.
func (h *Handler) LocalSetup(w http.ResponseWriter, r *http.Request) {
	if !h.cfg.LocalMode {
		http.NotFound(w, r)
		return
	}
	req, ok := decodeLocalCredentialRequest(w, r)
	if !ok {
		return
	}
	username, message := validateLocalCredential(req.Username, req.Password)
	if message != "" {
		writeError(w, http.StatusBadRequest, message)
		return
	}
	salt := make([]byte, 32)
	if _, err := rand.Read(salt); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to create local credential")
		return
	}
	digest := deriveLocalPassword(req.Password, salt, localPasswordIterations)
	command, err := h.DB.Exec(
		r.Context(),
		`INSERT INTO lifeos_local_credential(
			singleton, username, password_salt, password_hash, password_iterations
		 ) VALUES (1, $1, $2, $3, $4)
		 ON CONFLICT (singleton) DO NOTHING`,
		username, salt, digest, localPasswordIterations,
	)
	if err != nil {
		slog.Error("local credential setup failed", "error", err)
		writeError(w, http.StatusInternalServerError, "failed to create local credential")
		return
	}
	if command.RowsAffected() != 1 {
		writeError(w, http.StatusConflict, "local credential is already configured")
		return
	}
	h.completeLocalLogin(w, r, true)
}

// LocalLogin authenticates the single human user with the locally stored
// credential. Errors are deliberately generic so callers cannot distinguish
// the username from the password.
func (h *Handler) LocalLogin(w http.ResponseWriter, r *http.Request) {
	if !h.cfg.LocalMode {
		http.NotFound(w, r)
		return
	}
	req, ok := decodeLocalCredentialRequest(w, r)
	if !ok {
		return
	}
	credential, err := h.loadLocalCredential(r.Context())
	if err != nil {
		writeError(w, http.StatusUnauthorized, "invalid username or password")
		return
	}
	if credential.LockedUntil.Valid && time.Now().Before(credential.LockedUntil.Time) {
		writeError(w, http.StatusTooManyRequests, "too many attempts; try again later")
		return
	}
	normalizedUsername := strings.ToLower(strings.TrimSpace(req.Username))
	candidateHash := deriveLocalPassword(req.Password, credential.Salt, credential.Iterations)
	usernameOK := subtle.ConstantTimeCompare(
		[]byte(normalizedUsername), []byte(credential.Username),
	) == 1
	passwordOK := subtle.ConstantTimeCompare(candidateHash, credential.Hash) == 1
	if !usernameOK || !passwordOK {
		h.recordLocalLoginFailure(r.Context(), credential.Failures+1)
		writeError(w, http.StatusUnauthorized, "invalid username or password")
		return
	}
	_, _ = h.DB.Exec(
		r.Context(),
		`UPDATE lifeos_local_credential
		 SET failed_attempts = 0, locked_until = NULL, updated_at = now()
		 WHERE singleton = 1`,
	)
	h.completeLocalLogin(w, r, true)
}

// LocalAutomationLogin gives the local controller a JWT without exposing or
// reusing the chairman's password. The high-entropy token comes from a private
// file generated by the LifeOS launcher and the route is only mounted in
// loopback-only local mode.
func (h *Handler) LocalAutomationLogin(w http.ResponseWriter, r *http.Request) {
	if !h.cfg.LocalMode {
		http.NotFound(w, r)
		return
	}
	expected := h.cfg.LocalAutomationToken
	provided := strings.TrimSpace(r.Header.Get("X-LifeOS-Automation-Token"))
	if len(expected) < 32 || len(provided) != len(expected) ||
		subtle.ConstantTimeCompare([]byte(provided), []byte(expected)) != 1 {
		writeError(w, http.StatusUnauthorized, "invalid automation credential")
		return
	}
	var req LocalAutomationRequest
	r.Body = http.MaxBytesReader(w, r.Body, localAuthBodyLimit)
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&req); err != nil && !errors.Is(err, io.EOF) {
		writeError(w, http.StatusBadRequest, "invalid automation request")
		return
	}
	if strings.TrimSpace(req.AgentName) != "" {
		h.completeLocalAgentAutomationLogin(w, r, strings.TrimSpace(req.AgentName))
		return
	}
	h.completeLocalLogin(w, r, false)
}

func (h *Handler) completeLocalAgentAutomationLogin(w http.ResponseWriter, r *http.Request, agentName string) {
	user, workspace, changed, err := h.ensureLocalIdentity(r.Context())
	if err != nil {
		slog.Error("local mode bootstrap failed", "error", err)
		writeError(w, http.StatusInternalServerError, "failed to initialize local workspace")
		return
	}
	agents, err := h.Queries.ListAgents(r.Context(), workspace.ID)
	if err != nil {
		slog.Error("local automation agent lookup failed", "error", err)
		writeError(w, http.StatusInternalServerError, "failed to resolve local automation actor")
		return
	}
	var actor *db.Agent
	for index := range agents {
		candidate := &agents[index]
		if candidate.Name == agentName &&
			candidate.OwnerID.Valid &&
			uuidToString(candidate.OwnerID) == uuidToString(user.ID) &&
			!candidate.ArchivedAt.Valid {
			actor = candidate
			break
		}
	}
	if actor == nil {
		writeError(w, http.StatusBadRequest, "local automation agent not found")
		return
	}
	tokenString, err := h.issueLocalAgentAutomationJWT(user, workspace, *actor)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to create local automation session")
		return
	}
	if changed {
		h.notifyDaemonWorkspacesChanged(uuidToString(user.ID))
	}
	writeJSON(w, http.StatusOK, LocalLoginResponse{
		Token:     tokenString,
		User:      userToResponse(user),
		Workspace: workspaceToResponse(workspace),
		Actor: &LocalActorResponse{
			Type: "agent",
			ID:   uuidToString(actor.ID),
			Name: actor.Name,
		},
	})
}

func (h *Handler) issueLocalAgentAutomationJWT(user db.User, workspace db.Workspace, agent db.Agent) (string, error) {
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, jwt.MapClaims{
		"sub":             uuidToString(user.ID),
		"email":           user.Email,
		"name":            user.Name,
		"exp":             time.Now().Add(auth.AuthTokenTTL()).Unix(),
		"iat":             time.Now().Unix(),
		"actor_source":    auth.LocalAgentActorSource,
		"agent_id":        uuidToString(agent.ID),
		"actor_workspace": uuidToString(workspace.ID),
	})
	return token.SignedString(auth.JWTSecret())
}

func (h *Handler) completeLocalLogin(w http.ResponseWriter, r *http.Request, setCookies bool) {

	user, workspace, changed, err := h.ensureLocalIdentity(r.Context())
	if err != nil {
		slog.Error("local mode bootstrap failed", "error", err)
		writeError(w, http.StatusInternalServerError, "failed to initialize local workspace")
		return
	}

	tokenString, err := h.issueJWT(user)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to create local session")
		return
	}
	if setCookies {
		if err := auth.SetAuthCookies(w, tokenString); err != nil {
			writeError(w, http.StatusInternalServerError, "failed to create local session")
			return
		}
	}
	if changed {
		h.notifyDaemonWorkspacesChanged(uuidToString(user.ID))
	}

	writeJSON(w, http.StatusOK, LocalLoginResponse{
		Token:     tokenString,
		User:      userToResponse(user),
		Workspace: workspaceToResponse(workspace),
	})
}

func decodeLocalCredentialRequest(w http.ResponseWriter, r *http.Request) (LocalCredentialRequest, bool) {
	var req LocalCredentialRequest
	r.Body = http.MaxBytesReader(w, r.Body, localAuthBodyLimit)
	decoder := json.NewDecoder(r.Body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid local credential request")
		return LocalCredentialRequest{}, false
	}
	return req, true
}

func validateLocalCredential(username, password string) (string, string) {
	normalizedUsername := strings.ToLower(strings.TrimSpace(username))
	if !localUsernamePattern.MatchString(normalizedUsername) {
		return "", "username must be 3-64 characters using letters, numbers, dot, underscore, or hyphen"
	}
	passwordRunes := utf8.RuneCountInString(password)
	if passwordRunes < 12 || passwordRunes > 128 {
		return "", "password must be 12-128 characters"
	}
	categories := 0
	checks := []func(rune) bool{
		unicode.IsLower,
		unicode.IsUpper,
		unicode.IsDigit,
		func(value rune) bool { return unicode.IsPunct(value) || unicode.IsSymbol(value) },
	}
	for _, check := range checks {
		if strings.IndexFunc(password, check) >= 0 {
			categories++
		}
	}
	if categories < 3 {
		return "", "password must include at least three of lowercase, uppercase, numbers, and symbols"
	}
	if strings.Contains(strings.ToLower(password), normalizedUsername) {
		return "", "password must not contain the username"
	}
	return normalizedUsername, ""
}

func deriveLocalPassword(password string, salt []byte, iterations int) []byte {
	block := make([]byte, len(salt)+4)
	copy(block, salt)
	binary.BigEndian.PutUint32(block[len(salt):], 1)
	mac := hmac.New(sha256.New, []byte(password))
	_, _ = mac.Write(block)
	u := mac.Sum(nil)
	result := append([]byte(nil), u...)
	for i := 1; i < iterations; i++ {
		mac.Reset()
		_, _ = mac.Write(u)
		u = mac.Sum(nil)
		for j := range result {
			result[j] ^= u[j]
		}
	}
	return result
}

func (h *Handler) loadLocalCredential(ctx context.Context) (localCredential, error) {
	var credential localCredential
	err := h.DB.QueryRow(
		ctx,
		`SELECT username, password_salt, password_hash, password_iterations,
		        failed_attempts, locked_until
		 FROM lifeos_local_credential WHERE singleton = 1`,
	).Scan(
		&credential.Username,
		&credential.Salt,
		&credential.Hash,
		&credential.Iterations,
		&credential.Failures,
		&credential.LockedUntil,
	)
	return credential, err
}

func (h *Handler) recordLocalLoginFailure(ctx context.Context, failures int) {
	_, err := h.DB.Exec(
		ctx,
		`UPDATE lifeos_local_credential
		 SET failed_attempts = $1,
		     locked_until = CASE WHEN $1 >= $2 THEN now() + ($3 * interval '1 second') ELSE NULL END,
		     updated_at = now()
		 WHERE singleton = 1`,
		failures, localMaxFailedAttempts, int(localLockDuration.Seconds()),
	)
	if err != nil {
		slog.Warn("failed to record local login attempt", "error", err)
	}
}

func (h *Handler) localAuthConfigured(ctx context.Context) (bool, error) {
	var configured bool
	err := h.DB.QueryRow(
		ctx,
		`SELECT EXISTS(SELECT 1 FROM lifeos_local_credential WHERE singleton = 1)`,
	).Scan(&configured)
	return configured, err
}

// ensureLocalIdentity is intentionally repairable rather than transactional:
// every step is idempotent, so a process interruption or two browser tabs
// racing on first launch converges on the same unique user, workspace, and
// membership during the next call.
func (h *Handler) ensureLocalIdentity(ctx context.Context) (db.User, db.Workspace, bool, error) {
	changed := false

	user, err := h.Queries.GetUserByEmail(ctx, localUserEmail)
	if isNotFound(err) {
		user, err = h.Queries.CreateUser(ctx, db.CreateUserParams{
			Name:  localUserName,
			Email: localUserEmail,
		})
		if isUniqueViolation(err) {
			user, err = h.Queries.GetUserByEmail(ctx, localUserEmail)
		}
		changed = err == nil
	}
	if err != nil {
		return db.User{}, db.Workspace{}, changed, err
	}

	user, err = h.Queries.UpdateUser(ctx, db.UpdateUserParams{
		ID:       user.ID,
		Name:     localUserName,
		Language: pgtype.Text{String: "zh-Hans", Valid: true},
		Timezone: pgtype.Text{String: "Asia/Shanghai", Valid: true},
	})
	if err != nil {
		return db.User{}, db.Workspace{}, changed, err
	}
	user, err = h.Queries.MarkUserOnboarded(ctx, user.ID)
	if err != nil {
		return db.User{}, db.Workspace{}, changed, err
	}

	workspace, err := h.Queries.GetWorkspaceBySlug(ctx, localWorkspaceSlug)
	if isNotFound(err) {
		workspace, err = h.Queries.CreateWorkspace(ctx, db.CreateWorkspaceParams{
			Name:        localWorkspaceName,
			Slug:        localWorkspaceSlug,
			Description: pgtype.Text{String: "AI 星耀与陈星耀的本地工作台", Valid: true},
			Context:     pgtype.Text{String: localWorkspaceBrief, Valid: true},
			IssuePrefix: "LIFE",
		})
		if isUniqueViolation(err) {
			workspace, err = h.Queries.GetWorkspaceBySlug(ctx, localWorkspaceSlug)
		}
		if err == nil {
			changed = true
		}
	}
	if err != nil {
		return db.User{}, db.Workspace{}, changed, err
	}

	_, err = h.Queries.GetMemberByUserAndWorkspace(ctx, db.GetMemberByUserAndWorkspaceParams{
		UserID:      user.ID,
		WorkspaceID: workspace.ID,
	})
	if isNotFound(err) {
		_, err = h.Queries.CreateMember(ctx, db.CreateMemberParams{
			WorkspaceID: workspace.ID,
			UserID:      user.ID,
			Role:        "owner",
		})
		if isUniqueViolation(err) {
			_, err = h.Queries.GetMemberByUserAndWorkspace(ctx, db.GetMemberByUserAndWorkspaceParams{
				UserID:      user.ID,
				WorkspaceID: workspace.ID,
			})
		}
		if err == nil {
			changed = true
		}
	}
	if err != nil {
		return db.User{}, db.Workspace{}, changed, err
	}

	return user, workspace, changed, nil
}
