// Code generated by scripts/generate-text-preview-types.mjs. DO NOT EDIT.
// Edit text_preview_types.json and run `pnpm generate:text-preview-types`.

package handler

var textPreviewContentTypes = newTextPreviewSet(
	"application/json",
	"application/javascript",
	"application/xml",
	"application/x-yaml",
	"application/yaml",
	"application/toml",
	"application/x-sh",
	"application/x-httpd-php",
)

var textPreviewExtensions = newTextPreviewSet(
	// Markdown
	"md",
	"markdown",
	// Plain text
	"txt",
	"log",
	"csv",
	"tsv",
	"gitignore",
	// Web
	"html",
	"htm",
	"xml",
	// Stylesheets
	"css",
	// Sass
	"scss",
	"sass",
	// Less
	"less",
	// JSON
	"json",
	// YAML
	"yml",
	"yaml",
	// INI-style config
	"toml",
	"ini",
	"conf",
	// Build files
	"dockerfile",
	// Makefiles
	"makefile",
	// Shell
	"sh",
	"bash",
	"zsh",
	// Python
	"py",
	// Ruby
	"rb",
	// Go
	"go",
	// Rust
	"rs",
	// TypeScript
	"ts",
	"tsx",
	// JavaScript
	"js",
	"jsx",
	"mjs",
	"cjs",
	// Java
	"java",
	// Kotlin
	"kt",
	// Swift
	"swift",
	// C
	"c",
	"h",
	// C++
	"cc",
	"cpp",
	"hpp",
	// C#
	"cs",
	// PHP
	"php",
	// Lua
	"lua",
	// Vim script
	"vim",
	// SQL
	"sql",
)

var textPreviewBasenames = newTextPreviewSet(
	// Dockerfile
	"dockerfile",
	// Makefile
	"makefile",
	// Environment and ignore files
	".env",
	".gitignore",
)

func newTextPreviewSet(values ...string) map[string]struct{} {
	set := make(map[string]struct{}, len(values))
	for _, value := range values {
		set[value] = struct{}{}
	}
	return set
}
