export type MemberRole = "owner" | "admin" | "member";

export type WorkspaceRepoType = "github" | "local";

export interface WorkspaceRepo {
  /** Stable identifier. Generated by the server if omitted on create. */
  id: string;
  /** Human-readable name shown in UI and used as the default worktree dir name. */
  name: string;
  /** Source of truth for the repo. "github" clones the URL; "local" uses a path on the daemon host. */
  type: WorkspaceRepoType;
  /** Remote URL (required when type === "github"). */
  url?: string;
  /** Absolute filesystem path on the daemon host (required when type === "local"). */
  local_path?: string;
  description: string;
}

export interface Workspace {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  context: string | null;
  settings: Record<string, unknown>;
  repos: WorkspaceRepo[];
  issue_prefix: string;
  created_at: string;
  updated_at: string;
}

export interface Member {
  id: string;
  workspace_id: string;
  user_id: string;
  role: MemberRole;
  created_at: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface MemberWithUser {
  id: string;
  workspace_id: string;
  user_id: string;
  role: MemberRole;
  created_at: string;
  name: string;
  email: string;
  avatar_url: string | null;
}
