name: Build Web Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag to publish"
        required: false
        default: "crm-latest"

jobs:
  delegate:
    uses: ./.github/workflows/build-docker-images.yml
    with:
      image_tag: ${{ github.event.inputs.image_tag || 'crm-latest' }}
      image: web
