#include "RNOH/PackageProvider.h"
#include "RNOHPackagesFactory.h"
#include "generated/RNOHGeneratedPackage.h"
#include "RNOH/ArkTSTurboModule.h"
#include "RNOH/TurboModuleFactory.h"

using namespace rnoh;

namespace {

// CPP-side proxies for ArkTS-only turbo modules. The ArkTS side creates the
// module instance (bridged through PackageProvider.ets); without a CPP
// delegate returning an ArkTSTurboModule for the same name, the module
// request dies with "Couldn't find Turbo Module ... on the CPP side".
// methodMap_ entries must match the ArkTS class methods (name, argc).

class MulticaSecureStorageTurboModule : public ArkTSTurboModule {
 public:
  MulticaSecureStorageTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
      : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_ASYNC_METHOD_METADATA(set, 2),
        ARK_ASYNC_METHOD_METADATA(get, 1),
        ARK_ASYNC_METHOD_METADATA(remove, 1),
    };
  }
};

class MulticaClipboardTurboModule : public ArkTSTurboModule {
 public:
  MulticaClipboardTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
      : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_ASYNC_METHOD_METADATA(setString, 1),
        ARK_ASYNC_METHOD_METADATA(getString, 0),
    };
  }
};

// Safe-area insets (physical px) for lib/safe-area — the vendored tpl
// safe-area module resolves zeros in common window states.
class MulticaSafeAreaTurboModule : public ArkTSTurboModule {
 public:
  MulticaSafeAreaTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
      : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_ASYNC_METHOD_METADATA(getInsets, 0),
    };
  }
};

class MulticaHapticsTurboModule : public ArkTSTurboModule {
 public:
  MulticaHapticsTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
      : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_ASYNC_METHOD_METADATA(impactLight, 0),
        ARK_ASYNC_METHOD_METADATA(impactMedium, 0),
        ARK_ASYNC_METHOD_METADATA(notificationSuccess, 0),
        ARK_ASYNC_METHOD_METADATA(notificationError, 0),
    };
  }
};

// Media/document picker over @ohos.file.picker. Both methods are
// Promise-returning and copy the pick into the HAP cache before resolving
// (see MulticaMediaPickerModule.ts).
class MulticaMediaPickerTurboModule : public ArkTSTurboModule {
 public:
  MulticaMediaPickerTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
      : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_ASYNC_METHOD_METADATA(pickImage, 0),
        ARK_ASYNC_METHOD_METADATA(pickDocument, 0),
    };
  }
};

// netinfo tpl module proxy (source-dir package, no codegen glue). The
// ArkTS side bridges RNCNetInfo through PackageProvider.ets.
class RNCNetInfoTurboModule : public ArkTSTurboModule {
 public:
  RNCNetInfoTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
      : ArkTSTurboModule(ctx, name) {
    methodMap_ = {
        ARK_ASYNC_METHOD_METADATA(getCurrentState, 1),
        ARK_METHOD_METADATA(addListener, 1),
        ARK_METHOD_METADATA(removeListeners, 1),
    };
  }
};

class MulticaTurboModuleFactoryDelegate : public TurboModuleFactoryDelegate {
 public:
  SharedTurboModule createTurboModule(Context ctx, const std::string& name) const override {
    if (name == "MulticaSecureStorage") {
      return std::make_shared<MulticaSecureStorageTurboModule>(ctx, name);
    }
    if (name == "MulticaClipboard") {
      return std::make_shared<MulticaClipboardTurboModule>(ctx, name);
    }
    if (name == "MulticaHaptics") {
      return std::make_shared<MulticaHapticsTurboModule>(ctx, name);
    }
    if (name == "MulticaMediaPicker") {
      return std::make_shared<MulticaMediaPickerTurboModule>(ctx, name);
    }
    if (name == "MulticaSafeArea") {
      return std::make_shared<MulticaSafeAreaTurboModule>(ctx, name);
    }
    if (name == "RNCNetInfo") {
      return std::make_shared<RNCNetInfoTurboModule>(ctx, name);
    }
    return nullptr;
  }
};

class MulticaCppPackage : public Package {
 public:
  explicit MulticaCppPackage(Package::Context ctx) : Package(ctx) {}

  std::unique_ptr<TurboModuleFactoryDelegate> createTurboModuleFactoryDelegate() override {
    return std::make_unique<MulticaTurboModuleFactoryDelegate>();
  }
};

} // anonymous namespace

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  auto packages = createRNOHPackages(ctx); // <= autolinking
  packages.push_back(std::make_shared<RNOHGeneratedPackage>(
      ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
  packages.push_back(std::make_shared<MulticaCppPackage>(ctx));
  return packages;
}